### ISSUE TITLE
Basic example doesn't serve static files

### ISSUE THREAD

**Issue by srad** [unosquare/embedio#10]
I just installed the nuget package and created a simple index.html file an placed it under c:/web/index.html and used the first code example to get the index.html served within the web browser (which automatically opens given the demo code) and it fails because the server is not reachable.

Could you try if the code is actually working, or is anything else required here?

**Comment by geoperez** [comment]
Let me try to reproduce it.

**Comment by geoperez** [comment]
I found some minor issues in the basic sample that I'll fix. I created a console app with the Nuget and the next code and it's working fine:

```csharp
namespace Company.Project
{
    using System;
    using Unosquare.Labs.EmbedIO;
    using Unosquare.Labs.EmbedIO.Log;
    using Unosquare.Labs.EmbedIO.Modules;

    class Program
    {
        /// <summary>
        /// Defines the entry point of the application.
        /// </summary>
        /// <param name="args">The arguments.</param>
        static void Main(string[] args)
        {
            var url = "http://localhost:9696/";
            if (args.Length > 0)
                url = args[0];

            // Our web server is disposable. Note that if you don't want to use logging,
            // there are alternate constructors that allow you to skip specifying an ILog object.
            using (var server = new WebServer(url, new SimpleConsoleLog()))
            {
                // First, we will configure our web server by adding Modules.
                // Please note that order DOES matter.
                // ================================================================================================
                // If we want to enable sessions, we simply register the LocalSessionModule
                // Beware that this is an in-memory session storage mechanism so, avoid storing very large objects.
                // You can use the server.GetSession() method to get the SessionInfo object and manupulate it.
                // You could potentially implement a distributed session module using something like Redis
                server.RegisterModule(new LocalSessionModule());

                // Here we setup serving of static files
                server.RegisterModule(new StaticFilesModule("c:/web"));
                // The static files module will cache small files in ram until it detects they have been modified.
                server.Module<StaticFilesModule>().UseRamCache = true;
                server.Module<StaticFilesModule>().DefaultExtension = ".html";
                // We don't need to add the line below. The default document is always index.html.
                //server.Module<Modules.StaticFilesWebModule>().DefaultDocument = "index.html";

                // Once we've registered our modules and configured them, we call the RunAsync() method.
                // This is a non-blocking method (it return immediately) so in this case we avoid
                // disposing of the object until a key is pressed.
                //server.Run();
                server.RunAsync();

                // Fire up the browser to show the content if we are debugging!
#if DEBUG
                var browser = new System.Diagnostics.Process()
                {
                    StartInfo = new System.Diagnostics.ProcessStartInfo(url) { UseShellExecute = true }
                };
                browser.Start();
#endif
                // Wait for any key to be pressed before disposing of our web server.
                // In a service we'd manage the lifecycle of of our web server using
                // something like a BackgroundWorker or a ManualResetEvent.
                Console.ReadKey(true);
            }
        }
    }
}
```

**Comment by srad** [comment]
Thanks for the quick reply, I still get an exception which I thought was related to the access rights level to the file system, but raising the level to admin didn't made it go away. Any idea what this is?

My VS is in German, but the trace should be readable:
```
Web server prefix 'http://localhost:9696/' added.
Finished Loading Web Server.
"App .vshost.exe" (CLR v4.0.30319: LernBar Studio.vshost.exe): "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\mscorlib.resources\v4.0_4.0.0.0_de_b77a5c561934e089\mscorlib.resources.dll" geladen. Das Modul wurde ohne Symbole erstellt.
Started HTTP Listener
System.Net.HttpListenerPrefixCollection
Listener Closed.
System.ObjectDisposedException: Auf das verworfene Objekt kann nicht zugegriffen werden
(object can't be accessed).
Objektname: "System.Net.HttpListener".
   bei System.Net.HttpListener.CheckDisposed()
   bei System.Net.HttpListener.EndGetContext(IAsyncResult asyncResult)
   bei System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   bei Unosquare.Labs.EmbedIO.WebServer.<<RunAsync>b__4>d__7.MoveNext()
```

**Comment by geoperez** [comment]
It's seem like the tcp port can not be open. What Windows version are you
using?

**Comment by mariodivece** [comment]
I would also suggest changing the port. Go for a url prefix such as:

http://localhost:49618/

**Comment by srad** [comment]
I'm on Windows 8.1, VS 2013, .net 4.5
@mariodivece Changing the port didn't changed it, still the same exception. I tried a few ports.

**Comment by mariodivece** [comment]
Quick question: Are you trying from the nuget package or from source? If from source, can you do a step-through and let us know which line breaks it? If from nuget can you send us the version number pls?

Please forgive the brevity and typos. Message sent from a mobile device.
________________________________

**Comment by srad** [comment]
I used the nuget package, version: 1.0.3
I could also try using the source code, but I'm not a full c# programmer, I'll try to figure it out.

**Comment by srad** [comment]
Hold on, I didn't realized that the example was only supposed to be run from a console application. But still the exception irritated me.

However I created a console only application and it's seems to be OK. I ran it within an forms project.

Is there any guideline how I should/can embed this inside such an application an existing, or can you give me some tips? Do I have to keep I running in a loop in a background or how do I handle this.

**Comment by mariodivece** [comment]
I created a new project from embedio package 1.0.3, added index.html to c:\web and it worked just fine... I'm attaching the zip file with the VS 2013 project. Can you let us know if it works?
https://www.dropbox.com/s/0zkg1vwn5qrsiy3/ConsoleApplication1.zip?dl=0

**Comment by mariodivece** [comment]
What kind of application are you writing? You don't have to run it in a console app. In fact we use it in Windows services and linux daemons. If you'd like to run it in say, a WPF app or a WinForms app, you'd just spawn a new thread and leave it there.

**Comment by srad** [comment]
It's an desktop application which hosts a local web application and I want to implement a REST API to the web server, so I can't move the application later online and retain the web application implementation, once the online service is done.

**Comment by mariodivece** [comment]
Take a look at this sample code I have created for you. It uses a background worker to host the web server in your winforms app.
https://www.dropbox.com/s/yzbo365m8hlqrzf/WindowsFormsApplication1.zip?dl=0

**Comment by srad** [comment]
Got it. Guys you are just awesome and really helpful thank you! I might be annoying you in the near future again, since I'm playing with you project. Thanks again :)

**Comment by mariodivece** [comment]
You bet, and good luck with your project! Closing this one down.
