### ISSUE TITLE
V1.91 not working with Port 80

### ISSUE THREAD

**Issue by stephanblaurock** [unosquare/embedio#101]
Hello,
since i have updated embedio from 1.8.0 to 1.9.1 i can't get working the Webserver to listen on port 80.
My Url-Prefix is: "http://<domainname>:80/"
**The local IIS has no binding to this domain and port**. And if i use the V1.8.0 all works fine on port 80. But i would like to upgrade because of the performance-issue.

If i make a request i get an 404-error (not found). Come this response from the IIS??

Can you help me?

**Comment by geoperez** [comment]
Hi,

Are you using * for any IP?  Like this: `http://*:80/` 

If the response is IIS you may have the following Response Header (you may check Chrome Developer Tools to see it):

`server:Microsoft-IIS/10.0`

**Comment by stephanblaurock** [comment]
Hi, thanks for your quick response!

No i using "http://mydomain.de:80" as prefix.

The response contains following:
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - Datei oder Verzeichnis wurde nicht gefunden.</title>
<style type="text/css">

</style>
</head>
<body>
<div id="header"><h1>Serverfehler</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - Datei oder Verzeichnis wurde nicht gefunden.</h2>
  <h3>Die gesuchte Ressource wurde möglicherweise entfernt oder umbenannt, oder sie steht vorübergehend nicht zur Verfügung.</h3>
 </fieldset></div>
</div>
</body>
</html>

If i shutdown the local IIS i get following response:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Not Found</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Not Found</h2>
<hr><p>HTTP Error 404. The requested resource is not found.</p>
</BODY></HTML>

**Comment by stephanblaurock** [comment]
sorry, i try to insert the response as code:
If i shutdown the IIS i get following response:
`<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Not Found</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Not Found</h2>
<hr><p>HTTP Error 404. The requested resource is not found.</p>
</BODY></HTML>`

**Comment by geoperez** [comment]
The second response is from EmbedIO. Ok let me take a look what's going on.

What framework version are you using?

**Comment by stephanblaurock** [comment]
i testet with 4.6.2 and 4.7

**Comment by geoperez** [comment]
The response is not from EmbedIO, it's something else opening the port 80.

**Comment by chubbsnes65** [comment]
Hi @stephanblaurock try this:

- Stop IIS and EmbedIO.
- Run a CMD as administartor and execute "netstat -aon" if you got an PID 4 for port 80
![image](https://user-images.githubusercontent.com/17009334/31683771-7520fd3c-b343-11e7-93ff-5eb492dedffe.png)
that means the port 80 is in use for a system process, you should lookup for which system services are 
using this port. 
I found this https://superuser.com/questions/352017/pid4-using-port-80 and it was useful for me I hope this can help you.

**Comment by stephanblaurock** [comment]
Hello @chubbsnes65 ,
thanks for your answer. I tried to find out which system service are using the 80er port, but only the IIS use this port. Now i searched several hours, but i can't get it to work :-(

Always i becom the response from "Microsoft-HTTPAPI/2.0".

Now i have make a little test with the System.Net.HttpListener - AND IT WORKS!! :-)
@geoperez : are you using the Unosquare.Net.HttpListener instead of System.Net.HttpListener?
![image](https://user-images.githubusercontent.com/25195741/31720991-68b2a7b4-b418-11e7-9ff7-0d0c5c73cb88.png)
Can you imagine what the problem is?

Here the quick and dirty code that works fine:
`	
listener = new HttpListener();
			listener.Prefixes.Add("http://test2.netlogger.eu:80/");
			listener.Start();
			listener.BeginGetContext(new AsyncCallback(ListenerCallback), listener);

private void ListenerCallback(IAsyncResult Result) {
			HttpListenerContext Context;
			try {
				Context = listener.EndGetContext(Result);
				string RequestInput = Context.Request.ToString();
				this.ProcessRequest(Context);
			} catch (HttpListenerException eR) {
				System.Diagnostics.Debug.WriteLine(eR.ToString());
			}
			try {
				listener.BeginGetContext(new AsyncCallback(ListenerCallback), listener);
			} catch (InvalidOperationException eR) {
				System.Diagnostics.Debug.WriteLine(eR.ToString());
			}
		}
		private void ProcessRequest(HttpListenerContext context) {
			HttpListenerRequest Request = context.Request;
			byte[] byteArr = Encoding.UTF8.GetBytes(DateTime.Now.ToString("T")+": Hello World!");
			context.Response.OutputStream.Write(byteArr, 0, byteArr.Length);
			context.Response.Close();
		}
`

**Comment by geoperez** [comment]
Since v1.9 the target net46 is using Unosquare.Net and netstandard2.0 System.Net.

You can try to target net47 or better to use System.Net.

**Comment by geoperez** [comment]
@chubbsnes65 did you test using net46?

**Comment by stephanblaurock** [comment]
hmm, i set the target-framework in the project-settings to 4.7:
![image](https://user-images.githubusercontent.com/25195741/31722084-71278d8a-b41b-11e7-8f17-d583d2e29c45.png)
is this correct or have i do something else?
If i debug with this settings the Unosquare.Net is used.

**Comment by geoperez** [comment]
That's odd, let me check how my VS is resolving the nuget.

**Comment by chubbsnes65** [comment]
I tested with version 4.7 and using Unosquare.Net and works for me
static void Main(string[] args)
        {
            // Our web server is disposable. 
            using (var server = new WebServer(80))
            {
                server.RegisterModule(new FallbackModule((ctx, ct) => ctx.JsonResponse(new { Message = "Error " })));

                // Once we've registered our modules and configured them, we call the RunAsync() method.
                server.RunAsync();
                Console.ReadKey();
            }
        }

**Comment by geoperez** [comment]
I'm updating the nuget to include target NET 4.7 with System.Net and keeping NET 4.6 with Unosquare.Net.

**Comment by geoperez** [comment]
I just updated the nuget to v1.10 to fix the issue with target NET 4.7.

**Comment by stephanblaurock** [comment]
thanks a lot for your quick help!!! Now it works as expected 👍
