### ISSUE TITLE
WebApiModule always returns 404

### ISSUE THREAD

**Issue by MarcoTheFirst** [unosquare/embedio#105]
Hi

I'd like to run a simple WebApiModule using the following code:

   ```
         WebServer server = new Unosquare.Labs.EmbedIO.WebServer("http://localhost:29879/");            
            server.RegisterModule(new WebApiModule());
            server.Module<WebApiModule>().RegisterController<TestApiController>();
            server.RunAsync();`
```

And the controller class:

    public class TestApiController: WebApiController
    {
        [WebApiHandler(HttpVerbs.Get, "/api/Hello/*")]
        public string GetHello(WebServer server, HttpListenerContext context)
        {
            return "Hello World";
        }
    }

However, EmbedIO always returns a 404 when I try to access http://localhost:29879/api/Hello/ using my regular browser.

Any ideas?
Thanks, Marco

**Comment by geoperez** [comment]
I don't see the unit testing failing... let me take a look in your code.

**Comment by geoperez** [comment]
I see what is happening....

Your WebAPI method signture is wrong. You must return `bool` or `Task<bool>` and you need to write to the Response output directly. In the following example I write a JSON using a helper method;

```
public class TestApiController : WebApiController
        {
            [WebApiHandler(HttpVerbs.Get, "/api/Hello/*")]
            public bool GetHello(WebServer server, HttpListenerContext context)
            {
                context.JsonResponse(new {Message = "HELLO"});
                return true;
            }
        }
```

**Comment by MarcoTheFirst** [comment]
ah, sorry, I was trapped in my old ASP.NET Web API thinking.

On another note: Where does the method JsonResponse() come from? It is unknown in my project and intellisense doesn't offer to add any namespace... so it must be in a diferent Nuget?

**Comment by geoperez** [comment]
It's an extension method, try to add the namespace `Unosquare.Labs.EmbedIO`.

**Comment by MarcoTheFirst** [comment]
Ah I found the problem... I was referencing System.Net, and so the extension was incompatible.

Now it works. Thanks a lot for the great and impressive work!
