### ISSUE TITLE
Using EmbedIO Just To Serve Files?

### ISSUE THREAD

**Issue by thebitbrine** [unosquare/embedio#107]
I'm writing a HTTP file server (Similar to [HFS](https://www.google.com/search?q=HFS)) which already has fancy directory index, users, server status and such, and currently one of my problems is serving partial contents for multi-part downloading and pause and resume feature. But i couldn't find a good way to achieve that.
Apparently `EmbedIO` does a fine job serving partial contents,
and i was wondering how could i use `EmbedIO.Modules.StaticFilesModule` (or something else) to serve the files through the same request without tearing apart my code (built on `HttpListener()`) and building it again on top of `EmbedIO`.
As far as i can recall `EmbedIO` does use `HttpListener()` too, so it wont be much of a problem i guess.
I dug through `EmbedIO`'s code and found a method called `HandleFile`, which does exactly what i need but i couldn't simply copy-paste it into my code because it throws a ton of errors which some are caused because of changes between` .NET` versions and some were just methods with long dependency chains.
And there are some other stuff that are originally private/internal from the source code like `Strings.BrowserTimeFormat` and such that i would have to modify them, recompile them and test them to see if they work.

The question is: Are there any better options?

**Comment by mariodivece** [comment]
You need to implement HTTP range request header parsing, binary file reading, and response headers accordingly. This issue is not EmbedIO related. Closing.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests

**Comment by geoperez** [comment]
Range request is already implemented in Embedio StaticFileModule, you may use this module as base for your own module.
