### ISSUE TITLE
Serving HTML Files From MemoryStream?

### ISSUE THREAD

**Issue by thebitbrine** [unosquare/embedio#108]
#107: "_After doing more digging i decided to go the hard but better way which was building the whole app around `EmbedIO` because of performance and security reasons._"

As i would be generating the HTML file programmatically, i need a way to serve the `HTML` content from a `MemoryStream` or even a `string`.

Is there any way that is could be achieved?

**Comment by mariodivece** [comment]
Sure. The exact same way the other modules generate content! This is one of the advantages of using EmbedIO! Simply inherit from the WebModule class and register your WebModule in you instance of EmbedIO. Example here: 
https://github.com/unosquare/embedio/blob/master/src/Unosquare.Labs.EmbedIO/Modules/FallbackModule.cs
