### ISSUE TITLE
Does EmbedIO support https on android?

### ISSUE THREAD

**Issue by AnderssonPeter** [unosquare/embedio#119]
Does EmbedIO support https on android I didn't find any thing in the documentation.

**Comment by geoperez** [comment]
Hi @AnderssonPeter, we aren't supporting HTTPS at NET46 target, but the NETSTANDARD* targets should be able to use HTTPS using the [HttpListener](https://msdn.microsoft.com/en-us/library/system.net.httplistener(v=vs.110).aspx) from Microsoft. They are many tutorials how to archieve HTTPS at Windows, but I don't really have idea how it may work at Android platform.

Sorry but we don't have any experience with Android HTTPS.
