### ISSUE TITLE
EmbedIO with NLog [help]

### ISSUE THREAD

**Issue by bufferUnderrun** [unosquare/embedio#120]
Hi,

I'm using NLog for logging as it handles some great features. 
How integrate NLog to take over the embedio internal logging system ?

Thanks for you answer.

**Comment by geoperez** [comment]
Hi @bufferUnderrun,

EmbedIO's logging is using SWAN Terminal component, you can redirect the log messages using the `OnLogMessageReceived` event. More info: https://github.com/unosquare/swan#example-3-forwarding-logging-messages

**Comment by bufferUnderrun** [comment]
Thanks for your help.

Just migrating to vs2017, at last, and discorering swan. Interesting tool.
