### ISSUE TITLE
Implement WebSocket Routing

### ISSUE THREAD

**Issue by firesharkstudios** [unosquare/embedio#123]
Does the websocket implementation also support the same routing rules.  Ideally like...

```
server.RegisterModule(new WebSocketsModule());
server.Module<WebSocketsModule>().RegisterWebSocketsServer<WebSocketsChatServer>("/chat/{id}");

```
or just...

```
server.RegisterModule(new WebSocketsModule());
server.Module<WebSocketsModule>().RegisterWebSocketsServer<WebSocketsChatServer>("/chat/*");
```

**Comment by geoperez** [comment]
Hi @firesharkstudios , the current `WebServer` routes handler support both strategies. Let me take a quick look into `WebSocketModule `if we can handle too.

**Comment by geoperez** [comment]
@firesharkstudios did you test the source code or you need a pre-release nuget?

**Comment by firesharkstudios** [comment]
I'll pull the source

**Comment by jpalcala** [comment]
HI @firesharkstudios just use `/test/{id}` as base path in `RequestRegexUrlParams()`.

**Comment by firesharkstudios** [comment]
Yes, that works.  Nice job.

fyi -- I think if the param name was "urlPattern" instead of "baseUrl" that I would have guessed the value properly.   The "base" prefix was throwing me off.

**Comment by jpalcala** [comment]
Yes you are right, sorry for the inconvenience, I'll fix this.

**Comment by firesharkstudios** [comment]
Great, not trying to be critical -- just trying to give constructive feedback to improve the project.  Thanks.

**Comment by jpalcala** [comment]
A new [EmbedIO](https://www.nuget.org/packages/EmbedIO/1.12.0) version has just been released with these changes.

**Comment by momo-the-monster** [comment]
RequestRegexUrlParams() doesn't exist in 3.0 - how do we route in a websocket now?
