### ISSUE TITLE
Implement Basic HTTP Authentication

### ISSUE THREAD

**Issue by FrankDoersam** [unosquare/embedio#125]
Hello, a great project! Is authentication on the roadmap? Thanks in advance.

**Comment by geoperez** [comment]
Hi Frank, there is no plan to include authentication. But we are open to pull requests 😃

**Comment by FrankDoersam** [comment]
okay thanks :) with the bear token could I solve it?

**Comment by geoperez** [comment]
Yes, we usually use the BearerToken module to authenticate. But a BASIC Http Authentication is out of scope for now.

**Comment by FrankDoersam** [comment]
of scope for now ... what do you mean ?

**Comment by geoperez** [comment]
no plans :)

**Comment by mariodivece** [comment]
Pull Requests are always welcome @FrankDoersam !

**Comment by mariodivece** [comment]
Can't you just read the HTTP headers from the HTTP context and check the logic there? You can write a custom module too you know?

**Comment by FrankDoersam** [comment]
We used in the past ServiceStack.
There we could mark the api methods with an attribute called authenticate. It think this would be the best Solution ? What think you ?

Von meinem iPhone gesendet

**Comment by geoperez** [comment]
We already have a basic auth module by @Tymonrare.
