### ISSUE TITLE
Broadcasting messages with WebSocket Server

### ISSUE THREAD

**Issue by FrankDoersam** [unosquare/embedio#126]
Hello everybody,

It is possible to send the WebApiController a broadcast via WebSocketsServer. As of today, the class is declared protected.

Thanks in advance

Best regards
Frank

**Comment by FrankDoersam** [comment]
*Method is declared protected.

**Comment by geoperez** [comment]
Also Send method. You need to derive the abstract class WebSocketServer and then you can use both methods. Check the chat WebSocketServer at the sample project.
