### ISSUE TITLE
Enhanced RegEx Routing

### ISSUE THREAD

**Issue by firesharkstudios** [unosquare/embedio#127]
I believe EmbedIO currently supports this..

`[WebApiHandler(HttpVerbs.Get, "/api/{resource}/{action}")]`

Is there a means to specify an actual regex expression?  Perhaps a syntax where you optionally add a colon after the name followed by the regex...

`[WebApiHandler(HttpVerbs.Get, "/api/{resource:contact|address|phone}/{action:insert|update|delete}")]`

or another example might be...

`[WebApiHandler(HttpVerbs.Get, "/api/ip/{ip:d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}}`

Trying to support actual regex expressions is a bit awkward if the named parameters use the curly bracket syntax since regexes can contain curly brackets.  Servers like Express (see [Express Routing](http://expressjs.com/en/guide/routing.html) prefix parameters with a colon).  

The syntax then might look like either...

`[WebApiHandler(HttpVerbs.Get, "/api/ip/:ip`
`[WebApiHandler(HttpVerbs.Get, "/api/ip/:ip:d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}`

**Comment by firesharkstudios** [comment]
Thinking about this more, I'm not sure the full regex syntax is all that necessary and useful (the IP example above probably isn't all that useful); however, supporting something like this is more useful...

`[WebApiHandler(HttpVerbs.Post, "/api/contact/{action:insert|update|delete}")]`

Although REST principles recommend mapping your actions to HTTP verbs, I generally find this awkward and confusing.  Instead, I prefer to do a POST with my action suffixed in the URL (yes, this breaks from REST principles but is more clear to me) and using a syntax like the above is much more concise than declaring three separate handlers.  Just a suggestion.

**Comment by geoperez** [comment]
Hi Kent, let me think about it.

**Comment by firesharkstudios** [comment]
I think this is a relatively minor improvement.  Maybe it g
