### ISSUE TITLE
Async Controller Actions

### ISSUE THREAD

**Issue by srad** [unosquare/embedio#13]
Since the controller actions are not tasks I wonder if you have another general notion on how to wait for I/O code in actions to complete?

Currently I'm using ```task.wait()``` for a task to complete, which doesn't seem to be 100% working, I need to debug a few cases yet. However, can I declare actions as Tasks?

**Comment by mariodivece** [comment]
All responses are already wrapped in async/await pattern. Your controller actions are all asynchronous:)

Please forgive the brevity and typos. Message sent from a mobile device.
________________________________

**Comment by srad** [comment]
I was going through a few options and also saw [uhttpsharp controller demo] (https://github.com/int6/uhttpsharp/blob/master/uhttpsharp-demo/Controllers/DemoController.cs) which declares actions as ```public Task<IControllerResponse> ...``` which I found a little less confusion and this would also allow to use straight the ```await``` keyword in the action without any ```task.wait()``` or similar technique.

Still I might be wrong, but just looking at it seems to be a benefit.

**Comment by geoperez** [comment]
@srad I created a branch (https://github.com/unosquare/embedio/tree/AsyncREST) where you can define ```await Task<bool> ...``` methods. Check if this is a better approach please.

@mariodivece What do you think of this branch?

**Comment by geoperez** [comment]
BTW check the sample at file https://github.com/unosquare/embedio/blob/AsyncREST/Unosquare.Labs.EmbedIO.Samples/RestApiSample.cs

**Comment by srad** [comment]
That is pretty cool.
What do you think of returning a response object/result like uhttpsharp does instead of ```bool```?

Because without event looking at a controller I would pretty much expect the signature to be something like ```public Task<IControllerResponse> ActionBla()``` returning something like ```Response.Render(HttpResponseCode.Ok, null);```

**Comment by geoperez** [comment]
The approach is different, our REST method returns a boolean just to indicate if the request was handled and the method must write the Response's output using for example ```context.JsonResponse```.

In the other hand, uhttpsharp is returning an interface where they can put any call to another class to write the content. It's pretty much the same, but Embedio is simpler. If you wish you can add these extra layers, but I really find it unnecessary.

Embedio REST Method -> call context.JsonResponse(object) -> return true
uhttpsharp  -> call Response.Render(ok, object) -> Create RenderResponse Object -> Render View -> return Response to Context

**Comment by srad** [comment]
I think I understand now that you go for less abstraction (which is not necessarily the same as simplicity), because I find uhttpsharp's approach semantically clearer, because it's more explicit.
The ```bool``` in the signature just bugs me, it's straight a question-mark looking at it. ;)

**Comment by geoperez** [comment]
I merged the Async branch to master.  Since we are not implementing return an interface in REST methods, I'm closing this issue now.
