### ISSUE TITLE
Single Page Application Routing

### ISSUE THREAD

**Issue by firesharkstudios** [unosquare/embedio#144]
Single page applications often use client side routing (like vue-router) and these client routers can modify the address bar and URL history as the user navigates within the single page application.  If a user bookmarks these URLs, the user would expect these URLs to open properly.

So, let's say a single page application has these physical files...

/project-dir/index.html
/project-dir/static/js/bundle.js
/project-dir/static/css/bundle.css

Ideally then any /static/* requests would serve the files from the /project-dir/static directory and all other directory requests would serve /project-dir/index.html.

So, all of these requests would effectively serve /index.html...

/
/contacts
/contact/spongebob
/contact/patrick

The client side logic contains a router that looks at the URL to display the correct content even though all these requests are loading /project-dir/index.html.

Here is someone addressing this same issue using IIS rewrite rules...

[https://www.mattburkedev.com/iis-rewrite-rule-for-single-page-apps/](https://www.mattburkedev.com/iis-rewrite-rule-for-single-page-apps/)

Is there a way to configure EmbedIO to properly serve a single page application that uses client side routing such that all /static requests are served normally and all other directory requests serve a specific file (/project-dir/index.html in the example above)?

**Comment by geoperez** [comment]
You can register the `FallbackModule `at the very end to redirect everything to the index.html.  We use this approach with Angular SPA and the client-side routing works just fine.

**Comment by bufferUnderrun** [comment]
There is a simple way, like i do, by using the 2 modules :

- WebApiModule : it exposes my REST Api to http://localhost/api/
- StaticFilesModules : it serves static files (SPA application with RiotJS) to http://localhost/index.html and consumes my rest api.

**Comment by firesharkstudios** [comment]
Thanks for the replies.  As suggested, adding the FallbackModule does exactly what I needed...

```
embedIOWebServer.RegisterModule(new FallbackModule((context, ct) => {
    using (var fileStream = new FileStream(Path.Combine(staticFullPath, "index.html"), FileMode.Open)) {
        fileStream.CopyTo(context.Response.OutputStream);
    }
    return true;
}));
```

I originally just passed "/index.html" to the FallbackModule but that was doing an HTTP redirect so I used the other constructor to read and serve the actual index.html file which leaves the URL intact.

**Comment by geoperez** [comment]
You can use the extension method `HtmlResponseAsync` to send a HTML string ;)
