### ISSUE TITLE
staticfilemodule: possible invalid char exception

### ISSUE THREAD

**Issue by benny856694** [unosquare/embedio#15]
Cause: 
the call to " context.Response.AddHeader(Constants.HeaderLastModified, utcFileDateString);" will trigger invalid char exception if running on non-english locale, since 'utcFileDataString' possibly has invalid chars (Chinese character in my case).

Possible fix: 
var utcFileDateString = fileDate.ToUniversalTime().ToString(Constants.BrowserTimeFormat, CultureInfo.InvariantCulture)  -  add InvariantCulture to the format function.

Thanks for the great project.

**Comment by geoperez** [comment]
Your PR was merged, thank you. I'll write some unit testing to validate the strings.

**Comment by benny856694** [comment]
hope to get the nuget release asap, so I can use it in my project, thanks. :)

**Comment by geoperez** [comment]
Sure thing, give me a minute.

On Wed, May 20, 2015 at 10:03 AM, benny856694 <notifications@github.com>
wrote:

> hope to get the nuget release asap, so I can use it in my project, thanks.
> :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/unosquare/embedio/issues/15#issuecomment-103919773>.
>



-- 
Geo Pérez

**Comment by geoperez** [comment]
New nuget https://www.nuget.org/packages/Embedio
