### ISSUE TITLE
Memoryleak in WebApiModule?

### ISSUE THREAD

**Issue by smedasn** [unosquare/embedio#153]
Hi guys. I am trying to upload a huge file (4-5gb) via WebApiModule. Unfortunately the ram of my devices climbs over minutes until it crashes. I am using Xamarin on a Android Tablet.

My configuration:

```
 var url = "http://localhost:9696/";
            WebServer server = null;
            try
            {
                server = new WebServer(url, RoutingStrategy.Wildcard);
                
                server.EnableCors();
                
                server.RegisterModule(new WebApiModule());
                server.Module<WebApiModule>().RegisterController<UploadController>();

                await server.RunAsync();

            }
            catch (Exception ex)
            {
                Log.Debug(_logTag, ex.ToString());
                //throw;
            }
            finally
            {
                server?.Dispose();
              
            }
```

My UploadController

```
[WebApiHandler(HttpVerbs.Post, "/api/upload")]
        public async Task<bool> UploadFile(WebServer server, HttpListenerContext context)
        {
            try
            {
                var parser = new MultipartFormDataParser(context.Request.InputStream);

                if (parser.Files.Any() == false)
                    throw new Exception("Invalid request, you need to post a file");

                context.Response.Redirect("/");
                return true;
            }
            catch (Exception ex)
            {
                return context.JsonExceptionResponse(ex);
                // return HandleError(context, ex);
            }
        }
```

In my log console i see constantly popping up "GC_MINOR: (Nursery full)" messages.

Am I doing something wrong or is thsi a possible issue of embedio? Thank you for help in advance.

**Comment by geoperez** [comment]
The issue is when you are receiving a really big file... I don't know if it's something we can handle. 

What .NET framework or .NET core version are you using?

**Comment by RyanYANG52** [comment]
@smedasn I try the same thing, the memory problem is not embedio's problem. You should use `StreamingMultipartFormDataParser ` instead, more info here->
https://github.com/Vodurden/Http-Multipart-Data-Parser#streaming-handles-large-files
https://github.com/Vodurden/Http-Multipart-Data-Parser/blob/master/HttpMultipartParser/StreamingMultipartFormDataParser.cs#L29

**Comment by geoperez** [comment]
That is a great library, I had use it with Embedio before.
