### ISSUE TITLE
StaticFilesModule support file larger than 2G

### ISSUE THREAD

**Issue by RyanYANG52** [unosquare/embedio#157]
Awesome lib, thanks guys.

I'm using the lib to build a LAN http file storage program, user can download and upload any file from webserver using a webpage. So far I can download any file less than 2G from staticFilesModule and upload using webApi #153 

The problem is Int.MaxValue is 2G, so the index will became negative after 2G, so can you please change to `long` in the next release, here ->   https://github.com/unosquare/embedio/blob/989c2be889f664158ef7d3da1dbede5e9186305c/src/Unosquare.Labs.EmbedIO/Modules/StaticFilesModule.cs#L237
and couple other places using the `lowerByteIndex` `upperByteIndex`
It'll be very helpful.

I changed the source code and works for 4G plus file.
thanks again!

**Comment by geoperez** [comment]
Let me create a PR.

**Comment by RyanYANG52** [comment]
Here->   https://github.com/unosquare/embedio/blob/Issue157-LargeFilesStatic/src/Unosquare.Labs.EmbedIO/Modules/StaticFilesModule.cs#L280
Need to change to `long sendData = 0;` also, and all works out , thanks! @geoperez

**Comment by geoperez** [comment]
Done.
