### ISSUE TITLE
Is it production ready?

### ISSUE THREAD

**Issue by ygl-rg** [unosquare/embedio#159]
Hi All

  I found out this lib during searching a pure c# http server on google. After reading some docs, I think it might fit what I need.

  I am curious whether it is production ready.

Regards

gelin yan

**Comment by geoperez** [comment]
We use this library in internal projects and we are pretty sure it's stable.

**Comment by ygl-rg** [comment]
Thanks @geoperez  

 I will give it a try.

Regards

gelin yan

**Comment by bufferUnderrun** [comment]
I want to add some feedback.

I use it in production for 1 year : internal and exposed from net to run restapi. Does the job and does it well !

Thanks for EmbedIO !!
