### ISSUE TITLE
Regex call not working with version 13.1

### ISSUE THREAD

**Issue by abuzaforfagun** [unosquare/embedio#169]
**Describe the bug**
Regex call not working with version 13.1. Wildcard working fine.

**To Reproduce**
Sample api: api_base/{category}/{name}
Sample Request: api_base/category/jhon

It return 500 response status. And api end point not firing.

**Expected behavior**
It should hit the end point and return expected data.

**Comment by geoperez** [comment]
I found the issue, please use the new version 1.13.2 (https://www.nuget.org/packages/Embedio)
