### ISSUE TITLE
Is it possible to support .net 4?

### ISSUE THREAD

**Issue by benny856694** [unosquare/embedio#17]

**Comment by mariodivece** [comment]
Hey Benny, if there is a good reason to do so, then we will. Can you explain why you need .net 4 support? Have you tried downloading the source and compiling for .net 4?

**Comment by benny856694** [comment]
tried, the Json and websocket  is the problem on .net 4

**Comment by geoperez** [comment]
Websocket inbuilt support doesn't exist in NET4 and the json library it's
just downgrade it. Are you planning a system limited to NET4 or why do you
need this requirement?

**Comment by benny856694** [comment]
never mind, drop this requirement.

**Comment by geoperez** [comment]
Aright. Let me know if you need anything else.
