### ISSUE TITLE
I needed a EmbeddedResource Static files module ... so I wrote one

### ISSUE THREAD

**Issue by nickhodge** [unosquare/embedio#170]
Thanks for an excellent piece of code.

[ResourceFilesModule](https://gist.github.com/nickhodge/3a7af97925a7623a45366d3d87280796)

Up until recently we had been using [Nancy](https://github.com/NancyFx/Nancy) and [Nancy Self Hosting](https://github.com/NancyFx/Nancy/tree/master/src/Nancy.Hosting.Self).

I found them too "heavy" so have successfully moved to Embedio.  Thanks guys!

But I needed to serve files from an Assembly. 

So I quickly wrote up this Module. As Assemblies **should** (my assumption) be in RAM, I removed the RAM cache. I have not perf tested this as there would only be one user per Embedio server.

Feel free to take it, make it work better (+ add tests!) -- maybe add Virtual Path support too!

**Comment by geoperez** [comment]
Cool, thank you.

I'm going to create a new branch to include it and design the tests. We may need to add an abstract class because I see some common source code.

**Comment by nickhodge** [comment]
Awesome!

Yes, this code isn't my best work -- I am sure you will make it better

**Comment by geoperez** [comment]
Adding a abstract base class: https://github.com/unosquare/embedio/blob/Issue170-StaticFilesFromResources/src/Unosquare.Labs.EmbedIO/Modules/ResourceFilesModule.cs

**Comment by geoperez** [comment]
New nuget: https://www.nuget.org/packages/Embedio
