### ISSUE TITLE
RoutingStrategy.Regex caused can not handle websocket request.

### ISSUE THREAD

**Issue by a44281071** [unosquare/embedio#172]
I need webapi and websocket handle.
But I found that a new WebServer.RoutingStrategy set to RoutingStrategy.Regex. It will cause a http 404 error.
can not handle websocket request.
How to fix it?

**Comment by geoperez** [comment]
Hello, please provide more information like a sample code and how are you trying to access the URL.

**Comment by geoperez** [comment]
I found the issue, please use the new version 1.13.2 (https://www.nuget.org/packages/Embedio)

**Comment by geoperez** [comment]
Dup #169
