### ISSUE TITLE
Example in how use ManualResetEvent or backgroundWorker?

### ISSUE THREAD

**Issue by mamcx** [unosquare/embedio#176]
I'm looking for a web server to put inside an Android App.

I try to run it with (in F#. I'm ok with sample in C#):

```
type Api() =
  inherit WebApiController()

  [<WebApiHandler(HttpVerbs.Get, "/{id}")>]
  member x.Home(theId) =
        "{}"

let startServer() =
    let server = 
        new WebServer(URL)

    let server = 
            server.
                EnableCors().
                WithWebApi()

    server.Module<WebApiModule>().RegisterController<Api>()

    server.
        RunAsync()
        |> ignore
```

But it not listen and not get logging or error. So I need a way to keep the server alive in the background, but how?

**Comment by geoperez** [comment]
I'm not familiar with asynchronous programming with F# but usually with C# RunAsync will return a task that you can store in a variable and then continue with a blocker instruction like Console.ReadLine and after the user continue execution cancel the stored task.

You may use a similar approach with F#

**Comment by mamcx** [comment]
I put the task into a var in the form and still the server not run. But this is in android, in iOS it work?

I'm ok with examples in C#. The thing is that I can't block with 

`task.Wait();`

**Comment by mamcx** [comment]
I finally found the problem, was a weird bug with the mono compiler ([that I reported in the past](https://stackoverflow.com/questions/50746267/error-image-en-fsharp-core-resources-dll-so-not-found-dlopen-failed-condi)) that not allow to see this.

For the record, is just to store the task into the form and that is. Nothing fancy to do.
