### ISSUE TITLE
Performance issue Json Serialize Deserialize

### ISSUE THREAD

**Issue by detlefm** [unosquare/embedio#177]
I have a project in which I want to transfer a lot of data via web service.
 In one example, I have 12 megabytes of EPG data. 
The transmission takes about 90 seconds due to the serialization by the standard Json Serializer. 
When using NewtonSoft only about 3 seconds.

Comparison programm see attachment - it is a pure Console app.
[FastJsonTest.zip](https://github.com/unosquare/embedio/files/2207485/FastJsonTest.zip)

Of course I can handle the problem by using NewtonSoft, but I think the hint could be useful for the overall performance of the system. I'm not sure where else this Json component is used.

**Comment by geoperez** [comment]
Hi, thank you for the heads up. We built SWAN as a common library for all projects we have.

I'm going to close this issue and open a new one in SWAN Repo (https://github.com/unosquare/swan/issues/137)
