### ISSUE TITLE
server.RunAsync().Wait() doesn't wait

### ISSUE THREAD

**Issue by DayBr3ak** [unosquare/embedio#178]
**Describe the bug**
The task from server.RunAsync() is not waiting when you call task.Wait()

```cs
var server = new WebServer(3131, RoutingStrategy.Regex);
server.RegisterModule(new WebApiModule());
server.Module<WebApiModule>().RegisterController<MainController>();
var t = server.RunAsync();
t.Wait();
```

The program will exit regardless event if Wait() is called.

**Comment by geoperez** [comment]
When you pass only the port number, EmbedIO will try to bind the weak wildcard (*) host you may need admin rights. Try to execute it as Administrator, or change the next line:

`var server = new WebServer("http://localhost:3131", RoutingStrategy.Regex);`

**Comment by DayBr3ak** [comment]
Thanks for your time but unfortunately no, the webapp works with just the port number but I have to artificially stop the thread with a Console.ReadKey(). Same thing with `http://localhost:3131`. Task.Wait() is not blocking the main thread and the processus justs ends.

**Comment by geoperez** [comment]
Hello @DayBr3ak , can you test with this [prerelease version](https://www.nuget.org/packages/EmbedIO/1.15.0-pre)?

**Comment by geoperez** [comment]
status?
