### ISSUE TITLE
RunAsync() not finish in Xamarin.Forms for physical iOS

### ISSUE THREAD

**Issue by abuzaforfagun** [unosquare/embedio#179]
Everything works fine in iPhone simulator. But when running over physical device and hit end point it returns 404. And if use Wait() it will not finish the execution.
Code without Wait()
`var serverData = new WebServer("http://localhost:18941/", RoutingStrategy.Regex).EnableCors();
serverData.RegisterModule(new WebApiModule());
            serverData.Module<WebApiModule>().RegisterController<DataController>();

            serverData.RunAsync();`

Code Sample
`var serverData = new WebServer("http://localhost:18941/", RoutingStrategy.Regex).EnableCors();
serverData.RegisterModule(new WebApiModule());
            serverData.Module<WebApiModule>().RegisterController<DataController>();

            var data = serverData.RunAsync();
            data.Wait();`
I have created and run the server in App class. And everything works fine for iOS simulator.

**Comment by geoperez** [comment]
Hello @abuzaforfagun , can you test with this [prerelease version](https://www.nuget.org/packages/EmbedIO/1.15.0-pre)?

**Comment by geoperez** [comment]
status?
