### ISSUE TITLE
Support for custom URI Schemes 

### ISSUE THREAD

**Issue by pushqrdx** [unosquare/embedio#181]
First i wanna thank you for this awesome library. 

**Describe the solution you'd like**
Is there a possibility that EmbedIO can support handing of custom URI Schemes. I find this handy when using EmbedIO to implement a custom HTML user interface for an application so it handles it's communication on it's own scheme.

**Describe alternatives you've considered**
Using the http scheme but being able to access the WebServer from outside the application ie any Web Browser to be inconvenient which leads me to the a question. Is it possible to limit the WebServer access to application only?

Again, EmbedIO is amazing, the code is pretty neat and the features are awesome and i can definitely see it very useful in a lot of scenarios.

**Comment by geoperez** [comment]
Do you mean register and listen for URI like embedio://localhost or similar?

I think we would have some issues related to cross-platform, what I know that you can add some Windows registry keys but I have no idea how to achieve it with Linux os Mac. Do you have any documentation?

**Comment by pushqrdx** [comment]
yea that's exactly what i meant however if this will break Mono/Cross-Platform compatibility then it's better not be implemented because the good thing about EmbedIO is that it runs everywhere. so i guess the question now is if there's a way so that the server can only be accessed from inside the application, i would really appreciate your help.

**Comment by geoperez** [comment]
It's possible to integrate an in-memory service just for the application running the server, something similar to OWIN TestServer (https://www.strathweb.com/2013/12/owin-memory-integration-testing/). Where the entire HTTP pipeline is mounted over a dispatcher without listening real network traffic.

The issue with this approach is that we need to rewrite EmbedIO to include this abstraction layer to separate WebServer logic from HttpListener as direct dependency.

**Comment by pushqrdx** [comment]
@geoperez If such move won't break mono/xamarin compatibility i would be glad to assist in adding this capability (after i get the hang of it) but i'll need some help ofc.
I can find this pretty useful in cases when you use EmbedIO to create an HTML/CSS/JS user interface for Android/iOS/UWP and virtually all Xamarin targeted frameworks where you have EmbedIO serving the UI layer from embedded resources or local folder. of course this can be achieved now but idk yet if having a web server running will cause issues submitting an application to the app stores hence the benefit of having the in memory option.

**Comment by geoperez** [comment]
The header thing is easy to do, you just need to implement a `WebModule` and register before any other module. The custom module will check the HTTP header and return false to continue the EmbedIO pipeline, otherwise return true and send an HTTP error.

You can even use the `FallbackModule` to achieve this behavior.

And yes, add the abstraction layer between WebServer and the HttpListener is not an easy task.

**Comment by geoperez** [comment]
We already implemented an abstraction layer between WebServer and HttpListener.
