### ISSUE TITLE
Modify Response Headers to enable caching

### ISSUE THREAD

**Issue by felixerdy** [unosquare/embedio#183]
**Describe the bug**
I'd like to modify the response headers to enable caching. Currently, all responses contain `Cache-Control: no-store, no-cache, must-revalidate`. I would like to have `Cache-Control: public` to enable caching.

**To Reproduce**
```c#
[WebApiHandler(HttpVerbs.Get, "/api/symbols/")]
public async Task<bool> GetSymbolsAsync(WebServer server, HttpListenerContext context)
{
    try
    {
        [...]

        context.Response.Headers.Add("Cache-Control: public");
        return context.JsonResponse(myData);
    }
    catch (Exception ex)
    {
        System.Diagnostics.Debug.WriteLine("Exception: " + ex.Message);

        return context.JsonExceptionResponse(ex);
    }
}
```
**Expected behavior**
Browsers response header shows `Cache-Control: public`

**Actual behavior**
Browsers response header shows `Cache-Control: no-store, no-cache, must-revalidate`

**Desktop:**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 68

**Comment by geoperez** [comment]
Yes, the current implementation is always calling [NoCache](https://github.com/unosquare/embedio/blob/709a98ef0bd1306453d7ae4bab492e3b5047b762/src/Unosquare.Labs.EmbedIO/Modules/WebApiModule.cs#L770) before the WebAPI method.

I'm going to change the logic to set the NoCache after the WebAPI method, and only if there is no Cache-Control header yet.

Good catch!

**Comment by geoperez** [comment]
Hi @felixerdy, I was thinking on this approach: https://github.com/unosquare/embedio/pull/184

Basically, you need to add to your controller the following method: 

`public override void SetDefaultHeaders(HttpListenerContext context)`

And A) Add your default headers (like public cache) or B) Set nothing and allow setting cache per Web API Method.

Let me know what you think.

**Comment by felixerdy** [comment]
👍 Yes I think that would be a good way

**Comment by geoperez** [comment]
Please use the new version 1.6.0 (https://www.nuget.org/packages/EmbedIO/1.16.0)

Don't forget star this project 👍

**Comment by felixerdy** [comment]
Works like a charme 🤗 

Thanks for your work!

**Comment by caverna** [comment]
@geoperez may I ask you to include this option also in WebApiController too?

**Comment by geoperez** [comment]
Hello, the method SetDefaultHeaders is for WebApiController, just override it

**Comment by jswigart** [comment]
How do you control Cache-Control for the files module?
