### ISSUE TITLE
Add support to add constructor dependency injection 

### ISSUE THREAD

**Issue by abuzaforfagun** [unosquare/embedio#187]
First of all thank you for your great work.

Currently we need to add controller with no parameterized constractor. Last time I have worked to convert Web API 2 project to EmbedIO. And I found that, it need to initialize each and every dependency manually. And think, you need create an object of a class what need 2-3 complex object that need to be initialized manually too.
On the mean time, Web API 2 resolves those dependency from their end or we use any dependency injection framework to resolve those dependency. 

Can you add any way to use dependency injection framework with embedio?

**Comment by geoperez** [comment]
EmbedIO is using [SWAN](https://github.com/unosquare/swan) and this library has a DI container, you may check it. 

Anyway, I'm working on a refactor to improve our WebAPI module, and probably DI will be helpful now. In the following link, you can see how the Controller methods are simplified and the Controller constructor will inject the HttpContext, so include a DI container there will be probably easy to implement.

https://github.com/unosquare/embedio/blob/9042b2e1dd5566e154547746fabe617a8041f23f/README.md#rest-api-example

**Comment by geoperez** [comment]
Status?

**Comment by StrongAndyZhang** [comment]
I find the function "RegisterController" with a parameter "factory" in WebApiModule,  we can use IOC (such as Autofac) to generate instance for controller so  that controller with constructor dependency injection. I create a repository to demostrate how to do it using Abp vNext. Hope this could give you a reference. [https://github.com/StrongAndyZhang/AbpEmbedIODemo](url)
