### ISSUE TITLE
Request Method Middleware

### ISSUE THREAD

**Issue by davenamic** [unosquare/embedio#189]
Does embedio support this type of middleware already? If so, how? ive searched quite a bit. Thanks.

// # Node.js, express
        app.get '*', (req,res,next) -> return next()

// C#
        [WebApiHandler(HttpVerbs.Get, "*")]
        public bool GET_MIDDLEWARE(WebServer srv, HttpListenerContext ctx)
        { 
        	// Foward to SSL if on Clear Port
        	// Etc...
        	return false; // ?
        }

**Comment by geoperez** [comment]
Hi, instead of middleware I would suggest you to write a web module. You
can check them in the git repo.

**Comment by geoperez** [comment]
May I close this issue?

**Comment by victorjonsson** [comment]
Can a web module act a s middleware? What if I would like to intercept all incoming request or all outgoing responses? Is that possible with a we module or something else? @geoperez
