### ISSUE TITLE
405 (Method Not Allowed)

### ISSUE THREAD

**Issue by SunnyTheBlue** [unosquare/embedio#193]
**Is your feature request related to a problem? Please describe.**
When client sends POST request with Authorization header, the client's method changes to OPTIONS and the server return's the 405 Method Not Allowed. But at the same time, when the client sends the POST request without any headers, server is returning Status 200 OK.

**Describe the solution you'd like**
When client will send POST request with Authorization header token, the server should return Status 200 OK.

**Describe alternatives you've considered**
We have tried to enable CORS on the server-side using: ```Server.EnableCors();```

Also, on the client side, we have tried to enable credentials

**Comment by geoperez** [comment]
What authorization module are you using?

**Comment by SunnyTheBlue** [comment]
We are not using any modules, we are writing authorization header for the post request.

**Comment by geoperez** [comment]
But where are you expecting to receive the POST? Are you using a WebAPI controller?

**Comment by SunnyTheBlue** [comment]
```
    Server.RegisterModule(new WebApiModule());
    Server.Module<WebApiModule>().RegisterController<Test>();

    public class Test : WebApiController
    {
        [WebApiHandler(HttpVerbs.Post, "/api/test")]
```

Yes

**Comment by geoperez** [comment]
I'm running EmbedIO Sample project and using the echo POST method from there I got no problems adding an authorization header:

![image](https://user-images.githubusercontent.com/1775792/45320056-2f6ef700-b507-11e8-85bc-d2bc310f25a0.png)

**Comment by SunnyTheBlue** [comment]
Yes, if you send requests through Rested / Postman, then everything is fine, but if you send a query simply from the index.html or localhost & server file, then that problem, here is an example of sending, also tried through `fetch`

```
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">

  <title>Document</title>
</head>

<body>
  <input type="file" onchange="Get('http://localhost:8080/api/user?uid=0')">

  <script>
    function Get(url) {
      const Request = new XMLHttpRequest();

      Request.open("GET", url, false);
      Request.setRequestHeader("Authorization", "Basic sfddsfsdf");
      Request.send(null);

      return Request.responseText;
    }
  </script>
</body>

</html>
```

**Comment by geoperez** [comment]
Is index.html in the same domain (localhost:8080)?

**Comment by SunnyTheBlue** [comment]
No, API: 8080 & Index: 8181

Our API will stand on another server, and the site on the other.

**Comment by geoperez** [comment]
Ok, let me test with CORS then.

**Comment by geoperez** [comment]
I found the issue, CORS module is not responding correctly.

**Comment by geoperez** [comment]
Cool. Closing issue.

🌟  Please star this project if you find it useful!

**Comment by Joe118** [comment]
@geoperez I just upgraded to 1.61.1 (I know, ancient) and still getting the error below:

First error -- xhr.js?b50d:178 OPTIONS http://localhost:9009/api/v1/local_time 405 (Method Not Allowed)

Second error -- localhost:8080/#/timer:1 Access to XMLHttpRequest at 'http://localhost:9009/api/v1/local_time' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

The request I'm sending, with axios, is:

      axios
        .get('http://localhost:9009/api/v1/local_time',
             {headers: {
               'Access-Control-Allow-Origin':'*'
             }})
        .then(response => {
           context.commit('updateTime', response.data);
        })
        .catch(err => {
           console.error(err);
        });

**Comment by Joe118** [comment]
Confirming that now with 1.16.1 things work for me. Earlier report of troubles was incorrect, an error on my side. I deleted that.
