### ISSUE TITLE
Need Help/Understanding

### ISSUE THREAD

**Issue by bufferUnderrun** [unosquare/embedio#195]
Hi,

I need some help to understanding how Async works in the WebApi.

**1. Async : what's for ?**

In sync mode : the client (usually the browser) make a request and the server send its response. If the task take some time, the server will continue to process as long as the client keep connection. If too long (timeout 30sec by default), the server stop request and return error.

In Async mode : 

- used to run a background task that take time to process. In this case, the server return a response to the client and continue its work. But how tell to client the task is finished or return final result ?

Am i correct ?

**2. How to use async ?**

Suppose i have a task that take time to proccess (ie: generate many pdf, sending mails, doing stuff in db...) and return the result to the client (browser). How to write this, do you have some snippets ?

Thanks for your answer.

**Comment by geoperez** [comment]
Hi @bufferUnderrun, I will suggest checking the following blog post: 
https://msdn.microsoft.com/en-us/magazine/jj991977.aspx

And some notes about EmbedIO design:

* Each incoming connection is handled by a task with `ConfigureAwait(false)`
* You can await any method in an async WebAPI, the initial idea to have async methods was to allow to write to the output stream asynchronously.
* Don't mix the concepts async/await with the browser behavior, they are different domains. The browser will handle an HTTP Request, in the same way, no matter if the backend is using async or not.

Also, I recommend you check any ASP.NET or ASP.NET Core WebApi Async suggestion. The principles are pretty much the same.

**Comment by geoperez** [comment]
Can I close this issue?

**Comment by bufferUnderrun** [comment]
Thanks for the pointer. A little less confuse for me.
