### ISSUE TITLE
C# Webbrowser component/embedio/php

### ISSUE THREAD

**Issue by thipages** [unosquare/embedio#196]
Hi,
We have a web site developped with php.
We would like to get a standalone (C#) application for Windows keeping the php code.

Do you think  we can use a c# application containing (only) a web browser component, calling php scripts with the help of embedio?

Thanks

**Comment by geoperez** [comment]
That is an interesting question... You may need to create a `WebModule` or use the `FallbackModule` to redirect the HTTP Request to the PHP executable. That is easy and possible, but what I don't have an idea is how to pass the content of the PHP global vars like QueryString...

Something similar to this: https://stackoverflow.com/questions/942976/how-to-pass-get-and-post-data-to-the-php-executable

**Comment by thipages** [comment]
Ok, I will try, keep you informed

**Comment by geoperez** [comment]
Try to use the `FallbackModule` first and probably you can run PHP exe with [SWAN ProcessRunner](https://github.com/unosquare/swan#the-processrunner-class). SWAN is an EmbedIO's dependency.

**Comment by geoperez** [comment]
Any feedback?
