### ISSUE TITLE
Please provide a version of RegisterWebSocketsServer which allows me to pass in an instance

### ISSUE THREAD

**Issue by PhilipDaniels** [unosquare/embedio#2]
The current implementation forces users to create a server with a parameterless constructor:

    public void RegisterWebSocketsServer<T>(string path)
            where T : WebSocketsServer, new()
    {
        this.ServerMap[path] = Activator.CreateInstance<T>();
    }

Just let me pass in a server I have created.

**Comment by mariodivece** [comment]
Closing. See commit b7789c2e5e70f50358bb0935bac4619892a888ad

**Comment by PhilipDaniels** [comment]
Thanks for the quick response. Can we get an updated NuGet package?

**Comment by mariodivece** [comment]
I've updated the nuget package. We have also removed the dependency on log4net.
