### ISSUE TITLE
Searching a way to communicate from restapi to websocket [help]

### ISSUE THREAD

**Issue by bufferUnderrun** [unosquare/embedio#204]
Hi,

My web app is using 2 differents modules to allow user to do their work: 
- a RestApi (webapi module) : for all actions
- a WebsocketServer (websocket module) : to get the number of running tasks (1min timer Broadcast).

When a user does some action via restapi, i would like to broadcast informations to all others users with the websocket connection.
So, is there a way to using the WebSocketsServer.Broadcast() from a RestApi Controller ?

Thanks for help or suggestion.

**Comment by geoperez** [comment]
We usually add a singleton provider with methods and events. For example:

```
// The WebSocket server add this event handler this in the constructor
FingerprintReaderProvider.Instance.EnrollNotification += (s, e) => Broadcast(Json.Serialize(e));

/// then the WebAPI may call to the Provider method to start an enrollment
FingerprintReaderProvider.Instance.RequestEnrollment();

// and finally the RequestEnrollment calls the event

void RequestEnrollment() {
  EnrollNotification ?.Invoke(event);
}
````
So the provider will keep track of exchange states between WebSocker and WebAPI.

**Comment by bufferUnderrun** [comment]
that's simple, sometime i feel stupid. Need to breath fresh air.

Can close the issue.
Thanks

**Comment by geoperez** [comment]
Heheh, don't worry!
