### ISSUE TITLE
Xamarin.Forms Webview: ERR_CONNECTION_REFUSED trying to load local server 

### ISSUE THREAD

**Issue by sonic1015** [unosquare/embedio#207]
**Describe the bug**
Android Webview can't connect to local host

**To Reproduce**
1. Create a Xamarin Forms App
2. On first-time startup, Load Html files into local folder
3. Create and Start a local Server Using LocalSessionModule and StaticFilesModule
4. Create Webview with the local url as the source

**Expected behavior**
Web Page displays. This works on iOS and UWP.

**Actual behavior**
Chrome Error page displays: ERR_CONNECTION_REFUSED

**Code used to create Local WebServer:**
```
    public class LocalWebServer: IDisposable
    {
        public static string Url = "http://localhost:8787/";

        private readonly string _filePath;
        private WebServer _server;

        public LocalWebServer(string filePath)
        {
            _filePath = filePath;
        }

        public void StartWebServer()
        {
            _server = new WebServer(Url);
            
            _server.RegisterModule(new LocalSessionModule());
            _server.RegisterModule(new StaticFilesModule(_filePath));
            _server.Module<StaticFilesModule>().UseRamCache = true;
            _server.Module<StaticFilesModule>().DefaultExtension = ".html";
            _server.Module<StaticFilesModule>().DefaultDocument = "index.html";
            _server.Module<StaticFilesModule>().UseGzip = false;

            

            Task.Factory.StartNew(async ()=>
            {
                Debug.WriteLine("Starting Server");
                await _server.RunAsync();
            });
        }

        public void Dispose()
        {
            _server?.Dispose();
        }
    }
```

**Code used to create Webview:**
```
    public App()
    {
        InitializeComponent();

        //Create and display a Webview
        _webView = new WebView();
        MainPage = new ContentPage()
        {
            Content = _webView,
        };
    }

    protected override async void OnStart()
    {
        //Service which can initialize app for first time use, and stores
        //the folder location for the html page on each platform
        var htmlService = DependencyService.Get<IHandleHtmlContentService>();

        //Local webserver
        var localWebServer = new LocalWebServer(htmlService.DirectoryPath);

        //This is just a function that loads the html content from the
        //bundle resource or assets into a folder. Will only really
        //matter during the first time the App boots up.
        await htmlService.InitializeHtmlContent();

        //Start the Webserver
        localWebServer.StartWebServer();

        //Navigate to the webserver
        _webView.Source = LocalWebServer.Url;
    }
```

**Smartphone (please complete the following information):**
 - OS: Attempted on Android 7 and 8
 - Devices: Samsung Galaxy Tab and S8

**Additional context**
- This is running on a device, not an emulator
- Everything is contained locally within the App, both the server and the webview
- Using the address 10.0.2.2 does not work
- I understand this may not/probably isn't a bug, but a result of my lack of understanding as to how this works. Never-the-less, I could use some help.

**Comment by geoperez** [comment]
Hello, did you check the issue #192? I'm expecting a sample project to include because a user was able to run it with Android.

**Comment by sonic1015** [comment]
I did, that's what helped me get as far as I did. He's also running the webpage out of Android_Assets, which isn't an option for me, I have to run it out of local storage (Not resource... although I did try to run it from Assets and it didn't work).

Would it help if I created a sample, even if it doesn't work on Android?

**Comment by geoperez** [comment]
Yes please, it will help for understand the issue with Xamarin.

**Comment by sonic1015** [comment]
[bugRepo-3.zip](https://github.com/unosquare/embedio/files/2515831/bugRepo-3.zip)

Link to project: https://github.com/sonic1015/bugRepo/archive/3.zip

**Comment by sonic1015** [comment]
Managed to solve it: Apparently, Android has no concept of a "localhost", and you have to get the IP address (which is different between devices and emulators). So I used this code to get the IP Address:

```
public class LocalWebServer: IDisposable
{
    public readonly string Url;

    ...

    public LocalWebServer(string filePath)
    {
        _filePath = filePath;

        Url = "http://" + GetLocalIpAddress() + ":8787/";
    }

    ...

    private static string GetLocalIpAddress()
    {
        var listener = new TcpListener(IPAddress.Loopback, 0);
        try
        {
            listener.Start();
            return ((IPEndPoint)listener.LocalEndpoint).Address.ToString();
        }
        finally
        {
            listener.Stop();
        }
    }
}
```

And now Android Webview can find the local value.

**Comment by geoperez** [comment]
Cool, I will include it with your sample and add it to the repo.

**Comment by logikonline** [comment]
This actually works but still fails when trying to post a file to the localhost server.  Does anyone have a solution for this?  It is the only aspect left that doesn't work on Android only.
