### ISSUE TITLE
Support for SSL

### ISSUE THREAD

**Issue by geoperez** [unosquare/embedio#217]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Genteure** [comment]
Also client certificate support would be a (maybe not used too much but) cool feature to have.

https://docs.microsoft.com/en-us/dotnet/api/system.net.security.sslstream.remotecertificate
https://docs.microsoft.com/en-us/dotnet/api/system.net.httpwebrequest.clientcertificates
https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_verify_client
https://blog.cloudflare.com/introducing-tls-client-auth/
