### ISSUE TITLE
Failing AuthModule.cs line 49

### ISSUE THREAD

**Issue by kujablik** [unosquare/embedio#218]
**Describe the bug**
System.ArgumentException when I try to add Auth Header (AuthModule.cs Line 49)

**Expected behavior**
I replaced the line 49
context.Response.Headers.Add("WWW-Authenticate", "Basic realm=\"Realm\"");
by this code
context.Response.AddHeader("WWW-Authenticate", "Basic realm=\"Realm\"");
That's OK)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Opera
 - Version 56.0.3051.107

**Comment by geoperez** [comment]
What framework target are you using?

**Comment by kujablik** [comment]
> What framework target are you using?

I tried NET47, 471, 472

**Comment by geoperez** [comment]
Fixed! You can check the new nuget v2.1.1

Let me know if I can close this issue.

**Comment by kujablik** [comment]
Thx! I've just tested. Close this issue.
