### ISSUE TITLE
Add an example of how serve files from API

### ISSUE THREAD

**Issue by nddipiazza** [unosquare/embedio#219]
There is no example of how to use the embedded server API to send bytes (possibly a file, or something that is originating from an output stream).

Someone similarly was trying to figure this out here: https://github.com/unosquare/embedio/issues/107

Can we provide an example in the readme that shows how to do this?

Something like...

```
    [WebApiHandler(HttpVerbs.Get, "/api/{fileId}")]
    public bool GetFile(string fileId) {
      var myFile = GetMyFile(fileId);
      var inputStream = myFile.InputStream;
      return this.Response.OutputStream.Write(myFile); // ???? How do I write the input stream to the response output stream???
    }
```
It's got to be a common use of this library, so someone's probably already got the example. Perhaps the Static file handler does this exact thing and the code can just be somehow copy pasted? 

Maybe a stripped down version of this? https://github.com/unosquare/embedio/issues/97

**Comment by geoperez** [comment]
I'll add it to https://github.com/unosquare/embedio/wiki/Cookbook

**Comment by nddipiazza** [comment]
@geoperez here is an example project that uses it (that i created)
https://github.com/nddipiazza/SambaFetcher

if there are any issues with my usage, let me know,

**Comment by geoperez** [comment]
I'm adding some extension methods for `IHTTPContext`: https://github.com/unosquare/embedio/commit/4502addea9eb2d27f30292b75011ec08375f9f0f#diff-278c2d69bf0c1601ce3d9801fd9ce798R456

What do you think?

**Comment by geoperez** [comment]
Sample doc:

**Comment by nddipiazza** [comment]
Great!
