### ISSUE TITLE
StaticFilesModule - Check for byte range requests before reading the entire file

### ISSUE THREAD

**Issue by mariodivece** [unosquare/embedio#22]
Line 251, by the time the check for byte range requests is performed, the entire file has already been read which could potentially be a very large file. Byte range requests should not use RAM caches either. Additionally, the response must contain a 206 Partial content header.

Make sure you use a FileStream with shared read access so the file is not locked when it is being read.

**Comment by geoperez** [comment]
Mario, please check new Nuget v1.0.12 https://www.nuget.org/packages/EmbedIO/

**Comment by mariodivece** [comment]
Ok, looks good now. Closing.
