### ISSUE TITLE
please document how to get POST parameters from Unosquare.Labs.EmbedIO.IHttpContext

### ISSUE THREAD

**Issue by nddipiazza** [unosquare/embedio#223]
is there any way to get the POST parameters from `Unosquare.Labs.EmbedIO.IHttpContext`? 

if so, can you add it to the documentation?

**Comment by geoperez** [comment]
I like your idea to include a better explanation of how to use Request/Response in several scenarios. I just need to finish the support for SSL and I'm going to continue with this task.
