### ISSUE TITLE
Missing functionality on IHttpContext, IHttpRequest and IHttpResponse for ASP.NET Core

### ISSUE THREAD

**Issue by jpalcala** [unosquare/embedio#225]
**Is your feature request related to a problem? Please describe.**
In order to implement EmbedIO on ASP.NET Core as a custom server some things are missing and need to be implemented.

**Describe the solution you'd like**
Adding those properties into the specified interfaces would allow the integration with ASP.NET Core to be completed.

The missing functionality with their corresponding interfaces are listed below:

- `IHttpContext`
```csharp
        //
        // Summary:
        //     Gets an object used to obtain identity, authentication information, and security
        //     roles for the client whose request is represented by this System.Net.HttpListenerContext
        //     object.
        //
        // Returns:
        //     An System.Security.Principal.IPrincipal object that describes the client, or
        //     null if the System.Net.HttpListener that supplied this System.Net.HttpListenerContext
        //     does not require authentication.
        public IPrincipal User { get; }
```
see : [IPrincipal](https://docs.microsoft.com/en-us/dotnet/api/system.security.principal.iprincipal?view=netcore-2.2)

- `IHttpRequest`
```csharp
        //
        // Summary:
        //     Gets the request identifier of the incoming HTTP request.
        //
        // Returns:
        //     A System.Guid object that contains the identifier of the HTTP request.
        public Guid RequestTraceIdentifier { get; }
```
see: [RequestTraceIdentifier](https://docs.microsoft.com/es-es/dotnet/api/system.net.httplistenerrequest.requesttraceidentifier?view=netcore-2.2)
- `IHttpResponse`
```csharp
        //
        // Summary:
        //     Gets or sets a text description of the HTTP status code returned to the client.
        //
        // Returns:
        //     The text description of the HTTP status code returned to the client. The default
        //     is the RFC 2616 description for the System.Net.HttpListenerResponse.StatusCode
        //     property value, or an empty string ("") if an RFC 2616 description does not exist.
        //
        // Exceptions:
        //   T:System.ArgumentNullException:
        //     The value specified for a set operation is null.
        //
        //   T:System.ArgumentException:
        //     The value specified for a set operation contains non-printable characters.
        public string StatusDescription { get; set; }
```
see: [StatusDescription](https://docs.microsoft.com/es-es/dotnet/api/system.net.httplistenerresponse.statusdescription?view=netcore-2.2)
**Describe alternatives you've considered**
It appears that there's no workaround since EmbedIO dropped the use of `HttpContext` and started using its own interfaces thats why previous versions could accomplish this integration (see [AspNet Core Embedio](https://github.com/jbatonnet/Microsoft.AspNetCore.Server.EmbedIO) )

**Additional context**
My request is in favor of adding EmbedIO as a custom server using a simple `WebHostBuilder` extension.

**Comment by geoperez** [comment]
You can find the new properties at the master branch.
