### ISSUE TITLE
Post, and getvalue

### ISSUE THREAD

**Issue by MajidSafari** [unosquare/embedio#229]
can use " WorkBook([FromPost("datevalue")] int dateValue "

for post ????

` public class WorkBookStudentController : WebApiController
    {
        public WorkBookStudentController(IHttpContext context): base(context)
        {
        }

        [WebApiHandler(HttpVerbs.Post, "/WorkBookPdfStudent")]
        public bool WorkBook([FromPost("datevalue")] int dateValue, [FromPost("counter")] int counter, [FromPost("action")] string action, [FromHeaders("key")] string key)
        {`

**Comment by geoperez** [comment]
EmbedIO WebAPI is similar to ASP.NET Core WebAPI but is not the same. The attributes like `FromPost` are not available.

You can pass only route params in the method signature, if you need body params (from POST) you need to use the extension method `ParseJson` of `IHttpContext`. And you can access the headers directly from `IHttpContext.Request`.
