### ISSUE TITLE
Add friendly SPA routes support

### ISSUE THREAD

**Issue by kadosh** [unosquare/embedio#230]
When dealing with SPA inside embedio, it is required a way to redirect all Frontend routes to the entry point of the app. Although Current Fallback module is redirecting routes properly, it is just doing an HTTP Redirect without actually preserving original URL

**For instance**
Given:
- SPA at /
- Some module at /module1

If you try to access /module1 (direct URL), embedio should let SPA deal with that route internally

**Comment by geoperez** [comment]
You can check this version:

https://www.nuget.org/packages/EmbedIO/2.2.0-pre3

And use the Fallback module constructor with a FileInfo argument.

**Comment by geoperez** [comment]
EmbedIO 2.2.0 was released yesterday. Let me know if I can close this issue.

**Comment by kadosh** [comment]
Awesome, works like a charm. Thanks
