### ISSUE TITLE
Blank screen running the EmbedIO.Forms.Sample.iOS project

### ISSUE THREAD

**Issue by Brun0oO** [unosquare/embedio#232]
**Describe the bug**
Launch the EmbedIO.Forms.Sample.iOS example and getting a blank screen.

**To Reproduce**
1. Download the latest release from Github repo
2. Open the solution file _EmbedIO.Forms.Sample.sln_ with Visual Studio Community
3. Copy the _html_ folder inside the (iOS) _Resources_ folder
4. Select and build  _EmbedIO.Forms.Sample.iOS_ project 
5. Run the project using the iOS simulator

**Expected behavior**
I expect to see the content of index.html "Hello, World!" like for the android example....

**Screenshots**
No... I think my description is clear enough, isn't it ?o)

**Desktop (please complete the following information):**
 - OS: Mac OS High Sierra 10.13.6 (17G4015)
 - XCode: 10.1 (10B61)
 - iOS Simulator: 10.1 (SimulatorApp-877 CoreSimulator-581.2)
 - Visual Studio Community: 8.0 Preview (8.0 build 869)

**Smartphone (please complete the following information):**
 - Device: iPhone6S plus, iOS Simulator (iPhone6S plus)
 - OS: iOS 12.1

**Additional context**
I tried unsuccessfully different **NSAppTransportSecurity** settings in _info.plist_ :
```xml
 <key>NSAppTransportSecurity</key>  
 <dict>  
      <key>NSAllowsArbitraryLoads</key><true/>  
 </dict>
```

```xml
<key>NSAppTransportSecurity</key>
<dict>
    <key> NSAllowsArbitraryLoadsInWebContent</key>
    <true/>
</dict>
```

```xml
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSExceptionDomains</key>
    <dict>
        <key>localhost</key>
        <dict>
            <key>NSExceptionMinimumTLSVersion</key>
            <string>TLSv1.0</string>
            <key>NSExceptionRequiresForwardSecrecy</key>
            <false/>
            <key>NSExceptionAllowsInsecureHTTPLoads</key>
            <true/>
            <key>NSIncludesSubdomains</key>
            <true/>
        </dict>
    </dict>
</dict>
```

**Comment by geoperez** [comment]
Sorry, but I don't have a Mac for testing. Let me know if you find a solution.

Thank you!

**Comment by martinlingstuyl** [comment]
Hi @Brun0oO ,

Regarding the info.plist setting, you need the following to exclude localhost from AppTransportSecurity:

```
        <key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsLocalNetworking</key>
		<true/>
	</dict>
```
