### ISSUE TITLE
Critical issue in WebApi after upgrading to v2.2.1

### ISSUE THREAD

**Issue by bufferUnderrun** [unosquare/embedio#237]
**Describe the bug**
After upgrading to v2.2.1 (v2.2.2 is also buggy), each request to the WebApi module throw an exception but the result is correctly return to browser.

**Last working version : 2.2.0**

**To Reproduce**
A simple snippet

```C#
using System;
using System.Threading;
using System.Threading.Tasks;
using Unosquare.Labs.EmbedIO;
using Unosquare.Labs.EmbedIO.Constants;
using Unosquare.Labs.EmbedIO.Modules;

namespace ConsoleApp1 {
    class Program {
        static void Main(string[] args) {

            var server = new WebServer("http://localhost:2393/", RoutingStrategy.Regex);

            server.RegisterModule(new WebApiModule());
            server.Module<WebApiModule>().RegisterController<TestController>();

            var cts = new CancellationTokenSource();
            var task = server.RunAsync(cts.Token);

            Console.ReadKey(true);
        }
    } // end class
    
    public class TestController : WebApiController {
        public TestController(IHttpContext context)
        : base(context) {
        }

        [WebApiHandler(HttpVerbs.Get, "/api/home/test")]
        public Task<bool> Test() {
            try {
                return this.JsonResponseAsync(new { test = "test" });
            }
            catch (Exception ex) {
                // an exception is thrown
                return this.JsonExceptionResponseAsync(ex);
            }
        }

    } // end class 

}
```
An exception will be thrown by `this.JsonResponseAsync` but a response will also be return to browser

**Screenshots**

https://pasteboard.co/HXVZh8y.png

Thanks

**Comment by geoperez** [comment]
What target framework did you use?

**Comment by geoperez** [comment]
Please try to use new nuget version 2.2.3

**Comment by bufferUnderrun** [comment]
i'm waiting for the nuget indexing...

**Comment by bufferUnderrun** [comment]
Your fix is working and you can close the issue.
Thanks !!

**Comment by bufferUnderrun** [comment]
Your fix lead to another critical issue... Please can you reopen the issue.

I have to downgrade to v2.2.0 and deploy in prod. I will explain in few minute.
From now, embedio does not return all data in some pages...

**Comment by geoperez** [comment]
Can you elaborate the issue?

**Comment by bufferUnderrun** [comment]
data is serialized by `newtonsoft.jsonnet` then this string is passed to` jsonsresponsasync()` (via context.extension) which call `stringresponseasync()` (context.extension).

i can't reproduce the issue in each request... so difficult to send you details. And wireshark listen to loopback is a nightware. Trying other thing... The issue seems to appear when thera are a certains amont of data (min 200Ko).

**Comment by geoperez** [comment]
We added a Gzip capability to the string response, maybe that's why. Try to check the last optional parameter and set false.

**Comment by geoperez** [comment]
Did you check the flag?

**Comment by geoperez** [comment]
I release a new version 2.2.4. I tried to reproduce the issue but it did not fail.

**Comment by geoperez** [comment]
Related to #239

**Comment by bufferUnderrun** [comment]
@geoperez yep, same as #239. So you can close this issue and we will continue to 239.
