### ISSUE TITLE
Implement RequestBodyAsync

### ISSUE THREAD

**Issue by emazv72** [unosquare/embedio#238]
Need a  non blocking way to read the body of the request from a WebApiHandler, because calling this.RequestBody() is blocking.

As a workaround I've implemented a simple extension method:

```
public static async Task<string> RequestBodyAsync(this IHttpContext context)
		{
			using (StreamReader reader = new StreamReader(context.Request.InputStream))
			{
				return await reader.ReadToEndAsync();
			}

		}
```

The method can be called like this:

`string body = await this.RequestBodyAsync();`

Would be nice to add the method to the APIs.

Thanks
Ema

**Comment by geoperez** [comment]
I like it, I will integrate with the next release. Thank you!
