### ISSUE TITLE
Non en_US locale can cause ArgumentException on any request.

### ISSUE THREAD

**Issue by shkim** [unosquare/embedio#24]
I got ArgumentException with any http request, the stack trace is:

2015-11-27 16:08:16.704	System.ArgumentException: 지정한 값에 잘못된 제어 문자가 있습니다.
매개 변수 이름: value
   위치: System.Net.WebHeaderCollection.CheckBadChars(String name, Boolean isHeaderValue)
   위치: System.Net.WebHeaderCollection.SetInternal(String name, String value)
   위치: Unosquare.Labs.EmbedIO.Extensions.NoCache(HttpListenerContext context)
   위치: Unosquare.Labs.EmbedIO.Modules.WebApiModule.<.ctor>b__2_0(WebServer server, HttpListenerContext context)
   위치: Unosquare.Labs.EmbedIO.WebServer.ProcessRequest(HttpListenerContext context)

The cause is

        context.Response.AddHeader(Constants.HeaderLastModified,
                DateTime.UtcNow.ToString(Constants.BrowserTimeFormat));

in Extensions.NoCache() method.

With Korean locale,  ToString("ddd, dd MMM yyyy HH:mm:ss 'GMT'") generates non-ASCII characters.
The token "ddd" is the problem.

Workaround: change the locale on program startup, like

var culture = CultureInfo.CreateSpecificCulture("en-US");
CultureInfo.DefaultThreadCurrentCulture = culture;
CultureInfo.DefaultThreadCurrentUICulture = culture;

I wish this problem is fixed for non-english users in the world~ :)

**Comment by geoperez** [comment]
Hi Kim,

Let me take a look and probably setup the HttpListener thread with en-US
culture to avoid force it from outside.

Thank you

On Fri, Nov 27, 2015 at 1:21 AM, Sunghun Kim <notifications@github.com>
wrote:

> I got ArgumentException with any http request, the stack trace is:
>
> 2015-11-27 16:08:16.704 System.ArgumentException: 지정한 값에 잘못된 제어 문자가 있습니다.
> 매개 변수 이름: value
> 위치: System.Net.WebHeaderCollection.CheckBadChars(String name, Boolean
> isHeaderValue)
> 위치: System.Net.WebHeaderCollection.SetInternal(String name, String value)
> 위치: Unosquare.Labs.EmbedIO.Extensions.NoCache(HttpListenerContext context)
> 위치: Unosquare.Labs.EmbedIO.Modules.WebApiModule.<.ctor>b__2_0(WebServer
> server, HttpListenerContext context)
> 위치: Unosquare.Labs.EmbedIO.WebServer.ProcessRequest(HttpListenerContext
> context)
>
> The cause is
>
>     context.Response.AddHeader(Constants.HeaderLastModified,
>             DateTime.UtcNow.ToString(Constants.BrowserTimeFormat));
>
> in Extensions.NoCache() method.
>
> With Korean locale, ToString("ddd, dd MMM yyyy HH:mm:ss 'GMT'") generates
> non-ASCII characters.
> The token "ddd" is the problem.
>
> Workaround: change the locale on program startup, like
>
> var culture = CultureInfo.CreateSpecificCulture("en-US");
> CultureInfo.DefaultThreadCurrentCulture = culture;
> CultureInfo.DefaultThreadCurrentUICulture = culture;
>
> I wish this problem is fixed for non-english users in the world~ :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/unosquare/embedio/issues/24>.
>



-- 
Geo Pérez

**Comment by geoperez** [comment]
@shkim quick question, what .NET version are you using?

**Comment by shkim** [comment]
Windows 8.1 / Visual Studio 2013 / .NET Framework 4.5.1

**Comment by mariodivece** [comment]
My suggestion is to generate the Browser Time Format manually as opposed to using a format string. The days of the week and the names of every month will need to be specified by a hard-coded dictionary using DateTime.DayOfWeek and DateTime.Month respectively as keys to what the browser expects.

**Comment by mariodivece** [comment]
I have updated the code to use en-US culture when generating these headers. Hope this fixes the issue.

**Comment by mariodivece** [comment]
@geoperez maybe add a unit test that creates a web server under a thread with a different culture and check if it generates the browser time format the right way.

Closing issue as not further comment were provided by @shkim
