### ISSUE TITLE
EmbedIO in StaticFileModule in Android

### ISSUE THREAD

**Issue by erossini** [unosquare/embedio#243]
I'm implementing a backend for testers with `EmbedIO` ([Github](https://github.com/unosquare/embedio "Github") here). It is working beautifully with `iOS`. But in `Android` I can't find a solution. 

In `iOS` I create this dependency from the Xamarin project:

    public class WebServer : Interfaces.IWebServer
    {
        public IWebModule CreateWebModule()
        {
            return new Unosquare.Labs.EmbedIO.Modules.StaticFilesModule(NSBundle.MainBundle.ResourcePath);
        }
    }

In this function in `iOS` I can use `NSBundle.MainBundle.ResourcePath` but I can't find an equivalent for `Android`. Any ideas? Thank you in advance.

**Comment by geoperez** [comment]
I'm not familiar with mobile development, but maybe you can try the [ResourceFilesModule](https://unosquare.github.io/embedio/api/Unosquare.Labs.EmbedIO.Modules.ResourceFilesModule.html#constructors). This module is similar to StaticFilesModule but using resources from an assembly.

**Comment by erossini** [comment]
It seems it doesn’t work. I have a similar issue with UWP: I can have a instance of the webserver but I can’t reach the page or I receive a blank screen.

I pass the Assembly and the path of assets folder.

**Comment by geoperez** [comment]
The 'resourcePath' argument is the full path to the resource including the namespace.
For example, if your assembly contains a `Program` class, a `Resources` folder and the default namespace is `MyCompany.MyApp`:

```csharp
var moduleInstance = new ResourceFilesModule(typeof(Program).Assembly, "MyCompany.MyApp.Resources");
```

**Comment by erossini** [comment]
Maybe you need some background. I'm creating a backend for `Xamarin` and I have projects for `iOS`, `Android`, `UWP` and `macOS`.

In `UWP` I have some files in a folder called `Webserver` under the `Assets` folder. I want to show this files. I wrote this code:

        public IWebModule CreateWebModule()
        {
            StorageFolder appInstalledFolder = Windows.ApplicationModel.Package.Current.InstalledLocation;
            string pth = Path.Combine(appInstalledFolder.Path, "Assets\\Webserver");
            return new Unosquare.Labs.EmbedIO.Modules.StaticFilesModule(pth);
      }

I start the `WebServer` like that:

            var webServer = new WebServer(urlPrefixes);
            webServer.RegisterModule(new WebApiModule());
            webServer.Module<WebApiModule>().RegisterController<TestController>();
            webServer.RegisterModule(fileModule);
            await webServer.RunAsync();

This is working with `iOS`.
