### ISSUE TITLE
Example for Serving Files from Assembly

### ISSUE THREAD

**Issue by hawkerm** [unosquare/embedio#246]
**Is your feature request related to a problem? Please describe.**
There's some great sample snippets, but it's hard to see where the rest of the samples are or if they're missing from the cookbook (there also doesn't seem to be a link from the homepage to the github).

**Describe the solution you'd like**
It'd be great to have a samples repo or more called out examples/snippets all centralized and organized in like the cookbook or something.

For instance, I don't see a ResourceFilesModule example (at least easily discovered)?

Thanks!

**Comment by geoperez** [comment]
Yeah, we need to work on documentation. Thanks for the heads up!
