### ISSUE TITLE
how use fixed content into certain folder?

### ISSUE THREAD

**Issue by ghiboz** [unosquare/embedio#248]
**Describe the bug**

Hi! In my `WebApiController` class I have a function like this:
```csharp
[WebApiHandler(HttpVerbs.Get, "/api/times/*")]
public async Task<bool> GetTimes()
```
into this function I read from a db some rows, I parse an html page to add the 'dynamic' content, like a php page do.. and works...

the issue is: the css, js, image files that the html page reference as relative path like `<link rel="stylesheet" href=css/style.css">` are not working...

how can I manage this? thanks in advance!

**Desktop:**
 - OS: Win 10
 - Browser chrome
 - Version 2.2.9

**Comment by geoperez** [comment]
Hello, if the path is relative you can try use a FallbackModule to redirect to the correct base path.

**Comment by ghiboz** [comment]
hello @geoperez , thanks for your fast reply:
I tried with this:

```csharp
// setup http
http = new WebServer(80, RoutingStrategy.Regex);
http.RegisterModule(new FallbackModule("C:/Users/ghiboz/Desktop/Chat/ChatServer/bin/Debug/SITE"));
http.RegisterModule(new WebApiModule());
http.Module<WebApiModule>().RegisterController((ctx) => new HttpController(ctx, db));
cts = new CancellationTokenSource();
task = http.RunAsync(cts.Token);
Console.WriteLine("http server read on port {0}", 80);
```

but doesn't work: if I put the fallback module before my `WebApiModule` I get `ERR_INVALID_REDIRECT`, if I put the module after, the page is displayed without css etc....

**Comment by geoperez** [comment]
You need to use StaticFilesModule for the CSS/JS files...

**Comment by ghiboz** [comment]
same thing: with this piece:
```csharp
http = new WebServer(80, RoutingStrategy.Regex);
http.RegisterModule(new WebApiModule());
http.RegisterModule(new StaticFilesModule("C:/Users/ghiboz/Desktop/Chat/ChatServer/bin/Debug/SITE"));
```
also before or after, no static content and the console get this:
![](https://i.imgur.com/fv4kWSg.png)

**Comment by geoperez** [comment]
Yeah, but if you check the path `/js/index.js` should response properly. I would suggest using absolute paths in your HTML or use a fallback module to redirect all the 404 from /api/* to / (root).

**Comment by ghiboz** [comment]
I tried to add the files in `PATH\api` and I get this error:
![](https://i.imgur.com/zq22f3l.png)
'character not valid in the path'
but is valid and works..

**Comment by ghiboz** [comment]
> Yeah, but if you check the path `/js/index.js` should response properly. I would suggest using absolute paths in your HTML or use a fallback module to redirect all the 404 from /api/* to / (root).

how can I set the fallback module to redirect from api/* to root?
thanks

**Comment by geoperez** [comment]
Something like this:

```

                server.RegisterModule(new FallbackModule((ctx, ct) =>
                    {
                        if (ctx.Request.Url.Segments.Skip(1).FirstOrDefault() == "api/")
                        {
                            return ctx.Redirect("/" + string.Join("/", ctx.Request.Url.Segments.Skip(2)), true);
                        }

                        return false;
                    }));
```

**Comment by ghiboz** [comment]
thanks! now begins to work!!

**Comment by geoperez** [comment]
Can I close this issue?

**Comment by ghiboz** [comment]
oops! sorry!
