### ISSUE TITLE
SSL Certificate `AutoDelete` Feature

### ISSUE THREAD

**Issue by kfreezen** [unosquare/embedio#249]
**Is your feature request related to a problem? Please describe.**
I have a program, which due to the way it's designed, needs to register a new SSL certificate every time it runs. Unfortunately, there's no way to auto-delete old SSL certificates at a certain port number.

**Describe the solution you'd like**
I'd like an `AutoDelete` property in WebServerOptions that deletes the SSL binding via `netsh` before rebinding a new certificate.

**Describe alternatives you've considered**
I can probably reimplement the netsh interfacing code, and run it before I instantiate WebServerOptions()

**Comment by geoperez** [comment]
I like the idea!
