### ISSUE TITLE
Strong Name the nuget assembly

### ISSUE THREAD

**Issue by sameera** [unosquare/embedio#25]
Can the nuget package be updated to contain a strong named assembly, please? My main code needs to be strong named and therefore this is a blocker for me to use the embedio lib.

**Comment by mariodivece** [comment]
It's coming; @geoperez  will release the new signed NuGet package in a bit.

**Comment by geoperez** [comment]
Nuget version [1.0.14](https://www.nuget.org/packages/EmbedIO/ ) is ready

**Comment by sameera** [comment]
Excellent! Thanks for the quick turn around :+1:
