### ISSUE TITLE
StaticFilesModule cache management

### ISSUE THREAD

**Issue by bufferUnderrun** [unosquare/embedio#259]
I'm using the StaticFilesModules with `server.Module<StaticFilesModule>().UseRamCache = true;` to serve static content (html, css, js) for a single page application which call a RestApi.

I encounter 2 issues : 

1. when i update a file (ie: index.html) while server is running and the browser refresh full app, the cache is used and i'm not getting the updated file.
2. same issue if i stop the server, update the index.html and start server. The browser will often use cache and not getting the last index.html update.

So, i wonder if the problem is related to embedio or browser ?

One fix could be to serve static file with cache but with custom exception (ie: no cache for index.html). It's my only issue because all files under the index.html are bundle and versioned.

Thanks

**Comment by geoperez** [comment]
The cache should invalidate if the checksum of the file is different. Let me take a look at what is going on.

**Comment by geoperez** [comment]
I created a new branch for this issue: Issue259-CacheInvalidation

**Comment by geoperez** [comment]
I'm not able to reproduce this issue. 

I set the Static File module with cache on, and the first request responds status 200, and the cache was set. The following calls respond with 304, after editing the file, the modification timestamp changed and the cache was invalidated and it responds 200.
