### ISSUE TITLE
HTTPS/WSS support

### ISSUE THREAD

**Issue by sameera** [unosquare/embedio#26]
Is there a way to enable wss support?

**Comment by geoperez** [comment]
Hi @sameera, did you already try to use the EmbedIO binding to wss with a certificate in your machine? For example following these steps to do the cert thing: http://stackoverflow.com/questions/11403333/httplistener-with-https-support

**Comment by sameera** [comment]
Hi, 
Thanks I trybit out. However, at a glance, this approach seems to limit me toba static port number (I.e. I'd have to hard code the port in the app as the cert is bound manually a one). 
What do you recliner the effort would be to do what socketsharp is doing (loading the cert off a pfx file)?

**Comment by geoperez** [comment]
The implementation in socketsharp looks really good, I'm going to take a deep look and let you know if we move to implement something similar.

**Comment by sameera** [comment]
Just checking in: Have you decided on either way?

**Comment by mariodivece** [comment]
@sameera Could you please try the following nuget? This is the simplest, most transparent way of setting certificates on ports and bindings. Please check it out and let us know how it goes. https://www.nuget.org/packages/SslCertBinding.Net/

**Comment by sameera** [comment]
Thanks Mario.
This would probably work for most scenarios; however, not mine. 
Reading through this implementation, looks like it needs the certificate to already be in the user's Certificate store. Which means the certificate is already installed and this simply does port binding to it. 

In my scenario, I have a standalone executable that I distribute which has the embedded websocket server. I want to embed the X509 certificate in the app as an embedded resource. I got this working fine with WebSocket-Sharp library. But, the implementation of WSS is almost done from scratch as it defines it's own HttpListener, WebSocketContext etc. rather than using the native .NET counterparts. So, (among other reasons) I'd prefer to use a EmbedIO instead if possible.

**Comment by sameera** [comment]
Hi,
Just want to let you know that this is no longer a requirement for me. Therefore, I could close this issue for now unless, this is a feature you are planning to build eventually.

**Comment by mariodivece** [comment]
This is an old thread. I'm closing this issue because there currently are no plans to implement X509 certs within EmbedIO but rather configure them via standard methods.

**Comment by mariodivece** [comment]
As an update, a combination of the following methods/packages should work:
https://github.com/segor/SslCertBinding.Net
http://stackoverflow.com/questions/30131591/httplistener-with-ssl-certificate-hanging-on-getcontext
