### ISSUE TITLE
Close a websocket connection with custom close status code

### ISSUE THREAD

**Issue by jasonkuo41** [unosquare/embedio#260]
**Is your feature request related to a problem? Please describe.**
Sometimes, there are requests that the server cannot handle or is against the server's policy, instead of marking the close frame as Normal, we want to mark it as other code (by spec or custom), so that the client will be able to present or handle the error instead.

**Describe the solution you'd like**
Add a method:
> public Task CloseAsync(CloseStatusCode code, string Comment = "", CancellationToken token = default);

**Describe alternatives you've considered**
Well, it's possible to send a message before closing the WebSocket to notify any sorts of error.

**Comment by geoperez** [comment]
👍

**Comment by geoperez** [comment]
I created a new branch for this issue: Issue260-CloseWebSocket

**Comment by geoperez** [comment]
Please check the following PR: https://github.com/unosquare/embedio/pull/268

**Comment by geoperez** [comment]
Please check new release: https://www.nuget.org/packages/EmbedIO/2.4.0

**Comment by geoperez** [comment]
Status?

**Comment by jasonkuo41** [comment]
Affirmative, got the update.
But why remove the WebSocket client? It has now broken my code.

**Comment by geoperez** [comment]
Sorry about that. The WebSocket client was kinda buggy, and the idea is to keep simple and tiny the web server. Did you try the WebSocket Client from .NET framework?

**Comment by jasonkuo41** [comment]
Oh, I initially wanted to use Embed.IO as a mean of WebSocket client/ server, rather than using it as a web server.
