### ISSUE TITLE
StaticFilesModule: 403 Forbidden on VirtualPath

### ISSUE THREAD

**Issue by developerFlo** [unosquare/embedio#263]
**The problem**
I want to serve static files from different directories.
Therefore I tried to set up a **StaticFilesModule** using VirtualPaths.
Unfortunatelly all **requests to something else then the base directory returns 403 Forbidden**.

**To Reproduce**
```
var server = new Unosquare.Labs.EmbedIO.WebServer("http://localhost:8080");
server.RegisterModule(new StaticFilesModule(new Dictionary<string, string>() {
        { "/",         @"C:\Users\current\AppData\Local\MyApp\wwwroot" },
        { "/userdata", @"C:\Users\current\Documents\MyApp\userdata" }
    }));
```

GET http://localhost:8080/userdata/me.png -> 403

**Requested behaviour**
Is there any way serve static files out of different root directories?
In my opinion the above code should work that way. Virtual Paths are commonly used to serve files from different locations than the root.
Another possible solution would be to add multiple "StaticFilesModule"s for different HTTP paths. But this also doesn't seem to be possible currently.

**Hint**
I identified the following lines of code as the root problem.
Core\VirtualPaths.cs:43-46
```
// Check if the requested local path is part of the root File System Path
if (IsPartOfPath(localPath, FileSystemPath) == false)
{
    return VirtualPathStatus.Forbidden;
}
```
By additionally checking against the file system path behind the virtual paths, everything works in my case.
```
string testLocalPath = localPath;
if (!IsPartOfPath(localPath, FileSystemPath) && !this.Values.Any(virtualFileSystemPath => IsPartOfPath(testLocalPath, virtualFileSystemPath)))
```

**Comment by geoperez** [comment]
Please check new release: https://www.nuget.org/packages/EmbedIO/2.4.0

**Comment by developerFlo** [comment]
Many thanks for the quick fix.
I changed back from the clone to the original NuGet-Package and everything works as expected.
