### ISSUE TITLE
both restapi and websocket for same user [help wanted]

### ISSUE THREAD

**Issue by bufferUnderrun** [unosquare/embedio#265]
Hi,

I'm using both restapi and websocket in my application.

Do you have an idea, how to retrieve the user websocket context from the restapi context ?
The goal it to notify the user with websoket (from server) after it has done a certain action from the restapi.

Thanks for your help.

**Comment by geoperez** [comment]
You need to add a static ConcurrentDictionary somewhere in your application to store the context. There is no way to communicate between the two modules inside EmbedIO.

**Comment by bufferUnderrun** [comment]
Thanks for your help.
Well, I've no other solution. I use a ConcurrentDictionary() in WebSocketServer and my web client send a websocket message to server containing cookie name. From my WebApi, i call websocket server Send by passing the current sesssion cookie.

You can close the issue.
