### ISSUE TITLE
Socket: accept failed, error: Too many open files(24)

### ISSUE THREAD

**Issue by fdsagizi** [unosquare/embedio#270]
Hi, we have many simple REST  requests on our server. may be over 10 000 per sec

why embedio open file descriptors for every POST/GET requests ? 

when FD over 1024 on linux,  we start receive this error  **Socket: accept failed, error: Too many open files(24)**

You can see how many FDs you use, for process: **ls -1 /proc/<process_id>/fd | wc -l**

And how we can disable open file descriptor for REST requests ?

**Comment by geoperez** [comment]
Are you running a performance testing with multi-threads? What I understand from UNIX sockets, that they have FILE descriptors too. So maybe are you reaching the limit of open sockets. Try to update your limit with `ulimit` (https://stackoverflow.com/questions/880557/socket-accept-too-many-open-files)
