### ISSUE TITLE
Disposable WebModules should be automatically disposed.

### ISSUE THREAD

**Issue by rdeago** [unosquare/embedio#273]
**Is your feature request related to a problem? Please describe.**

I want to use a `ReaderWriterLockSlim` in a WebModule. Since it uses unmanaged resources, good practice suggests that I implement `IDisposable`. Problem is, nobody is going to call `Dispose`.

**Describe the solution you'd like**

WebModules should be disposed in the `Dispose` method of `WebServer`. Actually, the `WebModules` class should implement `IDisposable` itself and:

* dispose all modules in its `Dispose` method;

* dispose the unregistered module in `UnregisterModule`.

There is no need for `IWebModule` to extend `IDisposable`, nor for `WebModuleBase` to implement it (both of which would be breaking changes). The `is` operator can be used to check whether a module is disposable and (thanks to pattern matching) cast it to `IDisposable` on the fly.

**Describe alternatives you've considered**

The only alternative I see is, whenever a disposable module is used, save a reference to it and call `Dispose` after stopping the `WebServer`. However, requiring application code to perform housekeeping for a library does not look like a good thing to do, especially when (as it is the case here) it can be done easily and transparently.

**Additional context**

I ran into the need for `ReaderWriterLockSlim` while preparing a PR to fix #272.

The module I need to be disposable is `StaticFilesModule`. Requiring every user of `StaticFilesModule` to dispose it in application code would be a breaking change, even if no changes are otherwise made to the APIs. It would also be quite an annoyance.

I'm going to prepare a PR for this before finishing the fix for #272. It will be completely transparent to existing user code.

@geoperez, do you agree, or is there something I overlooked?

**Comment by geoperez** [comment]
I like the idea! Are you working on this fix too or do you need help?

**Comment by rdeago** [comment]
I'm currently working on it.

Fixing `WebModules` was trivial. `WebServer` is disposable and thus only requires one more line of code.

`TestWebServer`, on the other hand, is not disposable. I'm currently making it so and adding `using` blocks wherever it is used. Technically I'm introducing a breaking change, since `TestWebServer` is part of the library, but it has no impact on "normal" users.

**Comment by geoperez** [comment]
Yeah, I can't remember why I didn't include IDisposable to TestWebServer... But probably it was just a mistake.

**Comment by geoperez** [comment]
I changed WebSocketModule for dispose all WebSocketServers instances properly! Again thanks for the heads up!

**Comment by rdeago** [comment]
You're welcome! I use EmbedIO in practically all my applications, so it's in my best interest that it keeps improving. Isn't open source great?!
