### ISSUE TITLE
StaticFilesModule regression: requesting a directory listing fails.

### ISSUE THREAD

**Issue by rdeago** [unosquare/embedio#278]
**Describe the bug**
EmbedIO v2.6.0 does not recognize path `/files` as mappable by virtual path `/files/`. Instead, it tries to resolve it using a shorter virtual path, or the root path.

**To Reproduce**
1. Have a directory structure as follows:

* /my/path/ _<-- feel free to use a Windows path, the problem is not bound to Unix-like systems_
  * root/
    * file1
    * pictures
  * download/
    * file.zip
  * pictures/
    * pic.jpg

2. Create a new console application as follows:
```C#
using System;
using System.Threading;
using System.Threading.Tasks;
using Unosquare.Labs.EmbedIO;

namespace MyTest
{
    static class Program
    {
        static void Main()
        {
            using (var cts = new CancellationTokenSource())
            using (var server = new WebServer("http://localhost:8080"))
            {
                server.RegisterModule(new StaticFilesModule(/my/path/root", null, new Dictionary<string, string>() {
                    { "/download", "/my/path/download" }
                }, true));
                Task.Run(() => server.RunAsync(cts.Token));
                Console.ReadKey();
            	cts.Cancel();
            }
        }
    }
}
```

3. Start your application.

4. On the same machine, start Chrome (or the browser of your choice), type the following on the address bar, press Enter, and verify that an error "404 - Not Found" is shown instead of the directory listing for `/my/path/download`:
> `http://localhost:8080/download`

5. Now type the following on the address bar, press Enter, and verify that the file `/my/path/pictures` is shown (or downloaded, depending upon the file contents) instead of the directory listing for `/my/path/pictures`:
> `http://localhost:8080/pictures`

**Expected behavior**
Directory listings should work.

**Server environment**
 - Ubuntu 18.10 / 64 bit
 - Mono 5.20.1
 - EmbedIO v5.6.0

Notice, though, that the described behavior is not apt to change in a different server environment (see the "Additional context" section below).

**Client environment**
 - Windows 10 Pro / 64 bit
 - Chrome 73.0.3683.103 (Official build) (64 bit)

Notice, though, that the described behavior is not apt to change in a different client environment (see the "Additional context" section below).

**Additional context**
The problem is exactly the same if a default document should be shown instead of a directory listing.

This is due to URL path normalization, introduced in PR #275: base URL paths (such as `/download/` and `/pictures/`) are internally forced to end with a slash, while requested URL paths are forced to NOT end with a slash. Then `VirtualPath.CanMapUrlPath` just checks that the requested path _starts with_ the base URL path; this check obviously fails if the base URL path is `/download/` and the requested path is `/download`.

My bad. A PR with the fix is on its way.

**Comment by geoperez** [comment]
New version published: v2.7.0
