### ISSUE TITLE
Wildcards only supported at the end of a URL?

### ISSUE THREAD

**Issue by jondavidford** [unosquare/embedio#28]
Correct me if I'm mistaken, but it seems like the "*" wildcard is only supported at the end of a URL rather than anywhere within it. Is this intentional? Looking through the documentation, I don't see any examples of a wildcard not at the end of a URL. Some of my endpoints require a wildcard in the middle of a URL, and I'm sure other developers have the same requirements.

**Comment by geoperez** [comment]
Can you post a sample where do you need the support to middle wilcard?

Thank you

On Thu, Mar 24, 2016 at 8:43 AM, Jon Ford <notifications@github.com> wrote:

> Correct me if I'm mistaken, but it seems like the "*" wildcard is only
> supported at the end of a URL rather than anywhere within it. Is this
> intentional? Looking through the documentation, I don't see any examples of
> a wildcard not at the end of a URL. Some of my endpoints require a wildcard
> in the middle of a URL, and I'm sure other developers have the same
> requirements.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/unosquare/embedio/issues/28>
>



-- 
Geo Pérez

**Comment by jondavidford** [comment]
Sure. In my API, I have the concept of groups of devices. So, to get the nth group of devices, the endpoint that makes the most sense to me is _/api/groups/n/devices_.

Alternatives:
_/api/groups/n_
Doesn't make sense since groups have more properties than just devices.

_/api/groups/devices/n_
This is what I'm currently using as a workaround, but I'm not satisfied. Here's why: I also need an API endpoint the get the groups that are assigned to a device. If wildcard is supported in the middle of a URL, then my ideal endpoint is _/api/devices/n/groups_. Otherwise, I must use _/api/devices/groups/n_. Now an API user might be confused about which endpoint does what (_/api/devices/groups/n_ vs. _/api/groups/devices/n_). When the wildcard is in the middle of the endpoint, the endpoint reads more like a language and we can deduce what it does. When the wildcard comes at the end of the endpoint, it is harder to tell whether the identifier applies to the first resource or the second (group or device).

I also have endpoints that require multiple wildcards, but that is a separate issue :)

**Comment by mariodivece** [comment]
Up-voted. I agree with Jon.

**Comment by bufferUnderrun** [comment]
Hi,

I've the same need. I use the ninja patch below to support one wildcard in the middle of the url.

```diff
--- Unosquare.Labs.EmbedIO/Modules/WebApiModule.cs
+++ Unosquare.Labs.EmbedIO/Modules/WebApiModule.cs
@@ -32,11 +32,17 @@
                 var path = context.RequestPath();
                 var verb = context.RequestVerb();
                 var wildcardPaths = DelegateMap.Keys
-                    .Where(k => k.EndsWith("/" + ModuleMap.AnyPath))
+                    .Where(k => k.Contains("/" + ModuleMap.AnyPath))
                     .Select(s => s.ToLowerInvariant())
                     .ToArray();
 
-                var wildcardMatch = wildcardPaths.FirstOrDefault(p => path.StartsWith(p.Substring(0, p.Length - 1)));
+                var wildcardMatch = wildcardPaths.FirstOrDefault(
+                    p => // wildcard at the end
+                         path.StartsWith(p.Substring(0, p.Length - ModuleMap.AnyPath.Length))
+                         // wildcard in the middle so check both start/end
+                         || (path.StartsWith(p.Substring(0, p.IndexOf(ModuleMap.AnyPath)))
+                             && path.EndsWith(p.Substring(p.IndexOf(ModuleMap.AnyPath)+1)))
+                );
 
                 if (string.IsNullOrWhiteSpace(wildcardMatch) == false)
                     path = wildcardMatch;
```

A better solution could be to support regexp and map match group to argument of the method.
example : 

```C#
[WebApiHandler(HttpVerbs.Get, RelativePath + "people/{id:([0-9]+)}")]
public bool GetPeople(WebServer server, HttpListenerContext context, int id) {
   ...
}


```

**Comment by mariodivece** [comment]
@bufferUnderrun would you be able to help us support regex-based routing without breaking wildcard routing by providing a pull request?

**Comment by geoperez** [comment]
I commited the @bufferUnderrun suggestion with an Unit Test and it's seems to be fine. But I agreed to include better support with regex to routes and bind segments as arguments in the WebApi handler.

**Comment by mariodivece** [comment]
@geoperez the routing attribute needs to have the default constructor to use wildcard matching and add an additional constructor taking in a string and a RoutingStrategy enum that has the members Wildcard and RegEx

**Comment by geoperez** [comment]
@mariodivece a very early version to support Regex and send args directly to the WebApi method is available in the next test file: https://github.com/unosquare/embedio/blob/master/Unosquare.Labs.EmbedIO.Tests/TestObjects/TestRegexController.cs

Let me know your thoughts

**Comment by bufferUnderrun** [comment]
cool, i'll test this.

**Comment by bufferUnderrun** [comment]
In your [last commit](https://github.com/unosquare/embedio/commit/80bd2c8c582787fe61f76dcfcd15f01b5343901a#diff-74b973dfeba646f9f188d25b3af25fcfR176), you use the new syntax for Properties introduced in C# 6.0 for property initializer.

Do you plan to retargeting to the most recent C# version ? because vs2013 does not support this...

**Comment by mariodivece** [comment]
we are now using VS 2015/C# 6. The solution file and some areas of the codes are now starting to use the features provided by C# 6. We will however continue to target .net framework 4.5 as there is no apparent benefit for this project to target later versions.

**Comment by mariodivece** [comment]
@geoperez The implementation is incomplete. Please avoid publishing a nuget package until the async implementation is completed. Starting to look pretty good though! :+1:

**Comment by bufferUnderrun** [comment]
@mariodivece hum, so after install vs2008 to maintain a old asp.net mvc1 project, vs2010 for a outlook addin and vs2013 for my current aspnet mvc5 projects, i will install vs2015... :)  Hope embedio will rule them all :+1:

**Comment by mariodivece** [comment]
@bufferUnderrun Ha! Story of my life. @geoperez has it worse: He has to run VB6 on a VM to support some really old application.

**Comment by geoperez** [comment]
:crying_cat_face:

**Comment by bufferUnderrun** [comment]
@geoperez you win !

**Comment by geoperez** [comment]
@mariodivece async methods are available with Regex Strategic. I created more unit tests to check async implementation in both ways.

**Comment by geoperez** [comment]
The new Nuget was published.
