### ISSUE TITLE
Add subprotocol handling to WebSocket support

### ISSUE THREAD

**Issue by jeffska** [unosquare/embedio#285]
The EmbedIO native WebSocket handling and exposed method via IHttpContext don't allow for the server to set a subprotocol when accepting a client request. The .NET System.Net.HttpListenerContext.AcceptWebSocketAsync method supports a string parameter for the subprotocol identifier.

The lack of this prevents a server from doing any subprotocol indication or negotiation.

**Comment by geoperez** [comment]
I created the branch Issue285.

**Comment by geoperez** [comment]
Hi @jeffska can you check the following line in the PR:

https://github.com/unosquare/embedio/pull/287/files#diff-d9acba2bc05568513c9173a84ffc1e0bR51

Is this what are you expecting?

**Comment by jeffska** [comment]
Thanks @geoperez. Yes that's what I had in mind. I did see a couple of things:

1. The subProtocol parameter on IHttpContext.AcceptWebSocketAsync should probably have a null default value to match the implementation and keep it source-compatible. If you think it needs to be binary-compatible then you could add an overload for the new signature.

2. In the WebSocketServer abstract class, SubProtocol probably shouldn't be a property since it could vary based on the request; specifically if the client sends the Sec-WebSocket-Protocol header with a specific subprotocol request. You may want to add another event that gets raised before accepting so the implementation can set the subprotocol. Doesn't really matter for my case.

**Comment by geoperez** [comment]
I updated the branch with your suggestions. For item 2, if the subprotocol is always sent by the client in the initial request, can we just read from the header? Can you check what I did?

**Comment by jeffska** [comment]
Hi @geoperez. The issues with automatically setting it from the client request header are that the client can send in a list of subprotocols in order of preference. The server-side can then select one of those to use for the session. The server can also choose not to support the requested subprotocol and not send the header back in the handshake.

**Comment by geoperez** [comment]
I see, let me explore the event suggestion! Thanks

**Comment by rdeago** [comment]
@jeffska, just out of curiosity, do you mean that the _same_ `WebSocketsServer` may choose to use different sub-protocols with different clients?

I'm admittedly new to all things WebSockets, hence some real-world use case would greatly help me here.

**Comment by jeffska** [comment]
@geoperez Yes that's right. Subprotocols are technically negotiated on each connection. Here's an example from the RFC.

The handshake from the client looks as follows:
```
        GET /chat HTTP/1.1
        Host: server.example.com
        Upgrade: websocket
        Connection: Upgrade
        Sec-WebSocket-Key: dGhlIHNhbXBsZSBub25jZQ==
        Origin: http://example.com
        Sec-WebSocket-Protocol: chat, superchat
        Sec-WebSocket-Version: 13
```
   The handshake from the server looks as follows:
```
        HTTP/1.1 101 Switching Protocols
        Upgrade: websocket
        Connection: Upgrade
        Sec-WebSocket-Accept: s3pPLMBiTxaQ9kYGzzhZRbK+xOo=
        Sec-WebSocket-Protocol: chat
```
In this case the client supports two subprotocols, and the server selected the one that it can support (`chat`). I don't have a feel for how common it is, but it's definitely part of the specification.

**Comment by geoperez** [comment]
@jeffska instead of adding an event, I just include an virtual method to the abstract class to allow the developer to make his own subProtocol handler.

https://github.com/unosquare/embedio/pull/287/commits/e12469dcb79ff515787ab19cdb8cb229f0eb4c7d

What do you think?

**Comment by geoperez** [comment]
Status?

**Comment by rdeago** [comment]
Subprotocol support for v3.0 is coming in next commit.

In short:

* every `WebSocketServer` will have to declare which subprotocol(s) it supports, if any, by calling `AddProtocol(string)`, or `AddProtocols(params string[])`, or `AddProtocols(IEnumerable<string>)` in the constructor;

* the first requested subprotocol that is also supported will appear in the accept response;

* both the accepted subprotocol and an `IEnumerable<string>` of the requested subprotocols will be available as properties of `IWebSocketContext`.

**Comment by rdeago** [comment]
WebSocket support in version 3.0 is now tracked in #295.
