### ISSUE TITLE
Escaping issue in Extension.RequestFormData()

### ISSUE THREAD

**Issue by bufferUnderrun** [unosquare/embedio#29]
Hi,

i've found a error in the way `Extension.RequestFormData()` is escaping characters, in particular the  "plus" sign.

In one of my forms, i use an ajax call with jQuery to send data to a RestApi Controller. When jQuery calls `$form.serialize()`, it encodes space as "plus" sign. Example : `field1=value1withoutspace&field2=value2+with+spaces`.

The problem is that the `Uri.UnescapeDataString()` do not correctly handle the "plus" sign as a space but as a "plus" sign... You can see more details to [blog msdn](https://blogs.msdn.microsoft.com/yangxind/2006/11/08/dont-use-net-system-uri-unescapedatastring-in-url-decoding/) or [rick strahl blog](http://weblog.west-wind.com/posts/2009/Feb/05/Html-and-Uri-String-Encoding-without-SystemWeb).

A workaround consist of using [WebUtility.UrlDecode](http://stackoverflow.com/a/33928647/3699737) and so you can see a proposal patch below.

```patch
--- C:\www\embedio-master\Unosquare.Labs.EmbedIO\Extensions.cs.
+++ C:\www\embedio-master\Unosquare.Labs.EmbedIO\Extensions.cs
@@ -281,7 +281,7 @@
 
                     return stringData.Split('&')
                         .ToDictionary(c => c.Split('=')[0],
-                            c => Uri.UnescapeDataString(c.Split('=')[1]));
+                            c => WebUtility.UrlDecode(c.Split('=')[1]));
                 }
             }
         }
```

Thanks,

**Comment by mariodivece** [comment]
Agreed. Thank you for the quick fix! We will correct ASAP.

**Comment by bufferUnderrun** [comment]
Thank for update.

**Comment by mariodivece** [comment]
The Pull Request has been completed. @geoperez please update the NuGet package.

**Comment by geoperez** [comment]
The NuGet was updated.

**Comment by bufferUnderrun** [comment]
Could you update the Newtonsoft.Json dependency to (>= 8.0)  for this last nuget package (v1.0.15). It is set to Newtonsoft.Json (>= 7.0.1) but it seems it has been compiled with the v8.

Without, it throws an exception (in French, sorry) :
`Impossible de charger le fichier ou l'assembly 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' ou une de ses dépendances. La définition trouvée du manifeste de l'assembly ne correspond pas à la référence de l'assembly. (Exception de HRESULT : 0x80131040)`

**Comment by geoperez** [comment]
Updated the dependency, thank you for the heads up

**Comment by mariodivece** [comment]
@geoperez if this is closed and you released the updated NuGet package, please close this issue.
