### ISSUE TITLE
WebSocket support in EmbedIO v3.0

### ISSUE THREAD

**Issue by rdeago** [unosquare/embedio#295]
WebSocket support has changed (hopefully for the better) in EmbedIO version 3.0. Here's a brief summary of what's changed since version 2.

#### _"I'm already bored. Show me the code!"_

Your wish is my command. Here's the new `IWebSocketContext` interface:
```C#
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Net;
using System.Security.Principal;
using System.Threading;

namespace EmbedIO
{
    /// <summary>
    /// Represents the context of a WebSocket connection.
    /// </summary>
    public interface IWebSocketContext
    {
        /// <summary>
        /// Gets a unique identifier for a WebSocket context.
        /// </summary>
        string Id { get; }

        /// <summary>
        /// Gets the <see cref="CancellationToken "/> used to cancel operations.
        /// </summary>
        CancellationToken CancellationToken { get; }

        /// <summary>
        /// Gets the unique identifier of the opening handshake HTTP context.
        /// </summary>
        string HttpContextId { get; }

        /// <summary>
        /// Gets the session proxy associated with the opening handshake HTTP context.
        /// </summary>
        ISessionProxy Session { get; }

        /// <summary>
        /// Gets the dictionary of data associated with the opening handshake HTTP context.
        /// </summary>
        IDictionary<object, object> Items { get; }

        /// <summary>
        /// Gets the server IP address and port number to which the opening handshake request is directed.
        /// </summary>
        IPEndPoint LocalEndPoint { get; }

        /// <summary>
        /// Gets the client IP address and port number from which the opening handshake request originated.
        /// </summary>
        IPEndPoint RemoteEndPoint { get; }

        /// <summary>The URI requested by the WebSocket client.</summary>
        Uri RequestUri { get; }

        /// <summary>The HTTP headers that were sent to the server during the opening handshake.</summary>
        NameValueCollection Headers { get; }

        /// <summary>The value of the Origin HTTP header included in the opening handshake.</summary>
        string Origin { get; }

        /// <summary>The value of the SecWebSocketKey HTTP header included in the opening handshake.</summary>
        string WebSocketVersion { get; }

        /// <summary>The list of subprotocols requested by the WebSocket client.</summary>
        IEnumerable<string> RequestedProtocols { get; }

        /// <summary>The accepted subprotocol.</summary>
        string AcceptedProtocol { get; }

        /// <summary>The cookies that were passed to the server during the opening handshake.</summary>
        ICookieCollection Cookies { get; }

        /// <summary>An object used to obtain identity, authentication information, and security roles for the WebSocket client.</summary>
        IPrincipal User { get; }

        /// <summary>Whether the WebSocket client is authenticated.</summary>
        bool IsAuthenticated { get; }

        /// <summary>Whether the WebSocket client connected from the local machine.</summary>
        bool IsLocal { get; }

        /// <summary>Whether the WebSocket connection is secured using Secure Sockets Layer (SSL).</summary>
        bool IsSecureConnection { get; }

        /// <summary>The <see cref="IWebSocket"/> interface used to interact with the WebSocket connection.</summary>
        IWebSocket WebSocket { get; }
    }
}
```
In short, all information that may be gathered from the opening handshake's HTTP context is readily available. The new `IWebSocketContext` is very similar to `System.Net.WebSockets.WebSocketContext`, with some EmbedIO-specific goodies such as `Id`, `HttpContextId`, `Items`, and `Session`.

Now let's take a look at what else has changed.

#### No more distinction between `WebSocketsModule` and `WebSocketsServer`. 

EmbedIO v2 had a `WebSocketsModule` that grouped one or more instances of `WebSocketsServer` together.

Now a `WebSocketModule` (renamed for consistency with the WebSocket protocol as described in [RFC6455](https://tools.ietf.org/html/rfc6455)) _is_ a WebSocket server. You may add as many as you want in the web server's module chain, they don't need to be grouped together any longer.

#### Async all the way

Version 2's `WebSocketsServer` had a number of protected virtual methods acting as event handlers: `OnClientConnected`, `OnClientDisconnected`, `OnFrameReceived`, `OnMessageReceived`. They were all synchronous methods, even if internally `WebSocketsServer` worked asynchronously.

The new `WebSocketModule`'s protected callbacks, on the contrary, are all asynchronous, as well as the `SendAsync` and `BroadcastAsync` methods that have replaced `Send` and `Broadcast`, respectively.

#### Automatic subprotocol negotiation

Each `WebSocketModule`-derived class can declare which subprotocol(s) it can accept.

When a client initiates a WebSocket opening handshake:

* if the list of accepted subprotocols is empty, the connection is accepted only if no `SecWebSocketProtocol` header is present in the request;

* if the list of accepted subprotocols is not empty, the connection is accepted only if one or more `SecWebSocketProtocol` headers are present in the request and one of them specifies one of the subprotocols in the list. The first subprotocol specified by the client, that is also present in the module's list, is then copied in the handshake response.

If a connection is not accepted because of a subprotocol mismatch, a `400 Bad Request` response is sent back to the client. The response contains one or more `SecWebSocketProtocol` headers that specify the list of accepted subprotocols (if any).

#### _"The code. I said show me the code!"_

Of course! Here are the salient parts of the new `WebSocketModule` APIs.
```C#
namespace EmbedIO.Modules
{
    public abstract class WebSocketModule : WebModuleBase, IDisposable
    {
        protected WebSocketModule(string urlPath, bool enableConnectionWatchdog);

        // Change the configuration at will, but do it before you start
        // the web server!
        protected int MaxMessageSize { get; set; }
        protected TimeSpan KeepAliveInterval { get; set; }
        protected Encoding Encoding { get; set; }

        // Subprotocol management
        protected void AddProtocol(string protocol);
        protected void AddProtocols(IEnumerable<string> protocols);
        protected void AddProtocols(params string[] protocols);

        // Contexts representing currently connected clients
        protected IReadOnlyList<IWebSocketContext> ActiveContexts { get; }

        // Data transmission methods
        protected async Task SendAsync(IWebSocketContext context, string payload);
        protected async Task SendAsync(IWebSocketContext context, byte[] payload);
        protected Task BroadcastAsync(byte[] payload);
        protected Task BroadcastAsync(byte[] payload, Func<IWebSocketContext, bool> selector);
        protected Task BroadcastAsync(string payload);
        protected Task BroadcastAsync(string payload, Func<IWebSocketContext, bool> selector);

        // When you're finished...
        protected async Task CloseAsync(IWebSocketContext context);

        // Async callbacks!
        protected abstract Task OnMessageReceivedAsync(IWebSocketContext context, byte[] buffer, IWebSocketReceiveResult result);
        protected virtual Task OnFrameReceivedAsync(IWebSocketContext context, byte[] buffer, IWebSocketReceiveResult result);
        protected virtual Task OnClientConnectedAsync(IWebSocketContext context);
        protected virtual Task OnClientDisconnectedAsync(IWebSocketContext context);
    }
}
```

#### Example: a simple chat server

Straight from the `EmbedIO.Samples` project.
```C#
using System.Threading.Tasks;
using EmbedIO.Modules;

namespace EmbedIO.Samples
{
    public class WebSocketChatModule : WebSocketModule
    {
        public WebSocketChatModule(string urlPath)
            : base(urlPath, true) { }

        protected override Task OnMessageReceivedAsync(IWebSocketContext context, byte[] rxBuffer, IWebSocketReceiveResult rxResult)
            => SendToOthersAsync(context, Encoding.GetString(rxBuffer));

        // Async calbacks make it easy to do more than one thing at a time.
        protected override Task OnClientConnectedAsync(IWebSocketContext context)
            => Task.WhenAll(
                SendAsync(context, "Welcome to the chat room!"),
                SendToOthersAsync(context, "Someone joined the chat room."));
        
        protected override Task OnClientDisconnectedAsync(IWebSocketContext context)
            => SendToOthersAsync(context, "Someone left the chat room.");

        // You can decide whom to broadcast to.
        private Task SendToOthersAsync(IWebSocketContext context, string payload)
            => BroadcastAsync(payload, c => c != context);
    }
}
```

---

New WebSocket support committed in 3315686091c98f7a719cef86e427bffe619e3e5e.

All feedback is, as always, highly appreciated.

**Comment by bufferUnderrun** [comment]
@rdeago   You've done a great job !

So with this new version, can you confirm that : if i save data in the user Session from HttpContext (RestAPI), i can retrieve it from the websocket ?

**Comment by rdeago** [comment]
@bufferUnderrun thanks!

Yes, you can exchange session data between WebSocket servers and other modules.

If you use `LocalSessionManager` (the v3.0 replacement for `LocalSessionModule`) all requests using the same session will be using _the same session object_, allowing for real-time data exchange between WebSocket servers and other modules, e.g. web API handlers.

Other session managers (there are none currently, but still) could choose to create a distinct session object for each HTTP request, as PHP does. In this case, changes made to session data by a web API handler will not be seen by an already-connected WebSocket server, and vice versa.
