### ISSUE TITLE
WebSocketsServer is abstract but has a non-virtual Dispose method

### ISSUE THREAD

**Issue by PhilipDaniels** [unosquare/embedio#3]
Please implement Dispose according to the correct pattern so that subclasses which have disposable objects can clean them up properly.

https://msdn.microsoft.com/en-us/library/vstudio/b1yfkh5e%28v=vs.100%29.aspx

Code Analysis will warn of this issue:

https://msdn.microsoft.com/query/dev12.query?appId=Dev12IDEF1&l=EN-US&k=k(CA1063);k(TargetFrameworkMoniker-.NETFramework,Version%3Dv4.5)&rd=true

**Comment by mariodivece** [comment]
Thanks for your input Philip! I have implemented the missing method.
