### ISSUE TITLE
MimeTypes.DefaultMimeTypes readonly in v2.9.0

### ISSUE THREAD

**Issue by bufferUnderrun** [unosquare/embedio#309]
The last commit and v2.9.0 introduce a breaking change (`MimeTypes.DefaultMimeTypes` is `IReadOnlyDictionary` whereas it was `IDictionary`) that as already been discussed in https://github.com/unosquare/embedio/issues/302

Can you revert the part where `MimeTypes.DefaultMimeTypes` is `IDictionary` ?

Thanks.

**Comment by geoperez** [comment]
You can check the new version 2.9.1.

**Comment by bufferUnderrun** [comment]
thanks for the revert ! All clear :+1:
