### ISSUE TITLE
Web Socket Bad Request - FireFox

### ISSUE THREAD

**Issue by k3z0** [unosquare/embedio#311]
**Describe the bug**
Getting error 400 (Bad request) when using web sockets in Firefox.

![imagen](https://user-images.githubusercontent.com/5455304/60134680-ac512180-9765-11e9-9f65-b2c6e9b9d7a0.png)

**Comment by rdeago** [comment]
Thanks @k3z0 for your input!

Apparently there was no agreement over the subprotocol to use.

EmbedIO v3 requires that the `Sec-WebSocket-Protocol` request header specifies one of the subprotocols declared via the `WebSocketModule.AddProtocol` method.

If `WebSocketModule.AddProtocol` is not called, only requests _not_ specifying any subprotocol are accepted.

The `Sec-WebSocket-Protocol: undefined` request header seems to indicate some uninitialized Javascript variable. It looks as if the header was added to the request without checking whether there was any actual value to write in it. Unless, of course, "undefined" is the name of the subprotocol you intended to use.

If the problem persists after verifying that the client and server both declare the same subprotocol (or no subprotocol), please let us know. Note that in this case, more information will probably be needed to identify the cause of the issue, such as:
* the code you use to initialize your web server;
* the relevant section of your web server's log.

**Comment by k3z0** [comment]
Thanks @rdeago 

I'm specifying a subprotocol and now the web socket is working.
