### ISSUE TITLE
No exception raised to the surface from WebServer.RunAsync() when a SocketException is thrown inside

### ISSUE THREAD

**Issue by jusovsky** [unosquare/embedio#313]
Server.RunAsync() does not throw any exception when binding fails.  The only way I was able to catch this was to add a continuation and look for the exception, there.
I don't know exactly how to repro this issue because I don't know the reason it even occurred on my system.  I ran across this issue when I tried binding to port 50635 and got a SocketException with message "An attempt was made to access a socket in a way forbbiden by its access permissions."  Others have run across this exception unrelated to EmbedIO and tried similar things that I did like looking for port usage. See https://stackoverflow.com/questions/10461257/an-attempt-was-made-to-access-a-socket-in-a-way-forbbiden-by-its-access-permissi.

Windows 10 v1903
Below is the stack trace:
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Unosquare.Net.EndPointListener..ctor(HttpListener listener, IPAddress address, Int32 port, Boolean secure)
   at Unosquare.Net.EndPointManager.<>c__DisplayClass9_0.<GetEpListener>b__1(Int32 x)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Unosquare.Net.EndPointManager.<GetEpListener>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Unosquare.Net.EndPointManager.<AddPrefix>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Unosquare.Net.EndPointManager.<AddListener>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Unosquare.Net.EndPointManager.<AddListener>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Unosquare.Net.HttpListener.Start()
   at Unosquare.Labs.EmbedIO.WebServer.<RunAsync>d__46.MoveNext()

**Comment by rdeago** [comment]
Hello @jusovsky, thanks for your input!

The exception is not "hidden" in any way: it just occurs in the execution context of the `Task` returned by `RunAsync`. If you want to catch an exception thrown by `RunAsync` (or by any asynchronous method) when using `Task.Run`, without having to wait for the returned `Task` to terminate, attaching a continuation to it is exactly the thing to do.

If you use `Task.Run` regularly and do not want to attach an exception-handling continuation to each returned `Task`, you may want to add a handler to the [`TaskScheduler.UnobservedTaskException`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskscheduler.unobservedtaskexception) static event. Otherwise, when a faulted `Task` is garbage collected your program will be terminated.

Thomas Levesque said it all, better than I ever could, [in a StackOverflow answer](https://stackoverflow.com/a/32317124) that is now four years old, but still actual.

**Comment by jusovsky** [comment]
Argh.  You are right.  I've been doing async/await so heavily that I forgot how plain old tasks handled exceptions!  Thank you for the refresher.  :\

**Comment by rdeago** [comment]
You're welcome. We've all been there. (Me? More times than I'm willing to admit! 😁)

You're also welcome to [join EmbedIO's Slack workspace](https://join.slack.com/t/embedio/shared_invite/enQtNjcwMjgyNDk4NzUzLWQ4YTE2MDQ2MWRhZGIyMTRmNTU0YmY4MmE3MTJmNTY4MmZiZDAzM2M4MTljMmVmNjRiZDljM2VjYjI5MjdlM2U), where you can tell us more about how you use EmbedIO and get more immediate support, and to try out [EmbedIO version 3](https://www.nuget.org/packages/EmbedIO/3.0.0-preview4), which so far seems rather stable and brings some interesting improvements overall. Porting an application to version 3 may take anything from 10 minutes to a couple hours, depending on which modules you use, but is almost certainly worth the effort, especially if you have a lot of Web API controllers (that now need much less boilerplate code), static files (now faster and better cached), or custom modules (lots of support APIs!)

**Comment by Genteure** [comment]
> Otherwise, when a faulted Task is garbage collected your program will be terminated.

That is not the case anymore from .NET Framework 4.5

https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskscheduler.unobservedtaskexception

>To make it easier for developers to write asynchronous code based on tasks, the .NET Framework 4.5 changes the default exception behavior for unobserved exceptions. Although unobserved exceptions still raise the UnobservedTaskException exception, the process does not terminate by default. Instead, the exception is handled by the runtime after the event is raised, regardless of whether an event handler observes the exception. This behavior can be configured. Starting with the .NET Framework 4.5, you can use the <ThrowUnobservedTaskExceptions> configuration element to revert to the behavior of the .NET Framework 4 and terminate the process

**Comment by rdeago** [comment]
@Genteure you're right, thanks for the heads-up!
