### ISSUE TITLE
how to write a controller for text/event-stream

### ISSUE THREAD

**Issue by kooboo-binbin** [unosquare/embedio#317]
how to write a controller for text/event-stream

**Comment by rdeago** [comment]
If you are talking about Server Sent Events, I'm no expert, but it should be nothing special: just set the content type of the response to `text/event-stream`, then every time you send some data append an extra line feed and flush the response stream.

This quick (and admittedly untested) example will send the number 42 as data every 2 seconds, until you stop the server. It's written for EmbedIO v3.0, which is currently in preview but I'm already using successfully in production.
```C#
server.OnGet("/answer", async (ctx, path, ct) => {
    ctx.Response.ContextType = "text/event-stream";
    using (var writer = ctx.OpenResponseText())
    {
        while (!ct.IsCancellationRequested)
        {
            writer.WriteLine("data: 42");
            writer.WriteLine();
            writer.Flush();
            await Task.Delay(2000, ct);
        }
    }

    return true;
});
```

The same for EmbedIO v2 would be:
```C#
server.RegisterModule(new ActionModule("/answer", HttpVerbs.Get, async (ctx, ct) => {
    ctx.Response.ContextType = "text/event-stream";
    using (var writer new StreamWriter(ctx.Response.OutputStream, Encoding.UTF8, 1024, true)))
    {
        while (!ct.IsCancellationRequested)
        {
            writer.WriteLine("data: 42");
            writer.WriteLine();
            writer.Flush();
            await Task.Delay(2000, ct);
        }
    }

    return true;
}));
```

**Comment by kooboo-binbin** [comment]
@rdeago thank you that is what I need.
one new question. How to check whether the client connection is closed (the browser is closed).

**Comment by rdeago** [comment]
When the client closes the connection, next attempt to send data will throw a `HttpListenerException` that you can catch. This should work regardless of the version of EmbedIO you use.

EmbedIO v3 gives you a somewhat nicer alternative: you can define a callback that will be called when the HTTP context is closed.

Let's say, for example, that we want to implement a counter of how many clients are listening to a given event source.

Here's the updated code for v2:
```C#
private int _connectionCount;

public int ConnectionCount => _connectionCount;

server.RegisterModule(new ActionModule("/answer", HttpVerbs.Get, async (ctx, ct) => {
    Interlocked.Increment(ref _connectionCount);
    try
    {
        ctx.Response.ContextType = "text/event-stream";
        using (var writer new StreamWriter(ctx.Response.OutputStream, Encoding.UTF8, 1024, true)))
        {
            while (!ct.IsCancellationRequested)
            {
                writer.WriteLine("data: 42");
                writer.WriteLine();
                writer.Flush();
                await Task.Delay(2000, ct);
            }
        }
    }
    catch (HttpListenerException)
    {
        // Whatever else you need to do when the client closes the connection.
    }
    finally
    {
        Interlocked.Decrement(ref _connectionCount);
    }

    return true;
}));
```

You can do the same in v3, or you can do this:
```C#
private int _connectionCount;

public int ConnectionCount => _connectionCount;

void OnContextClosed(IHttpContext context)
{
    Interlocked.Decrement(ref _connectionCount);
    // Whatever else you need to do when the context is closed.
    // Note that in this case you cannot be sure that the cause
    // was a HttpListenerConnection.
}

server.OnGet("/answer", async (ctx, path, ct) => {
    Interlocked.Increment(ref _connectionCount);
    ctx.OnClose(OnContextClosed);
    ctx.Response.ContextType = "text/event-stream";
    using (var writer = ctx.OpenResponseText())
    {
        while (!ct.IsCancellationRequested)
        {
            writer.WriteLine("data: 42");
            writer.WriteLine();
            writer.Flush();
            await Task.Delay(2000, ct);
        }
    }

    return true;
});
```

Why don't you [join EmbedIO's Slack workspace](https://join.slack.com/t/embedio/shared_invite/enQtNjcwMjgyNDk4NzUzLWQ4YTE2MDQ2MWRhZGIyMTRmNTU0YmY4MmE3MTJmNTY4MmZiZDAzM2M4MTljMmVmNjRiZDljM2VjYjI5MjdlM2U) so you can tell us more about your use case? Knowing how EmbedIO is used can help us understand better where to concentrate future development efforts.

**Comment by kooboo-binbin** [comment]
Thank you.
