### ISSUE TITLE
FileModule.Dispose exception

### ISSUE THREAD

**Issue by AbeniMatteo** [unosquare/embedio#319]
**Describe the bug**
Disposing a faulted or not started WebServer that has a FileModule attached throws `System.ArgumentException`.

**Cause**
The exception is thrown [here](https://github.com/unosquare/embedio/blob/4f21893dac043c2875fed1c00b76830649071da3/src/EmbedIO/Files/FileModule.cs#L262) probably because `_cacheSection` is not yet initialized.

**To Reproduce**
Run the following snippet:
```cs
namespace Repro
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Threading;
    using EmbedIO;
    using EmbedIO.Files;

    class Program
    {
        static void Main()
        {
            var server = new WebServer(12345);
            server.WithModule(new FileModule("/", new MyFileProvider()));
            //server.RunAsync();

            server.Dispose();
        }

        class MyFileProvider : IFileProvider
        {
            public bool IsImmutable => false;

            public event Action<string> ResourceChanged;

            public IEnumerable<MappedResourceInfo> GetDirectoryEntries(string path, IMimeTypeProvider mimeTypeProvider)
                => throw new NotImplementedException();

            public MappedResourceInfo MapUrlPath(string urlPath, IMimeTypeProvider mimeTypeProvider)
                => throw new NotImplementedException();

            public Stream OpenFile(string path)
                => throw new NotImplementedException();

            public void Start(CancellationToken cancellationToken)
                => throw new NotImplementedException();
        }
    }
}
```

**Expected behavior**
No exception.

**Version**
3.0.0-preview7

**Comment by rdeago** [comment]
Another good catch, @AbeniMatteo, thanks a lot!

The issue has been fixed in https://github.com/unosquare/embedio/commit/09610482197af973285b3e30bbe628853f58e98d.

**Comment by geoperez** [comment]
Also, you can check the nuget preview 8.

**Comment by AbeniMatteo** [comment]
Preview 8 contains a bug fixed with [this commit](https://github.com/unosquare/embedio/commit/3216ee2ac6ad95db91999f98d0e3be6079803e7c), i'll test with the next preview. Thanks.

**Comment by geoperez** [comment]
Preview 9 is ready.

**Comment by AbeniMatteo** [comment]
Works fine now, thank you.
