### ISSUE TITLE
Update samples with new CDN and RegEx Routing Strategy

### ISSUE THREAD

**Issue by mariodivece** [unosquare/embedio#32]
Once you complete the RegEx routing strategy, update the samples' CDN and update the handlers to show usage of RegEx routing strategy.

**Comment by geoperez** [comment]
@mariodivece  the documentation and samples were updated. Let me know if I need to change anything else.

**Comment by mariodivece** [comment]
I need to make a few minor corrections. Looks good though. Thanks @geoperez
