### ISSUE TITLE
Question: WebSocket server setup for device to device comms

### ISSUE THREAD

**Issue by InquisitorJax** [unosquare/embedio#323]
I'm trying to setup mobile device to device communication via websockets.

When connecting via ClientWebSocket - the url it expects is ws://* - but when specifying the host server url, that is not valid, and it will only accept http://*.
ie: Host server will only accept http*, and ClientWebSocket will only accept ws*

Is there something I'm missing here?
Is it possible to connect using System.Net.WebSockets.ClientWebsocket to a WebServer?

server code setup:
```
			_server = new WebServer(address);

			_server.RegisterModule(new WebSocketsModule());
			_server.StateChanged += Server_StateChanged;

			_server.Module<WebSocketsModule>().RegisterWebSocketsServer<HalWebSocketsServer>("/comms");

			await _server.RunAsync();

```

**Comment by rdeago** [comment]
You can use `http://*` as your WebServer URL prefix, it will respond to `ws://*` requests just fine.

The `ws` scheme tells the client to make a WebSocket request. As per [the WebSocket protocol](https://tools.ietf.org/html/rfc6455), such a request starts as a HTTP request and the connection is then "switched" to WebSocket. The server is a HTTP server, the request (at least in its initial phase, called "handshaking") is a HTTP request; therefore, there is no need to use the `ws` scheme on the server side.

**Comment by InquisitorJax** [comment]
thanks @rdeago ... good to know that's not the cause of my connection issues. I'm new to this kind of p2p protocol comms :P
