### ISSUE TITLE
Empty response on publicly available IP with port forwarding

### ISSUE THREAD

**Issue by shdwp** [unosquare/embedio#325]
**Describe the bug**
When accessing web server by router IP with port forwarding server responds with Content-Length: 0. It's the server, since I can see `server: embedio` in the headers. Accessing the same URL by local IP seems to work fine. 

Nothing at all gets printed in the stdout if you access it trough public IP (I've enabled the debug output as well).

Server is on windows, and binding the same port to apache works fine.

**To Reproduce**
1. Start the server as in basic example
2. Forward its port through the router
3. Attempt to access it via the internet

**Environment**
OS: Windows 
embedio version: 2.9.2

**Comment by rdeago** [comment]
Hello @shdwp, thanks for your input.

Which version of EmbedIO are you referring to?

**Comment by shdwp** [comment]
2.9.2 from nuget.

**Comment by UserR00T** [comment]
Still an issue in version 3.0.2. When adding the public IPv4 to the prefix list by typing ``WithUrlPrefix("publicip")`` [the application instantly closes.](https://i.imgur.com/kilYNxo.png)

What is peculiar though is that if I set my url in ``WithUrlPrefix`` to ``127.0.0.1``, localhost and direct internal ip (in this case ``192.168.1.38``) both respond with an empty 200 OK repsonse which includes a ``Server: embedio/3.0`` header, just like with the public ip.)

Did a clean install of this package along with the example code, and still managed to invoke said behaviour.

**Comment by UserR00T** [comment]
Using ``http://+:80/`` resolved the issue. Thank you!
