### ISSUE TITLE
Disposing not-listening server will close the listener socket of another server

### ISSUE THREAD

**Issue by AbeniMatteo** [unosquare/embedio#332]
**Possible cause**
Disposing an invalid server that shares the same prefix with another (it's invalid because of that) will close  [here](https://github.com/unosquare/embedio/blob/d5d1295f5dc86f5ecfca22edf24b486a8e205409/src/EmbedIO/Net/Internal/EndPointListener.cs#L64-L78) the listener socket of the other server.

**To Reproduce**
Run the following snippet:
```cs
namespace Repro
{
    using System;
    using System.Threading;
    using EmbedIO;

    class Program
    {
        [STAThread]
        static void Main()
        {
            var server1 = new WebServer(12345);
            server1.Start();

            var server2 = new WebServer(12345);
            server2.Start();

            if (server2.State != WebServerState.Listening)
                server2.Dispose();

            while (true)
                Thread.Sleep(1);
        }
    }
}
```

**Expected behavior**
[http://localhost:12345/](http://localhost:12345/) responding with 404 (no modules are attached but the server is running fine)

**Version**
3.0.0-rc003

**Comment by rdeago** [comment]
This looks like a long-standing bug in EmbedIO's `HttpListener`, probably coming from the version of Mono it was copied from.

The Mono team has since scraped that code in favor of the CoreFX implementation. I can't help but strongly agree with that decision every time I see the code. 🙈

IMHO, more than a bug to fix, this is just one more reason to replace the EmbedIO.Net classes with something more modern (not to mention decently written).

**Comment by geoperez** [comment]
Tested with the latest version, same behavior. Current output:

```
12:10:55.676 INF >> [WebServer] Web server prefix 'http://*:12345/' added.
 12:10:55.556 INF >> [WebServer] Running HTTPListener: Unosquare HTTP Listener
 12:10:56.094 INF >> [WebServer] Started HTTP Listener
 12:10:56.137 INF >> [WebServer] Running HTTPListener: Unosquare HTTP Listener
 12:10:56.137 INF >> [WebServer] Web server prefix 'http://*:12345/' added.
 12:10:56.306 INF >> [WebServer] Cleaning up
 12:10:56.389 INF >> [WebServer] Listener closed.
```

**Comment by geoperez** [comment]
I changed the logic in `EndPointManager.AddListener` to log the exception.
