### ISSUE TITLE
Session cookies are not recognized when CookiePath is set

### ISSUE THREAD

**Issue by azixMcAze** [unosquare/embedio#338]
**Describe the bug**
Hello, I am using EmbedIO v3.
When `LocalSessionManager` get or creates a new cookie in `Create()`, it gets the request's session cookie from the request cookies and checks if it is valid in `IsSessionCookie()`:

```csharp
        private bool IsSessionCookie(Cookie cookie)
            => cookie.Name.Equals(CookieName, StringComparison.OrdinalIgnoreCase)
             && cookie.Path.Equals(CookiePath, StringComparison.Ordinal)
             && string.IsNullOrEmpty(cookie.Domain)
             && !cookie.Expired;
```
This codes checks that the cookie's path is equal to its `LocalSessionManager.CookiePath` property.

However it seems tha the cookie's path is always empy in HTTP requests as browsers does not transmit this property in the `Cookie` HTTP header. Chrome and firefox does not appear to do so and https://developer.mozilla.org/fr/docs/Web/HTTP/Headers/Cookie does not describe a syntax for passing the path.

This cause `LocalSessionManager` to always create new session cookies even if an existing one is sent in the request when `CookiePath` is set (for example to `"/"`).
I don't know if the `Domain` check could also cause some troubles.

**Expected behavior**
I expect that the session cookie sent in the request is recognized, with or without `CookiePath` set.

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6
 - Browser Chrome 75 and Firefox 68
 - Version git branch v3.0 (d7852e80)

**Comment by rdeago** [comment]
Hello @azixMcAze, thanks for the heads-up!

I'm fixing this in next commit on the v3.0 branch. Stay tuned! In the meantime, you may also [join EmbedIO's Slack workspace](https://join.slack.com/t/embedio/shared_invite/enQtNjcwMjgyNDk4NzUzLWQ4YTE2MDQ2MWRhZGIyMTRmNTU0YmY4MmE3MTJmNTY4MmZiZDAzM2M4MTljMmVmNjRiZDljM2VjYjI5MjdlM2U). 😉

**Comment by rdeago** [comment]
@azixMcAze can you confirm that the bug is fixed?

**Comment by azixMcAze** [comment]
The bug is fixed, thank you!
