### ISSUE TITLE
Xamarin.Forms 404 when loading webpage

### ISSUE THREAD

**Issue by mnxamdev** [unosquare/embedio#341]
I'm currently working in iOS on this. I'm trying to setup a project to load up a webpage with javascript. My initial iteration without ebmbedio just loads up a local file in a web view. I installed EmbedIO and created an API controller to return back a binary to the page from that EmbedIO endpoint, the call was made via JavaScript so loading of JavaScript resources and calling the ending from JavaScript works fine. I know it works because I could step through and see the endpoint was hit, except I got a security exception on the JavaScript side:
"Failed to load resource: Origin null is not allowed by Access-Control-Allow-Origin."

It seems since I'm loading the local HTML in the WKWebView it is using the file:// protocol to load up the HTML and calling JavaScript to an endpoint from file:// is not allow. If someone has a solution for that I'd like to hear it (how does Cordova handle this?). 

So, what I'm thinking is serving up the HTML from EmbedIO to get around the origin issue but I'm getting a 404. What am I missing.

```C#
var server = new WebServer("http://*:8080");
            server.RegisterModule(new WebApiModule());
            server.RegisterModule(new CorsModule("*", "*", "*"));
            server.RegisterModule(new LocalSessionModule());
            server.RegisterModule(new StaticFilesModule(Environment.GetFolderPath(Environment.SpecialFolder.Resources), false));
            server.Module<StaticFilesModule>().UseRamCache = true;
            server.Module<StaticFilesModule>().DefaultExtension = ".html";
            server.Module<StaticFilesModule>().DefaultDocument = "index.html";
            server.Module<WebApiModule>().RegisterController<MyNameSpace.ReturnBinaryController>();
            server.RunAsync();
```

In my web view renderer I have:
```C#
_wkWebView.LoadRequest(new NSUrlRequest(new NSUrl("http://127.0.0.1:8080/WWW/MyPage.html")));
```

My HTML file along with other JS and image resources are in:
```
My.EmbedIO.Project/Resources/WWW
```

I need help and haven't seen much posted about what I'm trying to do on other forums. If I'm not in the right space for support, please let me know where I should go. I appreciate any help you can offer.

**Comment by rdeago** [comment]
Hello @mnxamdev, thanks for your input.

You have in fact come to the right place for support on EmbedIO. Although no current EmbedIO contributor is an iOS developer, I'll try to do my best (and I can vouch for the others to do the same).

There are two possible causes for the 404 error you are seeing:
* either `StaticFilesModule` does not find `MyPage.html`, maybe because of some permission issue,
* or some other module is "eating" the request, `WebApiModule` being the strongest candidate.

I think a different module registration order is worth a try:
```C#
var server = new WebServer("http://*:8080");
            server.RegisterModule(new LocalSessionModule());
            server.RegisterModule(new CorsModule("*", "*", "*"));
            server.RegisterModule(new StaticFilesModule(Environment.GetFolderPath(Environment.SpecialFolder.Resources), false));
            server.RegisterModule(new WebApiModule());
            server.Module<StaticFilesModule>().UseRamCache = true;
            server.Module<StaticFilesModule>().DefaultExtension = ".html";
            server.Module<StaticFilesModule>().DefaultDocument = "index.html";
            server.Module<WebApiModule>().RegisterController<MyNameSpace.ReturnBinaryController>();
            server.RunAsync();
```

Please let us know whether the problem disappears or remains, or if some other problem appears, when using the above code to initialize your web server.

**Comment by mnxamdev** [comment]
Thanks for the reply. I'm still getting a 404.

**Comment by mnxamdev** [comment]
The following now gives me a blank page. I commented out all modules except StaticFileModule and moved everything into a WWW folder under the root of the project. I also changed MyPage.html to index.html and now point my WebView to http://127.0.0.1:8080/ and changed the build action on index.html to BundledResource, EmbeddedResource, and Content. As you can see below, I changed the initialization to point to LocalApplicationData/WWW. I even turned on directory browsing.

`
var server = new WebServer("http://*:8080");
server.RegisterModule(new StaticFilesModule(
                Path.Combine(
                    Environment.GetFolderPath(
                        Environment.SpecialFolder.LocalApplicationData), "WWW"), true));
server.Module<StaticFilesModule>().UseRamCache = true;
server.Module<StaticFilesModule>().DefaultExtension = ".html";
server.Module<StaticFilesModule>().DefaultDocument = "index.html";
`

**Comment by rdeago** [comment]
Forgive me for giving it for granted, but the build action should be Content for files you want to include in your application package. [Microsoft documentation](https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/file-system#special-considerations) is quite explicit in this regard.

A blank page, although not the desired result, is not a 404 either, so let's try and fix things from here. We can add back the other modules later.

First of all, maybe just out of my ignorance about ioS development, I'd like to be sure that `index.html` is where it should be. What happens if you set `DefaultDocument` to `null` _and_ enable directory browsing? You should see your `index.html` listed, along with any other file and/or folder you included as Content under `WWW`.

**Comment by mnxamdev** [comment]
I set DefaultDocument to null, turned on DirectoryBrowsing, and made sure all files in the folder and subfolders are set Build Action to Content. I still get a blank page.

**Comment by rdeago** [comment]
Maybe, just maybe, I've found out why your `WKWebView` turns out empty.

Take a look at [this topic on Xamarin forums](https://forums.xamarin.com/discussion/103689/after-ios-11-upgrade-wkwebview-does-not-load-my-website). Your problem could be the same, or very similar.

**Comment by mnxamdev** [comment]
Thanks for the reply and the links!  I created a policy decision handler per the post to allow but that didn't fix it.  I already had Arbitrary Loads set but can look into the other options.

**Comment by rdeago** [comment]
Maybe it's just me, and msybe it's completely unrelated, but why do the last two items appear to belong to the `NSExceptionDomains` dictionary? Shouldn't they belong to `NSAppTransportSecurity` instead?

Other than that, I must admin I'm out of ideas. Did you try using CURL as a client and see exactly what that blank page is made of, headers and all?

**Comment by AbeniMatteo** [comment]
It is a 404 or 500?

If it is 500 and you're running Visual Studio >=16.2 maybe you have this problem #336.

**Comment by mnxamdev** [comment]
@rdeago Those exceptions should be part of the domain but there is a mistake in my setup there in that the 127.0.0.1 entry should be a dictionary with those following being items in that dictionary. 
https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/ats-images/ats01.png#lightbox

I'll respond back with the header information like you asked but I inspected the page using Safari developer tools and it is actually the "about:blank" from what I recall.

@AbeniMatteo thanks for chiming in, I'll take a look at that. I'm on VS Mac 2019. I'm on 8.3 Preview. (8.3 build 1290). I recall trying this on a device and not just simulator with same results.
