### ISSUE TITLE
Handle file requests

### ISSUE THREAD

**Issue by etheaven** [unosquare/embedio#342]
**Is your feature request related to a problem? Please describe.**
I got very frustrated when I tried receiving a `<input id="file-input" type="file" capture="camera"/>`   
I saw this https://github.com/unosquare/embedio/issues/60#issuecomment-273472764 but my `HttpContext.Request.InputStream` doesn't have any length.

**Describe the solution you'd like**
Be able to actually get a stream of the file

**Describe alternatives you've considered**
`InputStream` having actual data

**Comment by rdeago** [comment]
Hello @etheaven, thanks for your input.

I'm not entirely sure what you mean by `HttpContext.Request.InputStream` not having any length. As far as I know, `MultipartFormDataParser` should not need to get the input stream's length, as it parses the stream while reading it.

Knowing the version of EmbedIO you are using could also be of help, in case a bug is discovered while investigating this issue.
