### ISSUE TITLE
Disable Logging in 3.*

### ISSUE THREAD

**Issue by DominikPf** [unosquare/embedio#346]
How to disable/change the Log-Level of EmbedIO in 3.*?

**Swan.Terminal.Settings.DisplayLoggingMessageType** does not exist anmore.

Is this still the correct way for 3.* ?
I looked at the WebServer Object but i could not find any other Option.
Currently i am using the fresh 3.0.1 release :)

The Docs seems to be the old ones from 2.*:
https://github.com/unosquare/embedio/wiki/Cookbook#how-to-turn-off-logging

**Comment by geoperez** [comment]
I need to update that wiki page. But I can explain to you:

We moved the logging to a new class `Logger`. You can Register or Unregister log targets, by default the ConsoleLogger is enabled in the startup. You can Unregister using:

`Logger.UnregisterLogger<ConsoleLogger>();`

**Comment by DominikPf** [comment]
@geoperez 
Thank you very much for this very quick Answer.
That fixed my Problem. 

Keep going with this Amazing Project ;)
