### ISSUE TITLE
support nullable parameter in the regexp engine

### ISSUE THREAD

**Issue by bufferUnderrun** [unosquare/embedio#35]
Hi,

my goal is to support optional parameter by the new regexp routing engine. With this 
[patch](https://github.com/unosquare/embedio/files/220643/support-nullable-type-parameter-in-regexp-engine.txt), you can now declare a nullable parameter :
```C#
            [WebApiHandler(HttpVerbs.Get, RelativePath + "people/{id}")]
            public bool GetPeople(WebServer server, HttpListenerContext context, int? id)
            {
                // when GET /people/, id will be forced to null and not throwing exception
                if (id == null) {
                    return context.JsonResponse(People.All());
                }

                // else use the actual parsing and cast the int to id.
                else  {
                    return context.JsonResponse(People.FirstOrDefault(p => p.Key == id));
                }
            }
```
It works but has some limits : 

1. when GET /people the regexp doesn't match the right url due to the fact that `NormalizeRegexPath()` doesn't know if a param is optional (nullable) and slash need to be ignored.. 
2. only the last nullable parameter is supported, same case as (1).

**Comment by mariodivece** [comment]
We'll need to analyze how the handling of multiple nullable parameters can be properly implemented. 
Here's a related question: http://stackoverflow.com/questions/26231961/webapi-routing-to-a-function-with-multiple-optional-parameters
And here's a link to how it's done in Web API 2:
http://www.asp.net/web-api/overview/formats-and-model-binding/parameter-binding-in-aspnet-web-api

**Comment by bufferUnderrun** [comment]
agree, i'll follow your pointers

**Comment by geoperez** [comment]
My last commit (https://github.com/unosquare/embedio/commit/49cf0899d4c21303c77ac803367ebcedd464c8eb) includes a way to add ONE optional parameter.

**Comment by mariodivece** [comment]
One optional non query string param is indeed sufficient and the only thing that makes sense.
