### ISSUE TITLE
FileSystemProvider can't handle escaped strings 

### ISSUE THREAD

**Issue by 1c3f0x84** [unosquare/embedio#352]
**Describe the bug**
FileSystemProvider can't handle escaped strings. 

**To Reproduce**
1. Create a WebServer with WithStaticFolder
2. Navigate to a folder with a whitespace in it

**Expected behavior**
To load the index.html in the folder which has a whitespace in it

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 3.0.2

**How to FIX**
Add this line 
urlPath = Uri.UnescapeDataString(urlPath);
in the Method MapUrlPath(...) in the try block in the file FileSystemProvider.cs

Wanted to do it myself but didn't have any rights to push a branch or PR

**Comment by 1c3f0x84** [comment]
@geoperez thank you for the fast responce and thx for the instruction. I will remember it.

**Comment by geoperez** [comment]
The new nuget was published, you can check version 3.0.4!
