### ISSUE TITLE
RegisterModule(new CorsModule()) or EnableCors() for WebServer is not working in v2.2.9

### ISSUE THREAD

**Issue by NvVijayakumara** [unosquare/embedio#354]
Hi, 

I've successfully created 2 server, in which
1. Serve static file, with http://localhost:6969/
2. Server folder as website that contains javascript & html files, with http://localhost:9696/

Html page in 2nd server (i.e *9696) is trying to access file inside 1st server(i.e *6969), but browser is showing error as below-
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:6969/master.mp4. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

Even I tried by enabling CORS, but still it's not working.

my sample code is -
// creating 2nd server
using (var server = new WebServer("http://localhost:9696/"))
{
	server.RegisterModule(new StaticFilesModule(Application.StartupPath + @"\secondwebsite\"));
	server.RegisterModule(new CorsModule("*", "*", "*"));
	server.EnableCors("*", "*", "*");
	server.RunAsync();
	serverWorker2.ReportProgress(100);
	while (serverWorker2.CancellationPending == false)
	{
		System.Threading.Thread.Sleep(100);
	}
}

I used older version (2.2.9) of this library in order to support my app that targets .net framework 4.5.2

For any sugession, thank you..

**Comment by geoperez** [comment]
Instead of white space use CORS wildcard *

**Comment by NvVijayakumara** [comment]
Yeah.. I use that too., but still its not working

**Comment by geoperez** [comment]
One thing I forgot to tell you, you need to include the CORS module before any other module. Also, try the extension method with no args:
`
var server = new WebServer();
server.EnableCors();
// here continue with the StaticFilesModule
`

The order of the modules is important.

**Comment by NvVijayakumara** [comment]
Awesome, it worked.. thanks @geoperez
