### ISSUE TITLE
Incorrect handling when URL does not contain a trailing slash.

### ISSUE THREAD

**Issue by waynebloss** [unosquare/embedio#36]
I configured a basic static server to test EmbedIO and I found that certain pages would not load depending on if the URL contained a trailing slash or not.

For instance, assume that I'm serving files from `C:\temp\` and that `C:\temp\xyz\` is a subfolder that exists with an `index.html` file inside of it.

If I have a link that points to `href="/xyz/"` the page loads. However, if the link points to `href="/xyz"` then a `404` error is returned.

**Comment by geoperez** [comment]
Issue resolved in new Nuget (version 1.0.20). Let me know if you get any issue.

I updated the unit tests to include this scenario.

**Comment by waynebloss** [comment]
This seems to work perfectly now. Thank you very much!
