### ISSUE TITLE
Incorrect http listener modes for isssue 355 tests

### ISSUE THREAD

**Issue by AbeniMatteo** [unosquare/embedio#362]
Http listener test modes specified [here](https://github.com/unosquare/embedio/blob/master/test/EmbedIO.Tests/Issues/Issue355_ContentResponseLength.cs#L14) are duplicated and not even used for `ActionModuleWithHeaderCollection_Handle_ContentLengthProperly` (same for `DefaultUrl` field).

**Comment by rdeago** [comment]
Hello @AbeniMatteo, thanks for the heads-up.

PR incoming!

**Comment by geoperez** [comment]
Can I close this issue?

**Comment by rdeago** [comment]
> Can I close this issue?

Looks like our faithful bot already saw to it. 😄
