### ISSUE TITLE
Strong Name the nuget assembly

### ISSUE THREAD

**Issue by 1F6B66** [unosquare/embedio#363]
Can the nuget package be updated to contain a strong named assembly, please? My main code needs to be strong named and therefore this is a blocker for me to use the embedio lib.

With version 1.0.14 the embedio assembly got stronlgy named but the latest version 3.0.5 isn't.

Related Issue: [25](https://github.com/unosquare/embedio/issues/25)

**Comment by geoperez** [comment]
Sorry for the delay, I'm curious why do you need a strong name? I was reading a little about strong name in .net core and they don't recommend it.

**Comment by 1F6B66** [comment]
I want to use the assembly from the GAC

**Comment by NvVijayakumara** [comment]
Use this GUI tool to sign [tool](https://brutaldev.com/post/net-assembly-strong-name-signer).

**Comment by geoperez** [comment]
I was checking this, but I'll need to add a strong name to SWAN first.

**Comment by geoperez** [comment]
I just release SWAN with strong name. Today, I'll release EmbedIO too.

**Comment by geoperez** [comment]
Done! You can check version 3.0.7!

**Comment by 1F6B66** [comment]
Thank you, great!
