### ISSUE TITLE
Can't install the package!

### ISSUE THREAD

**Issue by mohShah96** [unosquare/embedio#382]
Hi!
I can't install the package from nuget.
The error is:
Could not install package 'EmbedIO 3.0.7'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0

**Comment by rdeago** [comment]
Hello @mohShah96, thanks for using EmbedIO. Well, for trying, at least.

EmbedIO is a .NET Standard 2.0 library; therefore, when targeting .NET Framework, you should target at least .NET Framework v4.6.1 for NuGet to consider the package compatible with your project.

My advice, however, is to target at least .NET Framework 4.7.1, unless you have a specific requirement for an older version.
