### ISSUE TITLE
Github readme does not match available Nuget packages

### ISSUE THREAD

**Issue by chillwinston** [unosquare/embedio#384]
The Github readme page that includes examples does not match the available Nuget packages (3.0.8).  There's not even a tag for 3.0.8 in the Git repo, but there is for 3.0.6.

The project is great and worthwhile, but is frankly confusing for those of us that just want to install and use it as quickly as possible.

Can I suggest that you recompile, tag and re-release a nuget package that matches the readme, and / or change the readme so that it matches the available nuget package.

In essence - downloading a nuget package then trying to use the example code fails, and it means that people need to spend a great deal more time using the code - which is why you've created the project in the first instance: ease of use.

**Comment by geoperez** [comment]
I just updated the missing tag 3.0.8. Where do you see the version 3.0.6 in the README file?

**Comment by chillwinston** [comment]
Thanks Geovanni - I've found the error and it's at my side.  The Route
attribute that is being referred to is one from another package.

Oddly - the "WithController" method didn't emit any error that the
WebApiController was of the wrong type or that there wasn't any correctly
attributed methods, so it failed silently.

That being said - it now works, which is phenomenal.   Many thanks for your
swift response - the investigation my side to respond to you found the
issue.  This issue can now be closed.

**Comment by geoperez** [comment]
> Oddly - the "WithController" method didn't emit any error that the
WebApiController was of the wrong type or that there wasn't any correctly
attributed methods, so it failed silently.

@rdeago do you think we should fix this in another issue?

**Comment by rdeago** [comment]
I'd say this is the same as #351, a fix to which is long overdue. I'll be on it on Monday.
