### ISSUE TITLE
HttpRequest.ContentLength64 incorrectly returns 0

### ISSUE THREAD

**Issue by azixMcAze** [unosquare/embedio#389]
**Describe the bug**
With a request containing data in the body, `request.ContentLength64` returns 0 whereas `request.Headers[HttpHeaderNames.ContentLength]` returns a non zero number.

It seems that in the request that exhibits the problem, the content length header is in small caps (`content-length`) instead of being capitalized like in `HttpHeaderNames.ContentLength` (`Content-Length`)

I suppose that that the problem is that `NameValueCollectionExtensions.ContainsKey()` is case-sensitive  whereas `NameValueCollection []` is case-insensitive.

**Expected behavior**
I expect `request.ContentLength64` and `request.Headers[HttpHeaderNames.ContentLength]` to return the same value

Reproduced in EmbedIO 3.0.5 to 3.0.8 but not in 3.0.4

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6 
 - Browser: Firefox
 - Version: 69.0.1

**Comment by geoperez** [comment]
I'll take a look, thanks for reporting this issue.

**Comment by geoperez** [comment]
I'm not able to reproduce the issue. Can you check my commit? 

https://github.com/unosquare/embedio/commit/94cee1104f8033c91b64acf5bd43115603b795ff

**Comment by azixMcAze** [comment]
Hi, I check your commit and `HttpClient` sends capitalized http headers.

I checked with [mitmproxy](https://mitmproxy.org/) and Firefox also sends capitalized HTTP headers.

However I using a React web app making `fetch` web requests using a polyfill ([`whatwg-fetch`](https://github.com/github/fetch)) through a proxy (node's `http-proxy-middleware`) when using a [create-react-app](https://github.com/facebook/create-react-app)'s development test server (`yarn run react-scripts start`)

It looks like that it is `http-proxy-middleware` that converts the HTTP headers to lowercase.

It is not a setup that is easy to reproduce, let alone include in a test suite

**Comment by azixMcAze** [comment]
I created a script for [mitmproxy](https://mitmproxy.org/) that will convert all the headers to lowercase :
```python
import typing

from mitmproxy import ctx
from mitmproxy.http import HTTPFlow
from mitmproxy.net.http.headers import Headers


class LowercaseHeaders:
    def requestheaders(self, flow: HTTPFlow):
        headers = flow.request.headers
        new_headers = Headers((k.lower().encode(), v.encode()) for (k, v) in headers.items())
        flow.request.headers = new_headers

addons = [
    LowercaseHeaders()
]
```

You can launch mitmproxy to create a reverse proxy and use this script with this command line: `mitmproxy --mode reverse:http://localhost:1234/ -p 1235 -s lowercase.py`

In your test, listen on `http://localhost:1234/` but send requests to `http://localhost:1235/`.

Using this, `ActionModuleReadsKey_Handle_ContentLengthProperly` succeeds but `ActionModuleReadsProperty_Handle_ContentLengthProperly` fails with this error:

      String lengths are both 1. Strings differ at index 0.
      Expected: "7"
      But was:  "0"
      -----------^

**Comment by geoperez** [comment]
I found the issue, `ContainsKey` is not case insensitive as the index accessor in `NameValueCollection`. This is really odd.

Can you test my branch again? 

The only issue here is that I need a better unit test without the proxy.  But I can keep this for later and release a nuget if your test is passing.

**Comment by azixMcAze** [comment]
The test is now passing.
Before using a proxy, I tried to make `HttpClient` send lowercase HTTP headers by crafting a `HttpRequestMessage`, but I could not make it work.
I am not sure if it is possible and if this is related: https://stackoverflow.com/a/46575625

**Comment by geoperez** [comment]
OK. I'll merge this change and release a new nuget.

**Comment by geoperez** [comment]
New nuget version v3.1.1
