### ISSUE TITLE
How do I map url to static folder?

### ISSUE THREAD

**Issue by DomasM** [unosquare/embedio#39]
If I start web server with url http://+:8000/ and some static folder, say D:\web, request to http://127.0.0.1:8000/ maps to D:\web\Index.html. If I start web server with url http://+:8000/SomeName/, request to http://127.0.0.1:8000/SomeName/ maps to D:\web\SomeName\Index.html. How can I configure server that url part which is supplied in constructor is not included in static file path? I.e. If I start webserver on http://+:8000/SomeName/ and static folder is D:\web, request to http://+:8000/SomeName/ would map to D:\web\index.html

**Comment by geoperez** [comment]
Hello @DomasM, but at your example the http://+:8000/ what would resolve?

**Comment by DomasM** [comment]
It would resolve to nothing, as root address for that server is http://+:8000/SomeName/. I have intentions to have several servers running on same PC in different processes, all on port 80 but on different root addresses. So this server would not handle this request at all, as it is out of scope for him.

**Comment by geoperez** [comment]
OK I think I understand the issue, let me discuss with @mariodivece to see if we could support this feature.

**Comment by DomasM** [comment]
Embedio is built on on HttpListener, which is built on HTTP.sys and it definitely supports multiple clients on the same port and does all the forwarding to the right client, so it should be possible in general.

**Comment by DomasM** [comment]
I'm working on it.

**Comment by DomasM** [comment]
I implemented this behavior, spacing and indentation needs to be fixed. #40

**Comment by geoperez** [comment]
Manual merge at commit https://github.com/unosquare/embedio/commit/bdd7c2b4b2b09e4462f5d43494390b28fafa0b19
