### ISSUE TITLE
Parse url parameters from GET request

### ISSUE THREAD

**Issue by daxcurson** [unosquare/embedio#393]
Hello,

I would like to retrieve the values of parameters from the GET request. E.g., I receive a request:

GET /api?xmltype=saldo_stock&xmlparam=pepe HTTP/1.0

I want to read the values of xmltype and xmlparam parameters. How can I accomplish that?

This is what I have:
            var server = new WebServer(options => options
                  .WithUrlPrefix(url)
                  .WithMode(HttpListenerMode.EmbedIO))
            .WithLocalSessionManager()
            .WithWebApi("/api", module => module
                 .WithController<XmlController>());

And XmlController:

    public class XmlController : WebApiController
    {
        [Route(HttpVerbs.Get, "/api?xmltype=saldo_stock&xmlparam={xmlRecibido}")]
        public Respuesta ConsultaSaldoCliente(string xmlRecibido)
        {
            return new Respuesta();
        }

**Comment by geoperez** [comment]
Hello,

If you want to get data from querystring you can received using the argument attribute `QueryField` (https://unosquare.github.io/embedio/api/EmbedIO.WebApi.QueryFieldAttribute.html). 

Using your example:

```csharp
public class XmlController : WebApiController
{
    [Route(HttpVerbs.Get, "/api")]
    public Respuesta ConsultaSaldoCliente([QueryField] string xmltype, [QueryField] string xmlrecibido)
    {
        return new Respuesta();
    }
}
```

Note that you can't add Querystring to the Route, the Route is only a relative URL.
