### ISSUE TITLE
Delay in responding to requests with EmbedIO listener using ipv6

### ISSUE THREAD

**Issue by rocketraman** [unosquare/embedio#399]
**Describe the bug**
Using the Embed.IO listener with a simple /health controller that simply responds with a String. The request takes 2 seconds to process. Have tried with both httpie and curl on the client side.

With the MS listener, the request processes immediately as expected.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser [e.g. chrome, safari]: N/A
 - Version [e.g. 22]: 10

**Comment by geoperez** [comment]
@rdeago I don't think we should check this issue if we want to proceed with the idea of removing the current Http Listener.

What do you think?

**Comment by rocketraman** [comment]
What will you replace the current listener with, if anything?

**Comment by geoperez** [comment]
This is still on a topic on discussion. Anyway, I will try to check where is consuming time the startup of the webserver.

**Comment by rocketraman** [comment]
Note: its not just webserver startup. *Each* request takes 2s, not just the first one.

**Comment by geoperez** [comment]
😕 I don't have that time on each request. Can you elaborate a little more about your test?

**Comment by rocketraman** [comment]
I did some further testing and you're right... the issue appears to be something specific to my networking setup. When I connect directly to the machine instead of via an ssh tunnel I have, it works without any delay. Closing.

**Comment by rocketraman** [comment]
It is odd that its only the embedio listener and not the MS one though.

**Comment by geoperez** [comment]
So, is this happening when you connect using an ssh tunnel and work with EmbedIO Listener? Any additional information that you can share about the tunnel?

**Comment by rocketraman** [comment]
Nothing complicated. I use putty inside my Windows 10 VM to ssh to a Linux box (my host machine). Putty is configured to create a remote tunnel from port 7071 on the host, to localhost port 7071, which runs my EmbedIO app.

I've tried disabling Windows Firewall and Defender, and neither of these have any effect. When I connect directly to the VM from the host, it works fine. I've even tried capturing the network packets in Windows but am unable to for some reason -- doesn't seem to be as easy as with Linux.

**Comment by rocketraman** [comment]
Ah, its something to do with ipv6. With wireshark, I see a bunch of TCP RSTs happen with the ipv6 loopback, and then finally a fallback to ipv4 which works immediately:

![image](https://user-images.githubusercontent.com/53049/67701064-a2466600-f985-11e9-920d-241948e624be.png)

**Comment by geoperez** [comment]
I see. So the endpoint manager is failing to grab the IPv6 bind with EmbedIO Listener. There is a setting to use IPv6:

``EndPointManager.UseIpv6 = true;``

Can you test it?

**Comment by rocketraman** [comment]
For reference, here is the packet cap with the MS listener, with no additional settings to enable IPV6. Will test that setting above.

![image](https://user-images.githubusercontent.com/53049/67701296-154fdc80-f986-11e9-9d88-d93ed7b38623.png)

**Comment by rocketraman** [comment]
And with `EndPointManager.UseIpv6 = true;` it also works without an issue. Should that be the default?

**Comment by geoperez** [comment]
Maybe, I need to evaluate what could go wrong if a set this setting on by default. Let's keep open this issue while I review it.

**Comment by rocketraman** [comment]
Ok sounds good. BTW, I did confirm ipv4 requests with `EndPointManager.UseIpv6 = true;` do also work without any issue.

**Comment by rdeago** [comment]
@geoperez next minor version could be the right time to change the default for `EndPointManager.UseIpv6` to `true`. Want a PR? :wink:

**Comment by geoperez** [comment]
I think I already did it.

**Comment by rocketraman** [comment]
Closing, thanks.
