### ISSUE TITLE
JSON is sent with Byte-order-mark (BOM) illegally

### ISSUE THREAD

**Issue by rocketraman** [unosquare/embedio#400]
**Describe the bug**
The JSON serializer currently sends JSON with a BOM.

1) BOM is illegal in JSON: https://stackoverflow.com/questions/4990095/json-specification-and-usage-of-bom-charset-encoding

2) .NET StreamWriter adds it by default, can be configured off: https://stackoverflow.com/questions/5266069/streamwriter-and-utf-8-byte-order-marks

3) Looks like this code needs to change: https://github.com/unosquare/embedio/blob/0093d4e843ba266157bd7d166f679a34f75ac4b6/src/EmbedIO/HttpContextExtensions-ResponseStream.cs#L63

**To Reproduce**
1. Send a JSON response
2. Identify that the response contains a BOM, for example with httpie:

```
$ http --body GET :7071/foo | head -c 20 | od -xc
0000000    bbef    7bbf    6322    646f    2265    203a    7022    6664
        357 273 277   {   "   c   o   d   e   "   :       "   p   d   f
```

The initial two bytes are the illegal BOM.

**Expected behavior**
Do not send the BOM for JSON as per the RFCs.

**Comment by geoperez** [comment]
@rocketraman I did the change to remove the BOM in the serializer callback only. Can you check my commit?

**Comment by geoperez** [comment]
My output:

```
geo@GDLA-LT-171107B:~$ http --body GET :8877/api/people/1 | head -c 20 | od -xc
0000000    227b    6449    3a22    3120    222c    614e    656d    3a22
          {   "   I   d   "   :       1   ,   "   N   a   m   e   "   :
0000020    2220    614d
              "   M   a
```

**Comment by rocketraman** [comment]
@geoperez LGTM

**Comment by geoperez** [comment]
OK, I'll release a new nuget over the weekend.

**Comment by geoperez** [comment]
You can check the new nuget version 3.1.2.

**Comment by rdeago** [comment]
@rocketraman can you confirm that this issue is solved?

**Comment by rocketraman** [comment]
Sorry for the late reply. Yes, I can confirm this is fixed now.
