### ISSUE TITLE
Using .WithZipFile and .WithZipFileStream sometimes gives System.IO.IOException

### ISSUE THREAD

**Issue by simohr** [unosquare/embedio#419]
When starting WebServer with a zip file I sometimes get this exception [System.IO.IOException](https://drive.google.com/open?id=1q270BKEDRMrdYUJS8B5hGerXliS-mwZs). Sometimes it works as expected and loads all files. Sometimes I get this exception and sometimes it loads the server but with some files missing (local header corrupted). I am attempting to run the server on a Xamarin.Android app. Any help would be appreciated.

**Comment by geoperez** [comment]
Hi.

Do you have a similar issue with Windows or Linux?

**Comment by simohr** [comment]
I am using Macos Catalina(10.15.2) and Visual Studio for Mac (8.3.11). I would also like to note that when testing the WebServer on a simple Console App it could not open zip files created with the Mac system(Archive Utiliy or Keka), however I suppose this has more to do with System.IO.Compression.

**Comment by rdeago** [comment]
According to the results of [a quick Google search](https://www.google.com/search?q=bug+with+zip+files+created+on+macos) there seem to be some long-standing bugs in MacOS's ZIP archiving utilities. I don't know if this completely explains the problems @simohr is experiencing, but I'd suggest using ZIP files created on a Windows or Linux system, or at least verify that a ZIP file can be correctly extracted on a Windows or Linux system before using it with EmbedIO - or with `System.IO.Compression` at all.

**Comment by rdeago** [comment]
@simohr can you confirm that the problem goes away if all involved Zip files were created on other systems? If so, can we close this issue?

**Comment by simohr** [comment]
Yes, using zip files from other systems works fine.
