### ISSUE TITLE
Large static file cause 'Out Of Memory' error

### ISSUE THREAD

**Issue by egops** [unosquare/embedio#42]
I just use this project for servering a large archive(1.2GB), but it raises an 'Out Of Memory' error.

```
500 - Internal Server Error
Message

Failing module name: Static Files Module
System.OutOfMemoryException

Stack Trace

     System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
     Unosquare.Labs.EmbedIO.Modules.StaticFilesModule.HandleGet(HttpListenerContext context, WebServer server, Boolean sendBuffer)  C:\Unosquare\embedio\Unosquare.Labs.EmbedIO\Modules\StaticFilesModule.cs: 281
     Unosquare.Labs.EmbedIO.Modules.StaticFilesModule.<.ctor>b__37_1(WebServer server, HttpListenerContext context)  C:\Unosquare\embedio\Unosquare.Labs.EmbedIO\Modules\StaticFilesModule.cs: 187
     Unosquare.Labs.EmbedIO.WebServer.ProcessRequest(HttpListenerContext context)  C:\Unosquare\embedio\Unosquare.Labs.EmbedIO\WebServer.cs: 351
```

how can i solve it?

**Comment by mariodivece** [comment]
We will look into implementing large, chunked file transfers this week. Thanks for the good bug report!

**Comment by geoperez** [comment]
@egops are you using HTTP partials? Usually if you don't use partial to chunk your file in multiple small request the entire file is loaded to stream it.

In the unit tests is a sample how to use partials: https://github.com/unosquare/embedio/blob/master/Unosquare.Labs.EmbedIO.Tests/StaticFilesModuleTest.cs#L108

**Comment by egops** [comment]
@geoperez Thank you for your advice, I need the file can be downoaded by any browser, I think this solution is not suit for me.

**Comment by egops** [comment]
@mariodivece OK, thank you for nice work.

**Comment by mariodivece** [comment]
@geoperez see if it would be possible to send out the file from the stream little by little avoiding an oomex please. Partials are not really the solution to this exception.

**Comment by geoperez** [comment]
Sure, let me take a look.

**Comment by mariodivece** [comment]
@egops we continue working on this. it should be ready in a couple of days. @geoperez decided to cleanup the monolithic-looking request handler that includes large file serving

**Comment by geoperez** [comment]
@egops can you check the new Nuget (1.0.23)?

**Comment by egops** [comment]
@geoperez I updated the version, any file can NOT be downloaded by my browsers ( IE and Firefox ) now! 
Logs here when I try to download file:
```
2016-09-12 19:43:08.419	Start of Request d8741d92
2016-09-12 19:43:08.419	Source ::1:54160 - GET: /nvio.npg
2016-09-12 19:43:08.419	Static Files Module::StaticFilesModule.<.ctor>b__37_2
2016-09-12 19:43:08.419	File System: D:/nvio.npg
2016-09-12 19:43:08.601	Result: True
2016-09-12 19:43:08.601	End of Request d8741d92
```
but the browser shows nothing.
Can you check it out?

**Comment by geoperez** [comment]
I didn't see any issue in the unit tests, let me investigate it.

**Comment by mariodivece** [comment]
Guys, egops has the wrong path. See:
GET: /nvio.npg
Shouldn't it be nvio.png?
If not then verify the mime type is in the list.

**Comment by geoperez** [comment]
Mario there's something wrong, I'm checking it.

**Comment by mariodivece** [comment]
Ok. The other strange thing I noticed is that the result was TRUE for the request. Shouldn't it return FALSE when the file is not found?

**Comment by geoperez** [comment]
I found the issue, when the browser request includes Header Compression the stream compressed is not valid. Working on patch.

**Comment by geoperez** [comment]
Hello @egops  can you try with the new nuget?

**Comment by egops** [comment]
@geoperez @mariodivece thank you very  much, I will try it  tomorrow.

**Comment by egops** [comment]
@geoperez @mariodivece it works well now.
