### ISSUE TITLE
.Net 2.0

### ISSUE THREAD

**Issue by michaelrall** [unosquare/embedio#43]
Hello,

is it possible (with reasonable amount of work) to compile embedio against .NET 2.0. 
I would like to use it within Unity3D. 
Or could you tell me which modules I could remove to compile it against .Net 2.0 (I'm just using the "WebApiModule"-Module).

kind regards

**Comment by mariodivece** [comment]
It should be able to compile for .net 2.0 and still use C# 6. Can you give it a shot using VS 2015?

**Comment by mariodivece** [comment]
We tried it on our end and there's just too much stuff that is not available on .net 2.0 like Tasks, cancellation tokens, linq, etc. I am surprised that Unity still uses a .NET runtime form 10+ years ago.

**Comment by michaelrall** [comment]
Allright, thank you for your efforts. I think the problem is, that Unity uses a mix of mono and some custom modifications, so its hard for them to keep pace up with the major-releases.
