### ISSUE TITLE
Address all nullability issues

### ISSUE THREAD

**Issue by rdeago** [unosquare/embedio#440]
All warnings concerning nullability should be addresses before releasing version 4.0.

We could maybe leave imported code in the Net and WebSockets namespaces alone, but all "original" code should be free from nullability inconsistencies.

Of course there should be as many non-nullable public-facing properties and return values as possibile, at least where it makes sense.

**Comment by geoperez** [comment]
You are right, we should not invest time in `Net` namespace.

**Comment by rdeago** [comment]
I believe all nullability issues have been solved in #437. Closing this.
