### ISSUE TITLE
Cannot compile anymore with version 3.4.0

### ISSUE THREAD

**Issue by ormaa** [unosquare/embedio#449]
**Describe the bug**
My server controller which was working fine until today cannot be compiled anymore since I updated the embedIOo to 3.4.0

the error reported is :
[Route(HttpVerbs.Get, "/get/{action}")]

the name HttpVerbs does not exist in the current context.

I cannot see in the doc what need to be replaced.
 

**Expected behavior**
the server controller should compile fine.

**Desktop (please complete the following information):**
MACOS 10.15.2
Visual studio for Mac 8.4.5 build 19

**Comment by rdeago** [comment]
Hello @ormaa, thanks for using EmbedIO!

Version 3.4.0 was inadvertently released with some changes that should have gone into version 4.

I am currently working on a PR that will restore EmbedIO version 3 to a non-breaking state, while keeping most of the additions and corrections that have been done over last weeks.

Until version 3.4.1 is released (which means a few hours from now), and version 3.4.0 is deprecated, I can only advise you to use version 3.3.3.

**Comment by ormaa** [comment]
thanks
perfect for me.
:o)
