### ISSUE TITLE
Windows 8.1 Store App

### ISSUE THREAD

**Issue by falahati** [unosquare/embedio#45]
Hey,
It seems that unfortunately HTPPListener is not supported on Windows 8.1 Store Apps. And no 'Capability' can solve the problem. However, I believe that socket listening is available on Windows 8.1 Store Apps tho using StreamSocketListener class. I think this is true for Windows Phone as well.

So next to .Net Core, we need to have an HTTPListener port for Windows 8.1 Store Apps, Windows 8.1 Phone Apps and Windows 8 Phone Apps.

**Comment by mariodivece** [comment]
See #41
