### ISSUE TITLE
Internal server error when response is compressed

### ISSUE THREAD

**Issue by InlineAsm** [unosquare/embedio#452]
**Describe the bug**
Commit 1dd240b7db470e585026fb7a64bf01488468c2b8 introduced a bug where the responseContentLength is incorrect and causes an internal server error.

As far as I can see the responseContentLength has to be updated with the new length when the response is compressed on the following lines:
https://github.com/unosquare/embedio/blob/1dd240b7db470e585026fb7a64bf01488468c2b8/src/EmbedIO/Files/FileModule.cs#L531-L545

**To Reproduce**
Not sure. I have this all the time on the first request to the webserver when the root index.html file is served.

This is the code I use to configure the webserver:
```
new WebServer(o => o
                    .WithMode(HttpListenerMode.Microsoft)
                    .WithUrlPrefix($"http://127.0.0.1:{localPort}"))
                    .WithWebApi(
                        "attendants api",
                        "/api",
                        CamelCasedJsonResponse,
                        m => m.RegisterController(() => this.serviceProvider.GetInstance<AttendantsController>()))
                    .WithStaticFolder(
                        "/",
                        GetWebRoot(),
                        true,
                        m =>
                        {
                            m.WithContentCaching();
                            m.DefaultExtension = ".html";
                            m.PreferCompression("text/html", true);
                        });
```

**Expected behavior**
No exception

**Screenshots**
![image](https://user-images.githubusercontent.com/6095763/74560675-571d8680-4f67-11ea-9f7f-494f6fb61cb3.png)

**Desktop**
 - OS: Windows 10 1909
 - Browser: Chrome 80.0.3987.106
 - EmbedIO version 3.4.1

**Comment by rdeago** [comment]
Hello @InlineAsm, thanks for using EmbedIO!

This is a regression in both v3.4.1 and the master branch, on which we're currently working on the upcoming v4.

**Comment by geoperez** [comment]
Nuget v3.4.2 is out!

**Comment by InlineAsm** [comment]
Thank you. It works now. Thanks for the fast fix!
