### ISSUE TITLE
Add PCL Compatibility for Custom Modules

### ISSUE THREAD

**Issue by falahati** [unosquare/embedio#46]
Hey again,
Unfortunately, because of using System.Net.HttpListenerContext in "ResponseHandler" delegate for new 'Map's it is now impossible to write custom and also portable modules for the WebServer.

We should probably contain that class in a local type so we can access it.

**Comment by geoperez** [comment]
@falahati I'm not quite sure to understand your issue, can you elaborate it with a sample code?

**Comment by falahati** [comment]
Unfortunately I dont have access to my development computer now.
But for now if it helps I try to clearify.
I wanted to write a custom request handler. For doing so I need to add a Map object. Am I correct?
Well, for processing these request I need to use ResponseHandler delegate. In definition of this delegate you used a reference to System.Net.HttpListenerContext.
But this type is not available in portable class profiles. So I cant use the delegate.
We need to have a local proxy class for this type in main project and fix the delegate defination.
I will post a sample code asap

**Comment by geoperez** [comment]
Did you have the sample code?

**Comment by mariodivece** [comment]
Is this fixed because of #41 ?

**Comment by geoperez** [comment]
I don't think so, the requirement seems to be different but I'm not quite sure to understand it.

**Comment by falahati** [comment]
Well this problem was about PCL profiles. Bot now nuget package is not even supported on PCL profiles. So as there is no official support for any of PCL profiles for now, this issue is not related any more.

**Comment by mariodivece** [comment]
I am still unsure of what needs to be done here... So @falahati all you need is a PCL build in the NuGet package that used to be there? Was the PCL package ever in the NuGet? We already do have cross-platform support so I don't suspect this would be too hard to do...

**Comment by geoperez** [comment]
I created a PCL and trying to add EmbedIO, I got this issue:

Error		Could not install package 'EmbedIO 1.1.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile78', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by geoperez** [comment]
@falahati which Profile are you using?

**Comment by falahati** [comment]
Won't work with any of PCL profiles.
I can't use a sample code to show you the problem now that it is impossible to install the NuGet package on PCL profiles. In fact, I can't even check to see if you actually solved the problem with  #41 as you said.
So for now, the first step is to have a cross-platform portable library that can be used in PCL projects.

Now, I can see that you have two different projects for .NetCore and .Net4 so you can't actually merge these two projects into a PCL project. I suggest looking into the bait-and-switch pattern for this. You need to have a PCL project with the same name and copy your classes into it but without any actual code. Replacing all codes with "NotImplamentedException". You can have another PCL library to share codes between you dummy project. .NetCore project and .Net4.5 code if it helps as well.
Now you need to make sure that all three projects (Dummy PCL one, .NetCore and .net4.5) are sharing one namespace, same name and same version.
After this, with little tweaking of NuGet packages, you can have a true cross-platform library with each platform using the correct version of Library and PCL is possible.

Soory I am little slow to reply :)

**Comment by mariodivece** [comment]
PCL will not be supported, as it has been superseded bye .NET Standard, which embedio supports as a build target. Closing issue.
