### ISSUE TITLE
System.PlatformNotSupportedException on Android

### ISSUE THREAD

**Issue by TSIoT** [unosquare/embedio#476]
I use embedio in XamrinForms Android. Everything is working fine until I enable all **Common Language Runtime Exception**. It throw System.PlatformNotSupportedException from the followin line:
`_webServer = new WebServer(HttpListenerMode.EmbedIO, url);`
I believe this probelm is come from Swan.Logging: 
`$"Running HTTPListener: {listener.Name}".Info(LogSource);`

Embedio is working fine if I keep ignore this exception.

**Comment by rdeago** [comment]
Hello @TSIoT, thanks for using EmbedIO!

I fail to see why SWAN's logger should throw `PlatformNotSupportedException` on Android. Can you elaborate on that, attaching the exception's stack trace if possible?

**Comment by TSIoT** [comment]
I have enable all exception:
![image](https://user-images.githubusercontent.com/17898508/81517158-8f691100-936c-11ea-8d47-b46ae7df261a.png)
Then it throw exception when I initial the WebServer instance:
![image](https://user-images.githubusercontent.com/17898508/81517221-c50dfa00-936c-11ea-9228-3b503686a4ed.png)
Here are the detials of exception:
{System.PlatformNotSupportedException: Operation is not supported on this platform.  at System.Console.get_WindowHeight () [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2019-10/android/release/mcs/class/corlib/System/Console.cs:879   at Swan.Terminal.get_IsConsolePresent () [0x00017] in <869ca606d31f4fc18ff59301f10d0773>:0 }

**Comment by rdeago** [comment]
As you can see from [SWAN's source code](https://github.com/unosquare/swan/blob/3bb63a693c93acc5066ddeddf850ae26a565d84f/src/Swan.Lite/Terminal.cs#L117-L143), the exception is expected, as part of a test to determine whether a console is present; it is properly handled by SWAN internally, so it will not be a problem when not debugging.

**Comment by TSIoT** [comment]
Thanks for your response :)
I agree that this is not a problem of EmbedIo. But if an exception throw every time then it is not an "exception" even in debug mode. However, I will pos this issue to Swan's git. Thank again!
