### ISSUE TITLE
HttpListener=Microsoft crashes on Linux NET Core 3.1 in EmbedIO 3.4.3

### ISSUE THREAD

**Issue by NoTimeForHero** [unosquare/embedio#477]
Hello.

EmbedIO.WebServer with _HttpListenerMode=Microsoft_ crushes on Linux after any HTTP request with exception:
```
System.ObjectDisposedException: 
        Cannot access a disposed object.
        Object name: 'System.Net.HttpListenerResponse'.
```

But in Windows it working as intended.
With _HttpListenerMode=EmbedIO_ in Linux it works too.

**Affected enviroment**
- EmbedIO 3.4.3
- NET Core: 3.0/3.1
- Operating systems: Debian 9, CentOS 7
- Any port/prefix

**Steps to reproduce**
Minimal example:
```cs
using EmbedIO;
using EmbedIO.Actions;
using System;

namespace Test1
{
    class Program
    {
        static void Main(string[] args)
        {
            new WebServer(o => o.WithUrlPrefix("http://localhost:3000").WithMode(HttpListenerMode.Microsoft))
                .WithModule(new ActionModule("/", HttpVerbs.Any, ctx => ctx.SendDataAsync(new { Message = "Hello world!" })))
                .Start();
            Console.ReadKey();
        }
    }
}
```

**Exception details from console**
```
01:07:00.246 ERR >> [WebServer] [Vde65z5I60uOVpmTH7e+3Q] Fatal exception.
    $type           : System.ObjectDisposedException
    Message         : 
        Cannot access a disposed object.
        Object name: 'System.Net.HttpListenerResponse'.
    ObjectName      : System.Net.HttpListenerResponse
    TargetSite      : Void CheckDisposed()
    StackTrace      : 
        at System.Net.HttpListenerResponse.CheckDisposed()
        at System.Net.HttpListenerResponse.get_OutputStream()
        at EmbedIO.Net.Internal.SystemHttpResponse.get_OutputStream()
        at EmbedIO.WebServerBase`1.DoHandleContextAsync(IHttpContextImpl context)
    Source          : System.Net.HttpListener
    HResult         : -2146232798
```

**Comment by rdeago** [comment]
Hello @NoTimeForHero, thanks for using EmbedIO!

Thank you also for the gazillionth reason why ditching HttpListener would make EmbedIO a better library.

Unfortunately, digging into .NET Core's runtime source code to try and debug this issue would not only cost hours of time, not to mention headache medication<sup>(*)</sup> &mdash; it would be pointless, since HttpListener has long been deemed obsolete and unworthy of any serious maintenance.

All the advice I can give is to steer away from the configuration that is giving you trouble: use `HttpListenerMode.EmbedIO`.

---

(*) no overstatement here: been there, done that &mdash; more than once.

**Comment by CraziiTim** [comment]
Hi. I'm having the same issue while using ` HttpListernerMode.EmbedIO`

`
  private static WebServer CreateWebServer(string u)
        {
            var server = new WebServer(o => o
                    .WithUrlPrefix(u)
                    .WithMode(HttpListenerMode.Microsoft))
                .WithCors()
                // First, we will configure our web server by adding Modules.
                .WithLocalSessionManager()
                .WithWebApi("/api", m => m.RegisterController(() => new ApiController()));
                

            // Listen for state changes.
            server.StateChanged += (s, e) => Logging.Log($"WebServer New State - {e.NewState}");

            return server;
        }
`

**Comment by CraziiTim** [comment]
Update: `HttpListenerMode.Microsoft` is even worse. Doesn't work at all lol. Back to `HttpListenerMode.EmbedIO` - Still the same issue `Cannot access a disposed object.`
