### ISSUE TITLE
CPU usage spike with EmbedIO

### ISSUE THREAD

**Issue by deepgoyal25** [unosquare/embedio#481]
**Describe the bug**
We have started noticing CPU usage spike for our Windows and Mac users after we started using EmbedIO to host http server in our native application.
On Mac, the CPU usage spike is easily reproducible. We see an uptick of up to 4% CPU usage spike just by starting Http server with EmbedIO during application start. The CPU usage stays at 4% all the time even when we are not sending any calls to the http server.

**To Reproduce**
We are using the below code in our application to start http server: -
WebServer webServer = new WebServer(options => options.WithUrlPrefix(baseAddress).WithMode(HttpListenerMode.EmbedIO)).WithWebApi("/", m => m.RegisterController < MainModule >());
webServer.Start();

**Expected behavior**
CPU usage should not stay constantly at 4% when server is not serving any requests

**Desktop (please complete the following information):**
 - OS: MacOS 10.14 (MacOS Mojave)
 - .Net version - 4.6.2
 - Xamarin.Mac 5.16.1.25 (issue-7441-d16-3-vsmac / 881172e73)
 - === Mono Framework MDK ===

    Runtime:
	Mono 6.6.0.166 (2019-08/d9001b5ae70) (64-bit)
	Package version: 606000166

**Comment by deepgoyal25** [comment]
Any updates on the reported issue

**Comment by rdeago** [comment]
Hello @deepgoyal25, thanks for using EmbedIO! Also, apologies for taking all this time to reply.

Do you know of any way to reliably reproduce the issue either on Windows or on Linux? If not, I'll need your help to do some testing on a Mac, especially if you can use a profiler.

**Comment by deepgoyal25** [comment]
Hi @rdeago, thanks for getting back on this issue.
I am not able to reproduce this issue on Windows and Linux.
I am happy to help out with investigation. Let me know the steps that I need to try out
