### ISSUE TITLE
Terminal cursor breaking

### ISSUE THREAD

**Issue by SEQUOIIA** [unosquare/embedio#482]
**Describe the bug**
Starting the web server breaks the terminal cursor on macOS. Seems to be working as intended though in Windows.

**To Reproduce**
Merely just running
```
using (var server = Server.CreateWebServer())
{
  var cts = new CancellationTokenSource();
  Server.cts = cts;
  await server.RunAsync(cts.Token).ConfigureAwait(false);
}
```

will break the terminal.

**Expected behavior**
My terminal cursor shows up and works after exiting the application.

**Screenshots**
macOS video: https://cx11.cloud.seq.tf/embedio_macos.mp4
Doesn't work with web server started but does without.

Windows video: https://cx11.cloud.seq.tf/embedio_macos.mp4
Works with web server started and without.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.5
 - Browser: Not applicable
 - Version: EmbedIO 3.4.3

**Additional context**

**Comment by geoperez** [comment]
Hello, this is probably an issue with the logging library used, SWAN. I'll take a look.

**Comment by SEQUOIIA** [comment]
@geoperez Awesome. Please let me know if there is anything I can do(further testing, etc.)
