### ISSUE TITLE
backslash

### ISSUE THREAD

**Issue by Zulllus** [unosquare/embedio#483]
Start sample app (EmbedIO.Samples). 
On the page "http://localhost:8877/api/people/first" I get response from server with some extra backslashes.
{"Id": 1,"Name": "Mario Di Vece","Age": 31,"EmailAddress": "mario@unosquare.com","PhotoLocation": "http:\/\/www.gravatar.com\/avatar\/CEC856578C6F782F9A3FD0FF3C384CBA.png?s=100"}
Also on the page "http://localhost:8877/#/people" avatar images broken.
Maybe I'm doing something wrong.

**Comment by Zulllus** [comment]
Hm... :) issue tracker remove example bug:
`
{"Id": 1,"Name": "Mario Di Vece","Age": 31,"EmailAddress": "mario@unosquare.com","PhotoLocation": "http:\/\/www.gravatar.com\/avatar\/CEC856578C6F782F9A3FD0FF3C384CBA.png?s=100"}
`

**Comment by geoperez** [comment]
@JCorrea13  can you help me to review this issue?

**Comment by Zulllus** [comment]
You have a bug in the Swan.Lite library, in the Json.Serializer.cs file in line 170. 

```.Append('\\')```

I just comment this line. But this only heals the api. I didn’t tinker with broken pictures in html. Of course, I didn't deeply understanding the problem at all, only do heal for my specific task.
