### ISSUE TITLE
Getting Started Tutorial

### ISSUE THREAD

**Issue by katterfelto** [unosquare/embedio#485]
I found your project via NancyFX which is now archived. I would like to add a web interface to one of our windows services. The one thing that seems lacking in the embedio documentation is a getting started tutorial.

Please don't take this negatively, I will happily help if I can.

As someone completely new to embedio the first thing I tried was cutting and pasting your first example code in the readme.md into a console application, but that doesn't compile. It is missing code (which I know is in the samples folder) as well as a couple of using statements:

`using EmbedIO.Actions;`
`using Swan.Logging;`

How about simplifying your server declaration to something like:

`var server = new WebServer(o => o`
`.WithUrlPrefix(url)`
`.WithMode(HttpListenerMode.EmbedIO))`
`.WithLocalSessionManager()`
`.WithModule(new ActionModule("/", HttpVerbs.Any, ctx => ctx.SendStringAsync("<h1>Hello World!</h1>", "text/html", System.Text.Encoding.UTF8)));`

I realise my suggested first example is simple and doesn't show off the potential power of the project, but it demonstrates it's easy to use and the first time user ends up with a working web server very early in their introduction to the project. You could then follow up with the current code from the sample folder to show more complex scenarios are possible, from my perspective I wouldn't expect that to compile.

**Comment by geoperez** [comment]
Hello, I think you are right, even your sample can be reduced to:

```
var server = new WebServer(o => o
.WithUrlPrefix(url))
.WithModule(new ActionModule("/", HttpVerbs.Any, ctx => ctx.SendStringAsync("<h1>Hello World!</h1>", "text/html", System.Text.Encoding.UTF8)));
```

You only need an URL Prefix and entry point for the root.

I'll check the documentation and try to make it cleaner.
