### ISSUE TITLE
Json returned from get have extra characters in the response

### ISSUE THREAD

**Issue by olivier38070** [unosquare/embedio#486]
I have an application written in Xamarin forms, using EMBEDIO.
when another application call one web service, the web server (embed) return a json object.
on the client side, the json object have extras characters then I Cannot deserialise the object.
if I remove manually the extras characters from the string in the response, I can deserialise the object.

note :
with embedIO 3.3.3 : I don't have the problem.
with embed 3.4.3 I have the issue

-- Here is the code to start my web server 

```C#
                server = new WebServer(o => o
                .WithUrlPrefix(serverUrl)
                .WithMode(HttpListenerMode.Microsoft))
                .WithLocalSessionManager()
                .WithWebApi("/api", m => m.WithController<ServerController>())
                .WithModule(new ActionModule("/", HttpVerbs.Any, ctx => ctx.SendDataAsync(new { Message = "Error" })));

            server.StateChanged += (s, e) =>
            {
                Singleton.common.Log("Web server state changed : " + e.NewState.ToString());

                Xamarin.Forms.Device.BeginInvokeOnMainThread(() =>
                {
                   // ... my code here is not important
                });
            };
            server.Start();
```

-- here is the GET routing

```C#
    public class ServerController : WebApiController
   {

        [Route(HttpVerbs.Get, "/get/{action}")]
        public async Task<String> Get(string action) => await GetDatas(action);
        internal async Task<String> GetDatas(String action)
        {
            await Task.Delay(0).ConfigureAwait(false);
            try
            {
                string result = getMyJSONOBject(); // do some stuff to get my serialised object in a String
                return result;  // the string is correct at this step
            }
            catch (Exception ex)
            {
                // I manage my error here. not interesting here for that issue
            }
        }
```

-- here is my web service code

```C#
        // get one order 
        public async void GetOrder(Order order)
        {
            try
            {
                string json = JsonConvert.SerializeObject(order);
                var httpContent = new StringContent(json, Encoding.UTF8, "application/json");
                using (var httpClient = new HttpClient())
                {
                    HttpClient client = new HttpClient();
                    client.Timeout = TimeSpan.FromSeconds(8);

                    // Do the actual request and await the response
                    var httpResponse = await client.PostAsync(serverIP + "/api/post/getOrder", httpContent);

                    // If the response contains content we want to read it!
                    if (httpResponse.Content != null)
                    {
                        var responseContent = await httpResponse.Content.ReadAsStringAsync();
                        Console.WriteLine(responseContent);
                        // here the response has extra characters at start, and end.
                    }
                }
            }
            catch (Exception ex)
            {
            }
        }
```

-- example of json response with extra characters

```Json
"\"{\"rooms\":[{\"tables\":[{\"num\":1            .... all my datas if here
"dehors\"}],\"versionNum\":151}\""
```

-- example of correct json returned by an earlier version 
```Json
"{\"rooms\":[{\"tables\":                   ...... all my datas are here with correct format .......   
"}],\"versionNum\":151}"
```

my temporary ugly solution : remove the last characters : "
remove the First characters "\"

expected : the web server should return the object without any extra character.

**Comment by olivier38070** [comment]
Any idea about how i can fix that. I cannot update the nuget because of that issue. May be i can use it in another way to avoids that ?
Thanks for help

**Comment by rdeago** [comment]
Hello @olivier38070, thanks for using EmbedIO! Please accept my apologies for taking so long to address your issue.

The extra characters are due to the fact that you are serializing data twice.

As a matter of fact, EmbedIO will automatically serialize anything your controller methods return. The default serialization method uses the JSON serializer in the [SWAN](https://github.com/unosquare/swan) library.

Is there any way you can just return the result object instead of an already-serialized  string?

```C#
public class ServerController : WebApiController
{
    [Route(HttpVerbs.Get, "/get/{action}")]
    public async Task<object> Get(string action) => await GetDatas(action);

    internal async Task<object> GetDatas(string action)
    {
        await Task.Delay(0).ConfigureAwait(false);
        try
        {
            return getMyObject(); // do some stuff to get my object, without serializing it
        }
        catch (Exception ex)
        {
            // I manage my error here. not interesting here for that issue
        }
    }
}
```

Of course your controller method can return `Task<AnyClassYouWant>`. I used `Task<object>` just as an example.

Please let me know whether this helps solving your problem.

**Comment by olivier38070** [comment]
Hello

I Will try,
Thank you
Best regards
Olivier

**Comment by olivier38070** [comment]
Hello,

no your solution didn't help me.
my code is generic, and return a string, with inside : string of anything, decoded properly on client side.
is there a ways to avoid the EmbedIO server to serialise what it return ? ( because if I know that it is a string, I don't need the Swan serialisation ).
if there is a parameter to disable Swan serialisation, I Could keep my generic GET web service .

thanks for any feedback from your side :o)

**Comment by rdeago** [comment]
> is there a ways to avoid the EmbedIO server to serialise what it return ? ( because if I know that it is a string, I don't need the Swan serialisation ).

Yes, there is a way; I was just trying simpler methods first.

Unfortunately, the only way to change the response serialization of a Web API module is to subclass `WebApiModule`, as its `Serializer` property (inherited from `WebApiModuleBase`) is read-only. This is not as hard as it may seem: actually, it's almost earlier done that said.

This is a subclassed web API module that sends responses as JSON without performing any actual serialization:

```C#
using System.Threading.Tasks;
using EmbedIO;
using EmbedIO.Utilities;
using EmbedIO.WebApi;

namespace YOUR_NAMESPACE
{
    public sealed class JsonBypassWebApiModule : WebApiModule
    {
        public JsonBypassWebApiModule(string baseRoute)
            : base(baseRoute, JsonBypass)
        {
        }

        private static async Task JsonBypass(IHttpContext context, object? data)
        {
            Validate.NotNull(nameof(context), context).Response.ContentType = MimeType.Json;
            using var text = context.OpenResponseText(new UTF8Encoding(false));
            await text.WriteAsync(data?.ToString() ?? string.Empty).ConfigureAwait(false);
        }
    }
}
```

This is a handy extension method to keep your initialization code as fluent as before:

```C#
using EmbedIO;
using EmbedIO.WebApi;

namespace YOUR_NAMESPACE
{
    public static class WebModuleContainerExtensions
    {
        public static TContainer WithJsonBypassWebApi<TContainer>(this TContainer @this, string baseRoute, Action<WebApiModule> configure)
            where TContainer : class, IWebModuleContainer
            => @this.WithModule(new JsonBypassWebApiModule(baseRoute), configure);
    }
}
```

Just use `WithJsonBypassWebApi` instead of `WithWebApi` in your server initialization code.

---

On a side note, it would be nice if the response serializer callback was configurable without going through the hassle of subclassing. @geoperez should we add this to the v4.0 backlog?

**Comment by geoperez** [comment]
Sounds like a plan!

**Comment by olivier38070** [comment]
thanks a lot, I will try that :o)

**Comment by rdeago** [comment]
Actually you can already specify a response serializer for a `WebApiModule`, either [with a constructor parameter](https://unosquare.github.io/embedio/api/EmbedIO.WebApi.WebApiModule.html#EmbedIO_WebApi_WebApiModule__ctor_System_String_EmbedIO_ResponseSerializerCallback_) or [using a fluent extension method](https://unosquare.github.io/embedio/api/EmbedIO.WebModuleContainerExtensions.html#EmbedIO_WebModuleContainerExtensions_WithWebApi__1___0_System_String_EmbedIO_ResponseSerializerCallback_Action_WebApiModule__).

Shame on me for overlooking that.
