### ISSUE TITLE
Implement DeleteSession method in LocalSessionModule

### ISSUE THREAD

**Issue by bufferUnderrun** [unosquare/embedio#50]
Hi,

I am facing an issue (not really a bug) with the LocalSessionModule and i will trying to explain clearly, not easy.

1. When a user connects to my app (ie: index.html), Embedio always starts a session (in memory) and so a cookie "__session" is created in his browser. No problem.
2. Then, the user login and i add some extras infos to check security (roles based) to the embedio session (`session.Data.TryAdd("user-roles", new List<String>() { "admin", "debug" })`). No problem.
3. At the end, the user logout and because there is no "DeleteSesssion()" method, i simply delete all extras infos i've added with `session.Data.Clear()`. The session in Embedio is always enabled but do no rely on extras infos i used to check securty (this user is not admin anymore). A new session is started for the user, new session in Embedio and the browser get a new "__session" AND the old one. No problem.
4. BUT, when the user refresh his browser, the 2 "__session" cookies are send (";" separed) and Embedio take the first valid, the old one because always in memory and not the new...

Could you add a new method `DeleteSession(SessionInfo session)` in the LocalSessionModule to properly delete a session in embedio ?

Thanks.

**Comment by mariodivece** [comment]
Do you mind creating a pull request or proposing the code right here in the issue?

**Comment by bufferUnderrun** [comment]
@mariodivece You're right, it's more a pull request (enhancement) than issue. See [my proposal](https://github.com/unosquare/embedio/files/576255/add-DeleteSession-patch.txt). It should work but as usual, i've not installed vs2015 yet, so i can't test...

PS : arghhh github don't support file with "patch" extension, it's a shame...

**Comment by mariodivece** [comment]
Thanks @bufferUnderrun I have committed the changes.
@geoperez could you please update the NuGet package?

**Comment by bufferUnderrun** [comment]
thanks

**Comment by geoperez** [comment]
The new Nuget was published.
