### ISSUE TITLE
How can I create a https connection

### ISSUE THREAD

**Issue by ghiboz** [unosquare/embedio#500]
hi all! I'm trying to create an https connection:
following the samples I get this code:

```cs
            var options = new WebServerOptions("https://192.168.0.30:5555");
            options.AutoLoadCertificate = true;
            options.Mode = HttpListenerMode.EmbedIO;
   
            http = new WebServer(options);
            http.RegisterModule(new WebApiModule());
            http.RegisterModule(new StaticFilesModule(wwwPath.Text));
```

and when the server starts I get this:
![](https://i.imgur.com/nqRjCvN.png)

How can I make a ssl certificate? and how can I set the cert to the webserver options?

NOTE: I will use my app in a 'local' server, not a public server
thanks in advance

**Comment by rdeago** [comment]
Hello @ghiboz, sorry for the late answer.

I'm no SSL expert at all, but [a simple search](https://duckduckgo.com/?q=create+self-signed+ssl+certificate) can help you with the creation of a self-signed certificate. Sorry for not being of more help; maybe @geoperez can shed more light on the subject.
