### ISSUE TITLE
Please update swan.logging to 3.1.0 (3.0.0 Crashes on Terminal init)

### ISSUE THREAD

**Issue by faljse** [unosquare/embedio#509]
On some systems swan.logging crashes on terminal init:
https://github.com/unosquare/swan/issues/250
https://github.com/unosquare/swan/issues/247

This seems to be fixed in 3.1.0 (rebuilding embedio did work for me)
Would be nice to upgrade this dependency in your next release.

Regards,
faljse

**Comment by rdeago** [comment]
Hello @faljse, thanks for using EmbedIO!

The update to Swan 3.1.0 is already committed, we're just waiting for the release of EmbedIO v3.5.0.
