### ISSUE TITLE
WebSockets Support on Windows 7 and Mono 3.x

### ISSUE THREAD

**Issue by bufferUnderrun** [unosquare/embedio#51]
Hi,

It's not an issue or pr, just asking question. As i don't know how to contact you (a mailing list ?) let's do this here. Feel free to delete if it is not appropriate.

Before Embedio, i used the [websocket-sharp project](https://github.com/sta/websocket-sharp) to serve websocket in my app. Yesterday, i've just understood that the WebsocketModule provide by Embebio is using the Microsoft http.sys and so, starts with Windows 8 and higher. Little punch in my face as my dev env is always in Win7 (yes, i hate the win8&10 UI) and my app have to support Win7.

According to [https://msdn.microsoft.com/fr-fr/library/system.net.websockets.websocket](Microsoft)
> The classes and class elements in the N:System.Net.WebSockets namespace that are supported on Windows 7, Windows Vista SP2, and Windows Server 2008 are abstract classes. This allows an application developer to inherit and extend these abstract classes with an actual implementation of client WebSockets. 

Do you known if it exists an implementation of this class or at least, if the websocket-sharp can be integrated in Embedio with little effort to support websocket for Win7 ?

Thanks for your answer.

**Comment by mariodivece** [comment]
We will also need WebSockets to run on mono pretty soon here. I am investigating. Please stay tuned and provide any suggestions you may have.

**Comment by mariodivece** [comment]
This might be a good start:
https://github.com/sta/websocket-sharp#http-server-with-the-websocket

**Comment by mariodivece** [comment]
Some source code: https://github.com/sta/websocket-sharp/blob/master/websocket-sharp/HttpRequest.cs#L99

**Comment by mariodivece** [comment]
Additional library -- looks promising: http://vtortola.github.io/WebSocketListener/

**Comment by mariodivece** [comment]
Yet another alternative: http://supersocket.net/

**Comment by bufferUnderrun** [comment]
Interesting, i'll look into WebSocketListener.

**Comment by geoperez** [comment]
Today I published a new version and nuget with support to websockets in mono and windows 7.

**Comment by bufferUnderrun** [comment]
very exciting, i saw this 2 hours ago and i'm testing it. I'm cleaning my project (replacing System.Net.Websockets by Unosquare.Net) to get things works. I will give you feedback as soon as possible (probably tomorrow).

**Comment by bufferUnderrun** [comment]
Just can't wait :)

Primary tests shows EmbedIO handle websockets with my Win7 ! I will do some refactoring and migrate all my code from websocket-shap to embedio websockets. I will give you feedback if something goes wrong.

You can close the issue.

@mariodivece @geoperez guys, you've made an incredible work with this project.

**Comment by mariodivece** [comment]
Excellent! Closing! Open up a new issue if you run into any problems with WebSockets please.
