### ISSUE TITLE
force keep-alive

### ISSUE THREAD

**Issue by gyorokpeter** [unosquare/embedio#514]
I would like to implement a web server that doesn't close connections, it should be up to the client to close them, even if the client doesn't explicitly specify "Connection: keep-alive" in the headers. This is because a client may send many requests and handling them in separate connections would be too much overhead.
The clients are pre-existing applications which are known to support sending multiple requests through the same connection.

**Comment by rdeago** [comment]
Hello @gyorokpeter, thanks for using EmbedIO!

Your requirement being a blatant violation of the HTTP protocol, I strongly doubt you'll find any web server library supporting it out-of-the.-box, including EmbedIO. I don't think a "forced keep-alive" feature would make much sense.

That said, I understand that sometimes one has to work with what one is given. If you're willing to use a private fork of EmbedIO, here's how to force keep-alive with the least possibile modifications.

Just insert the following line of code below [this line](https://github.com/unosquare/embedio/blob/6ab15ee62bbbd1171f9bae3392d3c46ae86521ea/src/EmbedIO/Net/Internal/HttpListenerRequest.cs#L283) in `src/EmbedIO/Net/Internal/HttpListenerRequest.cs` (at the end of the `FinishInitialization` method):

```C#
            Headers.Set("Connection", "keep-alive");
```

As long as you use `HttpListenerMode.EmbedIO`, this will make EmbedIO treat all incoming requests as if they contained a [`Connection` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Connection) with a value of `keep-alive` and act accordingly.

**DISCLAIMERS**

- I did not actually test the above code, although I'm pretty sure it works.
- As I said above, this is a blatant violation of the HTTP protocol, so do it at your own risk. If you break something, you own both (or all) pieces.
- EmbedIO will close a connection anyway if the response status code is one in a hard-coded list of values, and every 100 served requests anyway. The code that does this is [here](https://github.com/unosquare/embedio/blob/6ab15ee62bbbd1171f9bae3392d3c46ae86521ea/src/EmbedIO/Net/Internal/HttpListenerResponse.cs#L208-L238) and is pretty easy to modify.
- Please keep your fork private; more specifically, do not distribute it under the name `EmbedIO`. Intellectual property matters aside, someone could install your fork by mistake and then face some weird, hard-to-figure-out bug in production.

**Comment by gyorokpeter** [comment]
In that case I will keep my bespoke solution that implements HTTP over a standard TcpListener.
The reason I wanted to use EmbedIO in the first place is because I wanted to integrate my code as a plugin to another app that already uses EmbedIO. So using a custom fork would not work.

**Comment by rdeago** [comment]
> [...] my bespoke solution that implements HTTP over a standard TcpListener.

Is that a private project, or may I take a look at it? We have to find a replacement for HttpListener before its status goes from the current "shamefully obsolete" to "covered in cobwebs" and any input is welcome.

**Comment by gyorokpeter** [comment]
https://github.com/gyorokpeter/SteelSeriesServer/blob/f7442dfcbeed365ac560c4946accc81a2b0fd965/SteelSeriesServer.cs#L456
