### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by angrykirc** [unosquare/embedio#519]
Too small of an issue to create a PR, so I thought I'd just write it down here.

**Describe the bug**
In _README.md_, there is a _WebSockets Example_ provided.

The example class' names in this example are different. In first paragraph, it's "WebSocketChatModule", and in the next one, it is "WebSocketsChatServer" (that implements WebSocketModule, so I guess it's not really a "Server", but a "Module".)

**Comment by rdeago** [comment]
Hello @angrykirc, thanks for using EmbedIO and for taking the time to open this issue.
