### ISSUE TITLE
Fix Samples Solution

### ISSUE THREAD

**Issue by mariodivece** [unosquare/embedio#52]
Currently the Samples solution looks bad and it is kind of broken. Please fix.

**Comment by geoperez** [comment]
@mariodivece  i unified the versions, let me know if you need anything else.

**Comment by mariodivece** [comment]
This is still broken. See noted examples right off the bat... I'm sure there is more. Put care into the sample please. Maybe add the Create and edit records functionality for people? The grid looks misaligned especially the overlay.

![image](https://cloud.githubusercontent.com/assets/351978/20279009/7df3d38e-aa6c-11e6-8c9c-36e70fa90842.png)
![image](https://cloud.githubusercontent.com/assets/351978/20279048/9a4bc294-aa6c-11e6-8f5c-b33e07c58f07.png)
![image](https://cloud.githubusercontent.com/assets/351978/20279079/b639988c-aa6c-11e6-85f1-0d93fda8460e.png)

**Comment by geoperez** [comment]
I see, I think broke like not building.... 🤕

**Comment by kadosh** [comment]
That was fixed on [this commit](https://github.com/unosquare/embedio/commit/586b3fafb8a4ab4e76c0c22aeb8b83e7913e75eb)
