### ISSUE TITLE
how to use WebApiConroller and Post.

### ISSUE THREAD

**Issue by Novotnde** [unosquare/embedio#526]
Hello, 

I would kindly ask for explanation of the WebApiConroller and Post. 

I am trying to post something, I have tried get but post seems to be better for what I need. I have created only simple sample to return some numbers
```
  [Route(HttpVerbs.Post, "/test/")]
        public int PostFile()
        {
            
            return 25852;
        }
```
And then use  client.PostAsync, but  client.PostAsync needs two parameters. Url and Content, but the method that return numbers doest get called at all. I am sorry to bother but I can't find any solution even in your cookbook, all examples are of course clear but if you are beginner like me then don't say much. 
 ```
private async Task TestPost()
        {
            try
            {
                var handler = new HttpClientHandler
                {
                    AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate,
                };
                using (var client = new HttpClient(handler))
                {
                    client.DefaultRequestHeaders.AcceptEncoding.Add(new StringWithQualityHeaderValue("*"));
                    
                    using (var response = await client.PostAsync($"{DefaultUrl}test/", CONTENT ?? ).ConfigureAwait(false)) // calling controller?
                    {
                        var responseString = await response.Content.ReadAsStringAsync().ConfigureAwait(false);
                        Result += "Result = " + (string.IsNullOrEmpty(responseString) ? "<Empty>" : responseString);

                    }
                }

            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
        }
```

MY server 

     Task.Factory.StartNew(async () =>
            {
                using (var server = new WebServer(HttpListenerMode.EmbedIO, "http://*:8089"))
                {
                    Assembly assembly = typeof(App).Assembly;
                    server.WithLocalSessionManager();
                    server.WithWebApi("/api", m => m.WithController(() => new PdfSourceController()));
                    server.WithEmbeddedResources("/", assembly, "Reader.html");
                    await server.RunAsync();
                }
            });

**Comment by rdeago** [comment]
Hello @Novotnde, nice to see you're still using EmbedIO.

A complete explanation of `HttpClient` is way beyond me, but I can tell you that the `content` parameter must be an instance of a class derived from [`HttpContent`](https://docs.microsoft.com/dotnet/api/system.net.http.httpcontent). Follow the link for the official MS documentation.

As for server-side code, before we even start it would be very helpful to see your Web server initialization code.

**Comment by Novotnde** [comment]
No I don't need that , I just I am not sure ow to actually ise the Web Api call and its content in the method

**Comment by rdeago** [comment]
Well, for a quick test you can use the simplest possible HttpContent: `new ByteArrayContent(new byte[0])`.

**Comment by Novotnde** [comment]
thank you, this way I get 404 - Not found, so it does not see the  [Route(HttpVerbs.Post, "/test/")]
       ```
 public int PostFile()
        {
            return 25852;
        }
```

**Comment by rdeago** [comment]
Are you sure your client is requesting the correct path, i.e. `/api/test`?

**Comment by Novotnde** [comment]
so sorry, I have been trying to make this work for several hours and decided to do this simple sample and even forgot to add the correct path

**Comment by rdeago** [comment]
[This section of the wiki](https://github.com/unosquare/embedio/wiki/Cookbook#multi-part-forms-and-file-uploads-multipartform-data) deals specifically with file uploads. You'll have to do some googling for the client-side code, it shouldn't be hard to find. 😉

**Comment by Novotnde** [comment]
yes, have seen that. thank you

**Comment by Novotnde** [comment]
May I also ask what does this mean? 

 20:31:39.837 INF >> [WebServer] [I5jaPTbgG02WMJvMXqvB9g] GET /: "404 Not Found" sent in 187ms (0 bytes)
 20:31:39.837 INF >> [WebServer] [ZSbyfVU72kmnyVej0v8KWg] POST /api/test/: "200 OK" sent in 2473ms (0 bytes)
 20:31:39.742 ERR >> [WebServer] [I5jaPTbgG02WMJvMXqvB9g] HTTP exception 404
    $type           : EmbedIO.HttpException
    StatusCode      : 404
    TargetSite      : Void MoveNext()
    StackTrace      :    at EmbedIO.WebServerBase`1.DoHandleContextAsync(IHttpContextImpl context)
    Message         : No module was able to serve the requested path.
    Source          : EmbedIO
    HResult         : -2146233088

I have added some cars.  .WithCors( 
                   "content-type, accept", 
                   "post, get") ###
