### ISSUE TITLE
Upgrade error to embedio v1.2.5 with nuget

### ISSUE THREAD

**Issue by bufferUnderrun** [unosquare/embedio#57]
Hi,

I can't upgrade to the last v1.2.5 release from nuget due to a dependency error :

```
Attempting to resolve dependency 'Newtonsoft.Json (≥ 9.0.1)'.
'EmbedIO' already has a dependency defined for 'System.Security.Cryptography.Primitives'.
```

The regression seems to have been introduced in the commit https://github.com/unosquare/embedio/commit/0e333d005ae35cbf2e0f27663e73e64fe3ec8604?diff=split

**Comment by geoperez** [comment]
I just published a new nuget without the dependency mess, can you try again. @bufferUnderrun  and @harper10

**Comment by geoperez** [comment]
Hi guys, could you try again with version 1.2.7?

**Comment by bufferUnderrun** [comment]
with v1.2.7, another error

```
Attempting to resolve dependency 'Newtonsoft.Json (≥ 9.0.1)'.
'EmbedIO' already has a dependency defined for 'System.Collections.Specialized'.
```

**Comment by geoperez** [comment]
Can you show me your project.json please?

**Comment by bufferUnderrun** [comment]
I am stuck at vs2013. The error occurs even on a brand new project.

**Comment by geoperez** [comment]
Oh ok, let me try with a CSPROJ then.

**Comment by harper10** [comment]
I also have .csproj files instead of project.json.

**Comment by geoperez** [comment]
I was unabled to reproduce the issue with VS2015 and a CSPROJ 452. My log:

Attempting to gather dependency information for package 'EmbedIO.1.2.7' with respect to project 'tpro', targeting '.NETFramework,Version=v4.5.2'
Gathering dependency information took 299.1 ms
Attempting to resolve dependencies for package 'EmbedIO.1.2.7' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'EmbedIO.1.2.7'
Resolved actions to install package 'EmbedIO.1.2.7'
Retrieving package 'EmbedIO 1.2.7' from 'nuget.org'.
Retrieving package 'Newtonsoft.Json 9.0.1' from 'nuget.org'.
Adding package 'Newtonsoft.Json.9.0.1' to folder 'c:\Users\geovanni.perez\documents\visual studio 2015\Projects\tpro\packages'
Added package 'Newtonsoft.Json.9.0.1' to folder 'c:\Users\geovanni.perez\documents\visual studio 2015\Projects\tpro\packages'
Added package 'Newtonsoft.Json.9.0.1' to 'packages.config'
Executing script file 'c:\Users\geovanni.perez\documents\visual studio 2015\Projects\tpro\packages\Newtonsoft.Json.9.0.1\tools\install.ps1'...
Successfully installed 'Newtonsoft.Json 9.0.1' to tpro
Adding package 'EmbedIO.1.2.7' to folder 'c:\Users\geovanni.perez\documents\visual studio 2015\Projects\tpro\packages'
Added package 'EmbedIO.1.2.7' to folder 'c:\Users\geovanni.perez\documents\visual studio 2015\Projects\tpro\packages'
Added package 'EmbedIO.1.2.7' to 'packages.config'
Successfully installed 'EmbedIO 1.2.7' to tpro
Executing nuget actions took 3.72 sec

**Comment by geoperez** [comment]
Running VS2013 I'm getting the same error: 'EmbedIO' already has a dependency defined for 'System.Collections.Specialized'.

I think the Nuget client version is affecting.

**Comment by geoperez** [comment]
Yes, updating the Nuget client to latest in VS2013 resolves the issue. Could you try?

**Comment by bufferUnderrun** [comment]
confirm ! with a nuget client up to date, the package can be installed. 

Apologize.

**Comment by geoperez** [comment]
No problem, closing ticket.
