### ISSUE TITLE
Handle ETags

### ISSUE THREAD

**Issue by geoperez** [unosquare/embedio#6]
StaticFilesModule needs to handle ETags

**Comment by mariodivece** [comment]
Yep, that was a comment I left in the code and that certinly needs to be addressed. Another nice to have would be partial content with range requests for the purposes of for example, camera streams.
http://benramsey.com/blog/2008/05/206-partial-content-and-range-requests/

**Comment by geoperez** [comment]
Mario, I pushed Etags and 206 partials support. Check them please.

**Comment by geoperez** [comment]
New release
