### ISSUE TITLE
Not able to set NullLog!

### ISSUE THREAD

**Issue by caverna** [unosquare/embedio#63]
I did install from NuGet (1.4.6).
In this binary, there's no way to set NullLog as ILog in Webserver constructor.
Looking at the source code, you're using conditional tag for compilation.
Is there any reason for that?
Is it safe just download all source code and set COMPAT in "Conditional compilation symbols" at build properties?

**Comment by geoperez** [comment]
Yes, if check the 1.4 release notes, we decide to move the logging
subsystem out of EmbedIO to use our toolkit Swan. If you have plans to use
nulllog, you are just fine using the latest version.

**Comment by caverna** [comment]
Well, the main idea was to use no log at all (NullLog should be that, right?)

**Comment by geoperez** [comment]
So you are fine 👍 use the current version without anything else.

**Comment by mariodivece** [comment]
Closing and rejecting issue.
