### ISSUE TITLE
context.UserEndPoint - NullReferenceException

### ISSUE THREAD

**Issue by lansman** [unosquare/embedio#64]
I get error when try to read context.UserEndPoint in OnClientDisconnected() and sometimes in OnMessageReceived() hooks
```
in Unosquare.Net.HttpConnection.get_RemoteEndPoint() in C:\Unosquare\embedio\src\Unosquare.Labs.EmbedIO\System.Net\HttpConnection.cs: 140
in Unosquare.Net.WebSocketContext.get_UserEndPoint() in C:\Unosquare\embedio\src\Unosquare.Labs.EmbedIO\System.Net\WebSocketContext.cs: 233
```

Client is local, connecting from the same computer

embedio version 1.4.6.

**Comment by geoperez** [comment]
Hi @lansman, this is an expected behavior because when the client socket is closed, the Endpoint is not longer available, so OnClientDisconnected will always get you null and I think OnMessageReceived it's giving null when the connection is not longer there.

@mariodivece  Any thoughts?

**Comment by mariodivece** [comment]
If the connection is no longer there, then it should return null.
