### ISSUE TITLE
Tasks not handled correctly

### ISSUE THREAD

**Issue by kdblocher** [unosquare/embedio#66]
I suggest you guys read this blog and change `WebServer.RunAsync` accordingly: http://blog.stephencleary.com/2014/05/a-tour-of-task-part-1-constructors.html
* Use `Task.Run` instead of `Task.Factory.StartNew`, the latter shouldn't be used hardly ever
* Support cancellation better
  * currently inelegantly handled via `clientSocketTask.Wait(ct)`
  * pass a `CancellationTokenSource` argument instead of `CancellationToken`
  * Check `source.Token.IsCancellationRequested` inside the `while` loop
  * Catch/throw `OperationCanceledException` instead of `AggregateException`
*1 Use `async`/`await` if .NET 4.5 is present, allowing your `RunAsync` method to work concurrently as well as in parallel

We are the same developers that gave you the support initially (@marner2, @faeriedust, @Joe0), but we ourselves found out over time we were not doing it right either.

**Comment by mariodivece** [comment]
Do you have a pull request that we may use to implement your proposed changes?

**Comment by kdblocher** [comment]
I can see if I can put one together.  I thought it might be at least useful for you guys to read up about this topic, since the pattern is becoming a lot more commonplace.

**Comment by kdblocher** [comment]
There are still several problematic uses of Task.Factory.StartNew and sync-over-async antipatterns throughout the code, but I don't think they're fixed easily (from the outside).  I still suggest you take a look through the blog (for that matter, any of Stephen Cleary's writing) and read some of the common suggestions. Most are applicable in your case.

See http://stackoverflow.com/a/36355946 and https://msdn.microsoft.com/en-us/magazine/jj991977.aspx for more information.

**Comment by mariodivece** [comment]
I am reopening this issue because and marking it as an enhacement to change calls that can be changed to ConfigureAwait(false) i.e. those that don't require context. Are there any other specific recommendations that you might want to suggest @kdblocher ?

**Comment by kdblocher** [comment]
@mariodivece yes: follow the "async is viral" approach - e.g. everything lower-level that is asynchronous should be called by asynchronous methods itself. This is the most performant, and the cleanest.  (I actually tried to do this with your code but ran into a couple of pitfalls.)

I can add a couple of commits with small changes to demonstrate.

**Comment by geoperez** [comment]
@kdblocher check my latest commits, I've been updating the code to a better async/await approach.
