### ISSUE TITLE
Implement "safe shutdown"

### ISSUE THREAD

**Issue by kdblocher** [unosquare/embedio#69]
Our product has a 'soft restart' function, which allows us to reinitialize the entire application, usually because of some sort of major configuration change.  Our implementation disposes of all managed objects and rebuilds them.  In particular, we use an operating system "shutdown signal" metaphor: inform all running processes to stop, and when they all do, dispose and then we restart.

With embedio, it would be nice to keep track of all running `Task`s generated by each request in [`RunAsync`](https://github.com/unosquare/embedio/blob/69989232a947cab597463ea04c45145ca3fc8db5/src/Unosquare.Labs.EmbedIO/WebServer.cs#L346). On a call to some sort of theoretical `Stop` method, we would `await` on all of the running tasks, then call `WebServer.Dispose`. Optionally, some sort of timeout could be supplied, upon which we would cancel the `CancellationToken` and then call `Dispose`.

Of course, it is not completely trivial to track all of these: some sort of monitor would need to be implemented, or each individual request would have to kick off a subtask to remove itself from the ongoing request collection.

**Comment by pablovilchis** [comment]
Hi @geoperez @mariodivece: Is this something you're planning to support? If that so, I would like to explore such a model and help you if it's possible. Please let me know.

**Comment by mariodivece** [comment]
We have been able to restart embedio in other products without any problems. Not sure what the use case or limitation this suggests. @kdblocher coud you please post the code or an example that you believe should work and is not working?

**Comment by geoperez** [comment]
Any feedback?

**Comment by kdblocher** [comment]
It's probably easier to point you to [this page](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/hosting?tabs=aspnetcore2x) for ideas. We've since abandoned our approach of a "soft restart" and just restart the entire process periodically until we have time to revisit this (as an optimization).
