### ISSUE TITLE
Add SimpleConsoleLogger and use in example Doc

### ISSUE THREAD

**Issue by mariodivece** [unosquare/embedio#7]
Let's add a SimpleConsoleLogger as an out-of-the-box logger that you can plug into your setup.
Also update the readme.md and example code.

**Comment by geoperez** [comment]
SimpleConsoleLogger is ready, and documentation was updated.

**Comment by mariodivece** [comment]
http://unosquare.github.io/embedio/

This has no been updated yet :(

**Comment by geoperez** [comment]
Web site updated.
