### ISSUE TITLE
Can't install package

### ISSUE THREAD

**Issue by ashking** [unosquare/embedio#70]
Hi there,

Looking at the docs it seems very interesting and promising to use this. However, when I try to install I end up with the following error:

`You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

I'm on a Windows 10 Pro using Xamarin Studio Community.

Let me know if you would need more information.

P.S: Am from a JS dev background and very new to C#/.Net programming. Hence, at the moment I'm really relying hard on the provided documentation.

**Comment by geoperez** [comment]
Hello, can you upgrade your project to target 4.5.2?

**Comment by geoperez** [comment]
Closing.
