### ISSUE TITLE
HttpRequest ContentEncoding hardcoded to ISO-8859-1 instead of UTF8

### ISSUE THREAD

**Issue by japonophile** [unosquare/embedio#73]
First of all, thanks a lot for this great library!  It is simple and does the job very nicely (I'm using both WebSocket and REST API).

I encountered an issue recently with encoding, where the request content was garbled (when using non ASCII chars).
Looking at the code, it seems the ContentEncoding of the Request in HttpListenerContext is always Encoding.GetEncoding(0), regardless of the "Content-type" header.  Instead, it should follow the "Content-type" (or at least use UTF-8).

See:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type

Also see note on MSDN about GetEncoding(0):
"... encoding and decoding data using the default code page returned by Encoding.GetEncoding(0) is not recommended. For the most consistent results, you should use Unicode, such as UTF-8 ..."
https://msdn.microsoft.com/en-us/library/wzsz3bk3(v=vs.110).aspx

**Comment by japonophile** [comment]
Btw, here is the workaround I use:
```C#
    var requestBody = context.RequestBody();
    // Workaround an issue with EmbedIO which assumes request content encoding is ISO-8859-1
    requestBody = Encoding.UTF8.GetString(Encoding.GetEncoding(0).GetBytes(requestBody));
```

**Comment by geoperez** [comment]
Let me take a look. Thanks for the heads up.

**Comment by mariodivece** [comment]
It looks like the Mono port of the Request class is not reading the content-type (charset part) HTTP header and just fixing it to GetEncoding(0) which, like you pointed out, @japonophile is incorrect. @geoperez  could you please change it to read the encoding from content-type (charset part)? If there is no charset part, the default to URF-8 as MDN suggests.

**Comment by geoperez** [comment]
Sure.

**Comment by geoperez** [comment]
The new nuget contains the default encoder as UTF8 the Charset part is still in development.

**Comment by geoperez** [comment]
All done.
