### ISSUE TITLE
Binary data problem with WebSocket transmission on .NET Standard (.NET Core runtime)

### ISSUE THREAD

**Issue by buvar** [unosquare/embedio#74]
Hi, I created own WebSocket Server inherited from WebSocketsServer, but when I send there 10000 binary buffer (with Unosquare.Net.WebSocket), received buffer (in OnMessageReceived method) is corrupted. Sending 1000 bytes is ok. Method OnFrameReceived is not supported, as I understand from sources (works probably in 4.6 only) so I cannot build final buffer myself.

**Comment by geoperez** [comment]
Hi @buvar , what version are you using? I already noticed this issue after 1.6.

**Comment by buvar** [comment]
Hi, 1.6.5 - latest from NuGet

**Comment by geoperez** [comment]
Can you try with 1.6?

**Comment by buvar** [comment]
1.6 works ok

**Comment by geoperez** [comment]
Yeah, I need to investigate what we did wrong between versions.

**Comment by buvar** [comment]
Great! Please let me know here once repaired and commited. Thanks a lot!

**Comment by geoperez** [comment]
Sure, don't forget to star the project 👍

**Comment by geoperez** [comment]
@buvar I updated the package (1.6.5) with a patch to resolve the issue with websocket.

**Comment by geoperez** [comment]
@buvar any feedback?

**Comment by buvar** [comment]
Works as excpected, thank you!
