### ISSUE TITLE
Byte[] and Stream decompression extension

### ISSUE THREAD

**Issue by buvar** [unosquare/embedio#75]
Hi, I tried the extensions for compression and decompression and I have problem calling decompression, which raises the exception "System.NotSupportedException: Stream does not support writing". I searched it and found this solution:
http://stackoverflow.com/questions/1354639/writing-to-the-compression-stream-is-not-supported-using-system-io-gzipstream
which works fine and I used it as a workaround.

**Comment by buvar** [comment]
Don't know what the Pull request is for, but of course, I can :-). As the function "Compress" is there and one of the parameters is "Uncompress", which is not working, I thought it to be a bug in this case... :-)

**Comment by geoperez** [comment]
Hey @buvar can you take a look in Nuget 1.6.10 and check the issue again.
