### ISSUE TITLE
Unable to prevent logging

### ISSUE THREAD

**Issue by shravan2x** [unosquare/embedio#76]
As the title says, I am unable to prevent these logs from being displayed:

```
 02:14:28.762 INF >> [WebServer] Web server prefix 'http://localhost:9696/' added.
 02:14:28.775 INF >> [WebServer] Finished Loading Web Server.
 02:14:28.781 INF >> [WebServer] Started HTTP Listener
```

I have tried `Terminal.Settings.DisplayLoggingMessageType = LogMessageType.None;`. I am using version **1.6.6**.

**Comment by geoperez** [comment]
Hello @shravan2x, you are right the DisplayLoggingMessageType should be enough. Can you tell me what environment are you using? and also a code snippet where you start your server.

**Comment by shravan2x** [comment]
@geoperez I have the same issue on both `net46` and `netcore1_1`. Here is a copy of my code:

```c#
public class EmbedIoTestExperiment : WebModuleBase
{
    public override string Name => "EmbedIoTestExperiment";

    public EmbedIoTestExperiment()
    {
        AddHandler("*", HttpVerbs.Any, OnHttpRequest);
    }

    public void Play()
    {
        Terminal.Settings.DisplayLoggingMessageType = LogMessageType.None;

        WebServer server = new WebServer("http://localhost:9696");
        server.RegisterModule(this);

        server.RunAsync();
        Console.ReadKey();
    }

    public Task<bool> OnHttpRequest(HttpListenerContext context, CancellationToken cancellationToken)
    {
        context.Response.KeepAlive = true;
        context.Response.StatusCode = 200;
        context.Response.ContentType = "application/json";

        using (StreamWriter jsonWriter = new StreamWriter(context.Response.OutputStream))
        {
            jsonWriter.Write(JsonConvert.SerializeObject(new { success = true }));
            jsonWriter.Flush();
        }

        return Task.FromResult(true);
    }
}
```

**Comment by shravan2x** [comment]
@geoperez Any update on this?

**Comment by geoperez** [comment]
Not yet.

**Comment by shravan2x** [comment]
@geoperez This is creating a major block in release our application, could you take a look please?

**Comment by geoperez** [comment]
Try upgrading Swan dependency to version 0.14.1

**Comment by shravan2x** [comment]
I now get a compile error:

```
Assembly 'C:\\TestLab\TestLab\bin\Release\Unosquare.Swan.dll' must be strong signed in order to be marked as a prerequisite.
```

**Comment by shravan2x** [comment]
I tested on another project and it seems to work, but still needs to be disabled manually.

- **Can we set it to be disabled by default?**
- Also, as I mentioned in my previous message, it does not compile in some projects.

**Comment by geoperez** [comment]
@shravan2x the default is enabled and it won't change. Regarding to the issue that some project don't compile, is it still happening?

**Comment by shravan2x** [comment]
I don't think so, no. I'll close the issue.

**Comment by shravan2x** [comment]
Re-opening this issue because the strong-signing issue still exists.

`Assembly 'C:\ProjectName\bin\Release\Unosquare.Swan.dll' must be strong signed in order to be marked as a prerequisite.`

**Comment by geoperez** [comment]
Can you try the new EmbedIO 1.6.10 using the latest SWAN?

**Comment by shravan2x** [comment]
I just did, it works well. Thank you so much =)
