### ISSUE TITLE
WebApiHandler with GET Parameter

### ISSUE THREAD

**Issue by JochenTester** [unosquare/embedio#79]
I have to fetch get-request url´s with parameters, but i can´t get it to work...
this "Sample: http://ip-of-embedio-webserver/api/command/ABC" run´s fine

[WebApiHandler(HttpVerbs.Get, "/api/command/*")]
public bool GetCommand(WebServer server, Unosquare.Net.HttpListenerContext contex
{...

But this: Sample: http://ip-of-embedio-webserver/api/command/ABC?key01=value01&key02=value02  will not be catched by WebApiHandler. 

Please help...

**Comment by geoperez** [comment]
Hi @JochenTester, let me take a look.

**Comment by bufferUnderrun** [comment]
@JochenTester can't reproduced your bug. It works for me with both regexp/wildcard strategy.

**Comment by JochenTester** [comment]
hm... strange... could you publish your test code...  especially your RegExp solution (how to get "key01" ) perhaps I can see my mistake

**Comment by JochenTester** [comment]
I made it work. My error was a comma in one of the values (key01=First Name, surname). After replacing the comma in the request, EmbedIO runs like a charm. 

Previously:  http://ip-of-embedio-webserver/api/command/ABC?key01=First, Second
Now: http://ip-of-embedio-webserver/api/command/ABC?key01=First_Second

Is it possible to customize the parser, because you can't always adjust the transmitter of the requests?

**Comment by caverna** [comment]
It doesn't seems the comma is the problem, but your space!
Try this way: http://ip-of-embedio-webserver/api/command/ABC?key01=First,%20Second

**Comment by geoperez** [comment]
@JochenTester what do you mean by customize the parser? I'm not quite sure to understand the issue here.

**Comment by mariodivece** [comment]
All url parameters need to be url-encoded. No web server will understand url query string values that are not properly escaped.

**Comment by JochenTester** [comment]
Back from mountaineering...

I always try to fix my software so that errors are detected and logged. This allows third parties to understand what is going on internally, or how to process the parameters that the software reads. Unfortunately, this was only possible by testing and trying to find the error. I want a debug.output (logging) that indicates the special character are included - and what special characters.

For example: url (full URL) could not be parsed completely; The value for the XXX key contains special characters ABC. 

That could help others not to commit the same mistake.
Thanks for your help...

**Comment by mariodivece** [comment]
@JochenTester if you would like to suggest a change via a PR please do so. We are totally open to contributions!
