### ISSUE TITLE
setup issues

### ISSUE THREAD

**Issue by johnfg1** [unosquare/embedio#81]
Hello,
looks like a great project! need something like this for use on windows iot devices. anyway i have set my code up(in a gui based UWP app) and it doesnt seem to be handling the requests, im not sure why though.
startup:
        public MainPage()
        {
            start();
        }

        public void start()
        {
            var url = "http://localhost:9696/";
            var server = new WebServer(url, RoutingStrategy.Regex);

            server.RegisterModule(new WebApiModule());
            server.Module<WebApiModule>().RegisterController<WebRestControllers>();
        }

Listener: 
    class WebRestControllers : WebApiController
    {
        [WebApiHandler(HttpVerbs.Get, "/api/people/{id}")]
        public bool GetPeople(WebServer server, HttpListenerContext context, int id)
        {
            Debug.WriteLine("Get request called");
            try
            {
                return context.JsonResponse(id);
            }
            catch (Exception ex)
            {
                return HandleError(context, ex, (int)HttpStatusCode.InternalServerError);
            }
        }

        protected bool HandleError(HttpListenerContext context, Exception ex, int statusCode = 500)
        {
            var errorResponse = new
            {
                Title = "Unexpected Error",
                ErrorCode = ex.GetType().Name,
                Description = ex.ExceptionMessage(),
            };

            context.Response.StatusCode = statusCode;
            return context.JsonResponse(errorResponse);
        }
    }

**Comment by geoperez** [comment]
Hi @johnfg10, the support to UWP is experimental. We are facing similar issues. Right now we are not actively working on UWP but let you know when a more stable version comes up. Our testing approach  is using a Background Application to host the web server:

```csharp
public sealed class StartupTask : IBackgroundTask
    {
        public async void Run(IBackgroundTaskInstance taskInstance)
        {
            var deferral = taskInstance.GetDeferral();

            var server = new WebServer(9090);
            server.RegisterModule(new FallbackModule((ctx, ct) =>
            {
                ctx.JsonResponse(new {Hola = "Message"});
                return true;
            }));

            await server.RunAsync();

            deferral.Complete();
        }
    }
```

Anyway any additional feedback or pull request is welcomed.

**Comment by johnfg10** [comment]
ahh ok.. seems like nothing works correctly with UWP atm :( well i guess i could run a background task as well as the UI task.

**Comment by johnfg10** [comment]
ok so ive tried setting up a background task and i still get `localhost refused to connect.`
```
    public sealed class StartupTask : IBackgroundTask
    {
        BackgroundTaskDeferral deferral;
        public async void Run(IBackgroundTaskInstance taskInstance)
        {
            Debug.WriteLine("started");
            deferral = taskInstance.GetDeferral();

            var server = new WebServer(9090);
            server.RegisterModule(new FallbackModule((ctx, ct) =>
            {
                ctx.JsonResponse(new { Hola = "Message" });
                return true;
            }));

            await server.RunAsync();
            deferral.Complete();
        }
    }
```

**Comment by johnfg10** [comment]
Ok so im using a background task now
```
    public sealed class StartupTask : IBackgroundTask
    {
        BackgroundTaskDeferral deferral;
        public async void Run(IBackgroundTaskInstance taskInstance)
        {
            Debug.WriteLine("started");
            deferral = taskInstance.GetDeferral();

            var server = new WebServer(9090);
            server.RegisterModule(new FallbackModule((ctx, ct) =>
            {
                ctx.JsonResponse(new { Hola = "Message" });
                return true;
            }));

            await server.RunAsync();
            deferral.Complete();
        }
    }
```
and when connecting to http://192.168.0.17:9090 it says `192.168.0.17 took too long to respond.` :(

**Comment by johnfg10** [comment]
did you have to make any setting changes to the remote device to get it to work?

**Comment by johnfg10** [comment]
ok i finally got it part working it now works with the fallback module correctly!

**Comment by geoperez** [comment]
Hi, how did you get the fallback working?

**Comment by johnfg10** [comment]
if im honest im not quite sure just messed around created a few more projects and it just worked

**Comment by geoperez** [comment]
I see, but you are using the IBackgroundTask?

**Comment by mariodivece** [comment]
Or just attach the file with the sample project so we can see what is going on :)

**Comment by johnfg10** [comment]
I am yes and I will upload it shortly

**Comment by johnfg10** [comment]
[MediaShare.zip](https://github.com/unosquare/embedio/files/1187463/MediaShare.zip)

**Comment by geoperez** [comment]
@johnfg10 did you manage to use WebAPI?

**Comment by geoperez** [comment]
Closing issue...

**Comment by johnfg1** [comment]
sorry missed the email notification no i didnt
