### ISSUE TITLE
remote endpoint from websocketcontext

### ISSUE THREAD

**Issue by pablonardone** [unosquare/embedio#87]
This is not an issue, just a question.
How can I obtain the remote endpoint of the websocket from the notification "Unosquare.Labs.EmbedIO.Modules.WebSocketsServer.OnClientConnected(WebSocketContext context)", where context is of type System.Net.WebSockets.WebSocketContext?
Thank you.

**Comment by geoperez** [comment]
That class belongs to .NET Framework and checking MSDN Documentation (https://msdn.microsoft.com/en-us/library/system.net.websockets.websocketcontext%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396) I can't see a way to get that value using the WebSocketContext.

**Comment by pablonardone** [comment]
I proposed a change in issue #89 to address this limitation.
Sorry for have opened a new issue, I did not realize in continuing the conversation here.
