### ISSUE TITLE
WebSocketsModule.cs change request

### ISSUE THREAD

**Issue by pablonardone** [unosquare/embedio#89]
It would be very useful to introduce in the next release the following change to the module WebSocketModule.cs:

1) Change the line 296:

`OnClientConnected(webSocketContext);`

for the lines:

```
#if NET47
    OnClientConnected(webSocketContext, context.Request.LocalEndPoint, context.Request.RemoteEndPoint);
#else
    OnClientConnected(webSocketContext);
#endif

```
2) Change the line 544:

`protected abstract void OnClientConnected(WebSocketContext context);`

for the lines:

```
#if NET47
    protected abstract void OnClientConnected(WebSocketContext context, IPEndPoint localEndPoint, IPEndPoint remoteEndPoint);
#else
    protected abstract void OnClientConnected(WebSocketContext context);
#endif

```
This would solve the limitation of the Windows WebSocket interface that does not include the connection endpoints.

Thank you for this great library.

**Comment by geoperez** [comment]
Hi @pablonardone, we are going to integrate your changes in the next release. Thank you.

**Comment by geoperez** [comment]
New nuget 1.8.0.
