### ISSUE TITLE
SimpleConsoleLogger not asynchronous

### ISSUE THREAD

**Issue by mariodivece** [unosquare/embedio#9]
The SimpleConsoleLogger is completely synchronous. The calls to the console are degrading the performance of the request-response cycles. Pick a thread from the thread pool and use a ConcurrentQueue (https://msdn.microsoft.com/en-us/library/dd267265%28v=vs.110%29.aspx) or use other means such as a BlockingCollection as described here (http://stackoverflow.com/questions/3670057/does-console-writeline-block)

Please note that the above StackOverflow answer is not using a ThredPool Thread. Use a Thread Pool Thread instead.

**Comment by geoperez** [comment]
This is done.
