### ISSUE TITLE
SSL and .Net Core/Standard

### ISSUE THREAD

**Issue by Alkalinee** [unosquare/embedio#92]
Hey,
I just ported all my apps to .Net Core and noticed that it's not possible to establish SSL connections using embedio. For me, a webserver without HTTPS is useless, encryption is absoluetly necessary and I really love embedio. I have a few questions here: Why is there no ssl? In .Net Standard 2.0, the [HttpListener was added](https://apisof.net/catalog/System.Net.HttpListener) so you can remove your own implementation (and I imagine that the offical listener will support SSL). Why are there so many targets? Isn't the goal of .Net Standard to reduce the targets to only one platform that will work with every framework?

**Comment by geoperez** [comment]
Yes, we need to give it a try to net standard 2.0 new APIs properly.
Meanwhile any pull request is welcomed.

**Comment by Alkalinee** [comment]
Closed because the pull request was merged. Thank you.
