### ISSUE TITLE
Serious performance issue after upgrading to v1.8.0

### ISSUE THREAD

**Issue by bufferUnderrun** [unosquare/embedio#94]
Hi,

After upgrading from v1.6.10 to v1.8.0 and so retargeting my app to .NET 4.6, i'm facing serious performance issue.

With only the staticfiles module loaded serving a index.html and 10 css/javascripts files, many files are loading fast as normal (10 to 60ms) but somes are loading incredibly slow (from 10 to 75**sec** !!). The problem appear each time and on random files...

Code to reproduce the issue

```C#
            using (var server = new WebServer("http://*:2393/"))
            {
               // serve statics files (index.html and somes css, js files
                server.RegisterModule(new StaticFilesModule(@"C:\www\ConsoleApplication1\html\"));
                server.Module<StaticFilesModule>().UseRamCache = true;
                server.Module<StaticFilesModule>().DefaultExtension = ".html";
                server.RunAsync();
                Console.ReadKey(true);
            }
```

I've tested the v1.7.0 release and it works as expect. So the problem come from a commit between the v1.7.0 and v1.8.0. I don't know if the bug is in the staticFileModule itself or the underlying httplistener...

Thanks for your answer

**Comment by geoperez** [comment]
I didn't notice the issue, let me take a look.

**Comment by bufferUnderrun** [comment]
Extras infos : Win7 SP1 + Visual Studio 2013 Update 5 + .NET Framework 4.6[.1,.2] [SDK|Targeting Pack] installed

**Comment by mariodivece** [comment]
I know what the problem is. It is a Windows 7 specific issue with thread time slices. @geoperez come talk to me and I will explain how to fix.

**Comment by bufferUnderrun** [comment]
@mariodivece you rock !

and thanks to both of you for support.

**Comment by geoperez** [comment]
@bufferUnderrun do you have LocalSession module on?

**Comment by bufferUnderrun** [comment]
@geoperez yep LocalSessionModule on

**Comment by geoperez** [comment]
Can you try to disable it? I found a bug there.

**Comment by bufferUnderrun** [comment]
Excuse-me, my previous answer was wrong. I used the localSessionModule for the app i've tried to upgrade to v1.8.0 BUT i don't use localSessionModule for the snippet i post above.

Only StaticModule ON and the bug is always here...

**Comment by geoperez** [comment]
Ok, thank you for the clarification. Anyway I need to resolve the LocalSessionModule issue too...

**Comment by geoperez** [comment]
@bufferUnderrun can you try version 1.9 please?

**Comment by bufferUnderrun** [comment]
Unfortunately, the issue is still there... https://www.noelshack.com/2017-38-5-1506063752-capture-latence.png (release 1.9 on NET462)

**Comment by geoperez** [comment]
I see. Let me take a look in the commits to see what changes.

**Comment by geoperez** [comment]
I noticed you are using Firefox, so testing the Sample App with Firefox I got the same issue as you retrieving a file with status 304... status 200 it's working fine...

![image](https://user-images.githubusercontent.com/1775792/30756353-fcae71ac-9f8f-11e7-975a-56380942f7af.png)

**Comment by geoperez** [comment]
I'm able to see the issue only when the headers IfModifiedSince, IfNoneMatch y Cache-Control (max) are set...

But the issue is way before StaticFileModule, I'm not receiving in time the HttpContext.

**Comment by geoperez** [comment]
This is not happening with Net Standard 2.0, so it may be an issue with the custom HttpListener.

**Comment by bufferUnderrun** [comment]
@geoperez i feel less alone. Yes i thinks the issue come from the custom httplistener too.

**Comment by geoperez** [comment]
@bufferUnderrun can you try the new version 1.9.1?

**Comment by bufferUnderrun** [comment]
@geoperez perfect ! You can close the issue.

**Comment by geoperez** [comment]
👍
